### ISSUE TITLE
Can't override icons

### ISSUE THREAD

**Issue by NoNamePaul** [brittyazel/Neuron#101]
I don't know to what extend this is intended but I only seem to able to override the icons of some specific buttons/macros. 
e.G.
```
#showtooltip 
/cast [talent:1/1] Force of Nature 
/cast [talent:1/2] Warrior of Elune
```
and the icon manually set to the [starlord icon](http://www.wowhead.com/icon=462651/spell-shaman-measuredinsight)
Works absolutely fine: It shows the icons of "FoN" or "WoE" accordingly when they are specced and the default starlord icon otherwise since none of the other spells are usable.
Same with the T6-Talent row (same basic structure)

The problem is I can't override icons of buttons/macros that only have one spell even though it is not available at all times (e.G. cyclone (PvP-talent)).
I can drag it to my bars but i can't override it's icon which makes it an transparent button when it is not usable and i have these weird "holes" in my bars. I'd like to see the icon at all time (since i know when i can use it, an when not).

And i'd like to override icons of buttons/macros even though they are only a single spell and usable without any conditions (e.G. moonfire, etc.)

**Comment by brittyazel** [comment]
This is fixed
