### ISSUE TITLE
Dragging buttons between buttons or bars or off the bars doesn't always work correctly

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#106]
Sometimes it leaves the bars in config mode, sometimes the wrong button is added (I think this can happen when moving a button to an empty button location after having added or moved a button previously), sometimes the button being moved off the bar remains stuck to the cursor even when you click away from the bars (infrequent but it's happened a few times), etc.

**Comment by brittyazel** [comment]
Hrm. I'll have to play with it. I thought I finally had this one ironed out. I spent a TON of time rewriting this a couple months ago

**Comment by raysmith59** [comment]
Ok, I'll come up with some specific examples then.
