### ISSUE TITLE
The Blizzard vehicle bar is coming up when an equivalent Neuron bar goes into vehicle mode

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#108]
That's new as of today's release, figured I'd report it here, I've spammed the comment section enough for one day.

**Comment by brittyazel** [comment]
So the vehicle bar isn't being suppressed? I'll add some logic in to suppress that bar if at least 1 bar has a vehicle state set

**Comment by raysmith59** [comment]
That seems to be the case, yeah, at least the one time I've used a vehicle bar recently for a WQ on Broken Shore (the Brew one).

**Comment by Fizgig1973** [comment]
Happening to me as well. Noticed it when doing the quest to kill the undead pirates from the boat in Stormrage.

**Comment by Koskun** [comment]
Similar to the issue I had a few versions ago.  However the vehicle bar does go away when out of the "vehicle", and I don't have to /reload.

Also of note, the default Follower/Bodyguard button is showing up as the default at the bottom-center of the screen for me, this however doesn't go away.  I do want to say it isn't across all characters however.  

I'm going to be wiping out all Neuron settings this weekend and will report if it is still happening then.

**Comment by brittyazel** [comment]
Yeah I'm still working on this. Also that Follow/Bodyguard bug is with the extrabar, and has already been fixed :-)

**Comment by Trajin** [comment]
My workaround for the vehicle frames being in the way are to use the MoveAnything addon and just hide the vehicle frames.

**Comment by Fizgig1973** [comment]
Tried using Move Anything to hide, but it was causing problems with other frames.

**Comment by Koskun** [comment]
A workaround to hide something that is supposed to be hidden by Neuron isn't a work around.  I don't use MoveAnything because I have other addons that do it themselves to what they are changing.

**Comment by brittyazel** [comment]
I'm not in the state ATM. Can someone look up for me the name of the blizzard bar frame? Onxe I have the frame I can disable it much like the other blizzard frames, I just don't have a computer with WoW on it to dig though the global namespace

**Comment by Fizgig1973** [comment]
How would I go about finding the frame for you?

**Comment by Addonman** [comment]
With moveanything options  or /framestack and  pointing to that frame you can get it.

I just whant to add to this bug.Blizzard vehicke bar isnt being removed if you are still in combat.Happen to me few times in dungeon or raids .And then i had to dps by pusjing button on memeor when i put certain spells.Doable but no too much convienient.

**Comment by Addonman** [comment]
Not sure if i hit right frame but could be UIparent ,mainmenubar

**Comment by brittyazel** [comment]
Ok this seems to be called the overrideactionbar

I believe I have code already for this bar, it just isn't working
