### ISSUE TITLE
The extra action button Request Stop also shows for the default Blizzard frame

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#111]
Not sure yet if it's just Request Stop but that one is consistently causing a dupe button to show up down where the Blizzard frame equivalent would be.

**Comment by brittyazel** [comment]
Can you send a screenshot? I'll add some logic to mute the default bar if we have an extra bar created

**Comment by raysmith59** [comment]
Long time user, first time screenshot includer... hoping for the best:

![image](https://user-images.githubusercontent.com/2917594/41063729-73eed11c-69a7-11e8-9f8a-b8a9002d7829.png)
