### ISSUE TITLE
Recharge animation for abilities with charges don't disappear on stance change

### ISSUE THREAD

**Issue by NoNamePaul** [brittyazel/Neuron#114]
Example:
I have frenzied regeneration on one button of my bar in bear form. When it goes on cooldown the yellowish cooldown ring appears (as with all charged abilities). 
When I now switch to any other form/stance the cooldown ring stays there:
![cooldownringneuron](https://user-images.githubusercontent.com/848158/41383225-f0174eae-6f6f-11e8-9fcb-50706d71a046.gif)
(btw you can also see Issue #102 there)

**Comment by brittyazel** [comment]
Yeah this is a current issue with bar states. I need to rework it so that cooldowns take state into account, as right now it's per button regardless of state

**Comment by brittyazel** [comment]
This is fixed
