### ISSUE TITLE
Extra action button x 2

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#116]
Getting what i think is blizzard and neuron extra action button at same time on most chars.on one char it seems i lost extra action button because  i cant see it.i tried recreateing  it but it still doesnt show up. Not sure if i have to go into zone /quest for blizz to create it but its not showing  up at place i set coordinates to.

**Comment by brittyazel** [comment]
hrm, I'm not having any issues with my Extra Action Button. I added some code in there specifically to disable to default if we have a Neuron variant. Where are you that you are having these issues?

**Comment by brittyazel** [comment]
Is this still an issue?

**Comment by Addonman** [comment]
On warr where its easy to test -in dalaran jump to skyhold i dont see double extra action button any more . On other chars (most on Argus) i still see when i log in empty extra action button frame popping up on diff spot then where i put Neuron extra action button. Is there spot in game where its easy to test it?

**Comment by brittyazel** [comment]
I still can't replicate it. Can you post a screenshot where you are seeing this issue? There's one more thing I can do to help mitigate this, but the code I have now should be adequate as it is

**Comment by brittyazel** [comment]
Ok, I think I finally fixed it. Can you test the version that's in master and let me know if that fixes it for you?
