### ISSUE TITLE
Unable to Edit Buttons (right click minimap icon)

### ISSUE THREAD

**Issue by denz1942** [brittyazel/Neuron#117]
Getting the following error:

Message: Interface\AddOns\Neuron\Bar-Modules/Neuron-Pet.lua:170: Usage: GetPetActionInfo(index)
Time: 06/25/18 17:44:15
Count: 1
Stack: Interface\AddOns\Neuron\Bar-Modules/Neuron-Pet.lua:170: Usage: GetPetActionInfo(index)
[C]: ?
[C]: in function `GetPetActionInfo'
Interface\AddOns\Neuron\Bar-Modules/Neuron-Pet.lua:170: in function `HasPetAction'
Interface\AddOns\Neuron\Bar-Modules/Neuron-Pet.lua:711: in function `SetObjectVisibility'
Interface\AddOns\Neuron\Neuron.lua:1335: in function `ToggleBindingMode'
Interface\AddOns\Neuron\Neuron.lua:1261: in function `ToggleButtonEditMode'
Interface\AddOns\Neuron\Neuron-MinimapIcon.lua:71: in function `OnClickHandler'
Interface\AddOns\Neuron\Neuron-MinimapIcon.lua:33: in function `OnClick'
...e\AddOns\Neuron\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:117: in function <...e\AddOns\Neuron\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:117>

Locals:

**Comment by brittyazel** [comment]
Can you give me more info? What class/spec are you. Does this always happen?

**Comment by denz1942** [comment]
Unholy Death Knight.
I have disabled all addons except Neuron just to be sure.

**Comment by brittyazel** [comment]
Is that with or without a pet?

**Comment by brittyazel** [comment]
Weird I can't replicate this issue. I went ahead and added a safety check to that function though. Mind downloading the latest code from MASTER and testing if it fixes it for you?

**Comment by denz1942** [comment]
Yes, It is working now.
