### ISSUE TITLE
Flyouts don't have tooltips

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#121]
Especially problematic for the portal/teleport flyouts for mages, I don't have the button icons memorized.

**Comment by jomo666** [comment]
On my mage solved this problem by editing the generated macro, and changed the ```c``` e.g. the "clickable" to ```m``` e.g. mouseover.  Strange, but for the _mouseover_ portals/teleports the tooltips works.

So, you can drag the teleport and portal spells from the spell-book, to the bar, and then right-click on the Neuron minimap icon (brings the edit mode), and right click on the particular dragged button, and change the ```c``` to ```m```.

e.g. my mage now using this:

```
...
/flyout blizz:12:l:b:t:1:m
```
note the ```m```.

**Comment by brittyazel** [comment]
Is this still happening? I don't have a mage so I can't test. Hunter's at the very least have the tooltips for their CallPet ability. It should, in theory, work the same for mages

**Comment by raysmith59** [comment]
Tooltips are showing up but a previous issue has re-appeared, I'll submit that one separately.
