### ISSUE TITLE
slash commands not working

### ISSUE THREAD

**Issue by pottervogel** [brittyazel/Neuron#125]
edit and config do not work anymore

**Comment by brittyazel** [comment]
Yeah I have to rewrite those slash commands. I changed a ton on how we launch eeit and config mode, and unfortunately the slash commands paid the price

**Comment by pottervogel** [comment]
ah, ok. would it be possible when you rewrite those (then, whenever) to make the "current bar" slash commands  work with barID too/instead so we could use them in macros? that would be awesome

**Comment by pottervogel** [comment]
sure, thank you so much

**Comment by brittyazel** [comment]
fixed
