### ISSUE TITLE
Incorrect Mount or Spell placed on hotbar

### ISSUE THREAD

**Issue by Riounis** [brittyazel/Neuron#127]
Almost always, when I drag a mount from my mount journal to the hotbar, it places the wrong mount on the hotbar. The mount placed on the hotbar is not always the same when you attempt to put the same mount on the hotbar. For example, when I try to put my Highlord's Golden Charger mount onto the hotbar, sometimes it will turn into the Lucid Nightmare, and other times it will turn into a nightsaber mount I don't have.

**Comment by brittyazel** [comment]
Interesting. I'll see if I can replicate this when I'm back in the USA in a few days. Thanks for the report

**Comment by Riounis** [comment]
If you'd like a video of it occurring, please let me know.
