### ISSUE TITLE
global save settings

### ISSUE THREAD

**Issue by Trajin** [brittyazel/Neuron#13]
This was my only complaint about Ion before you took over.   The menu bar and bag bar were save globally meaning that each of my toons had those bars saved in the same spot.   The other bars were saved per character.   Would you be able to change how these bars are saved?   My work around was to edit the LUA for those two bars so that they would be saved per character.   I'd rather not have to do this each time you updated.

Thanks

**Comment by brittyazel** [comment]
Yeah it's on my to-do list. I'd like to rework many of the profile save settings, but I need to do so in a way that doesn't break everyone's current profiles, which adds some complexity.

I'll bump this request up in priority though, and I'll get to it asap. I'm swamped at work atm, so my dev time is lacking a bit. But it'll get done

**Comment by Trajin** [comment]
I was just looking at how to use my workaround on neuron and it's the TOC file I modify.   I understand it would be messy to keep it working for everyone else.   Thank you for your continuing effort with this addon.  I'm one of them that has been using this since it was Trinity.

**Comment by brittyazel** [comment]
Fixed in 0.9.8 (not a pretty fix, but a stable one).
