### ISSUE TITLE
Possess/Vehicle/Override stance bars don't automatically get an Exit button

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#133]
Pretty sure that used to happen.  Ironically I'm able to make use of the one in the Blizzard bar that's still showing up in that scenario so maybe keep that issue around until this one gets fixed.  :)

**Comment by brittyazel** [comment]
Is this still an issue?

**Comment by brittyazel** [comment]
Yeah I've tried to effectively make the "Exit Button" be the de-facto way to exit vehicles. There are still situations though where the possess/vehicle/override buttons get their own unique exit button, but that is up to how Blizz codes the quest. I think only place this doesn't work well is during mind controls, but it's easy enough to 'esc' out of the MC, and it works about how I think the default UI works.

I'm going to close this for now, feel free to reopen if you still see issues

**Comment by raysmith59** [comment]
Yeah, that's fine.  I did get a vehicle bar recently where the 10th button was a "special" (return to base or somesuch), I think that's where the exit button used to go but I think the current behaviour is fine.
