### ISSUE TITLE
Extra action and Zone buttons are greyed out and don't have tooltips

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#134]
They brighten up only when activated, seems like, which is brief, I think they should always be bright when the ability is available.  Tooltips would help, too.

**Comment by DivertedCircle** [comment]
I'm not getting the error with them not being lit up but I am missing tooltips.

**Comment by raysmith59** [comment]
That may be another legacy issue that the profile reset will fix, I'll follow up once I have a chance to figure out if the buttons are still greyed out for me or not.

**Comment by Febilian** [comment]
I'm experiencing this as well. The buttons are grayed out, as though they are unavailable(although clicking them DOES work if prerequisites for the ability are met; just no visual indication whether it will work or not), and mousing over either button offers no tooltips to explain what they do. I only installed the addon maybe... two or three weeks ago? It was after patch 8.0 dropped, anyways, so I couldn't say whether this doesn't happen with a fresh install.

**Comment by brittyazel** [comment]
Is this fixed now?

**Comment by raysmith59** [comment]
Not for the ExtraActionBar(Button?) as of 35a, still greyed out and no tooltip, haven't had a ZAB yet to try.
