### ISSUE TITLE
Item count buttons are greyed out

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#135]
I figured out last week that if you do a #showtooltip <itemname> macro on a bar it will show you the count of that item, that addresses something I'd asked about in the comment section recently and is great.  However, the icon is greyed out when that happens if the item isn't useable (ie. doesn't have an on-use function... cloth, ore, etc).  Items with an on-use (fishing bait, for instance) aren't greyed out.  I'm not exactly sure what the implementation would be for this since generally unuseable items should be greyed out but maybe in the case of an item that doesn't even have an on-use function have it not be greyed out.

**Comment by brittyazel** [comment]
Yeah I'll have to add some logic to this one. I'm actually surprised that you can drag unusable items to the bars now...I don't recall that being possible before, but maybe I'm wrong

**Comment by raysmith59** [comment]
You can't drag, I just manually added a #showtooltip <itemname> to a blank button and it mostly works.  Just seeing if we can get it up to completely working.  :)

**Comment by brittyazel** [comment]
hrm, on mine I can drag.... are you sure you can't drag an item now?

**Comment by raysmith59** [comment]
I tried dragging some ore to the bar and nothing happened.  Tried putting the bar into edit mode first and still nothing.  Maybe you were dragging an item with a Use function?

**Comment by brittyazel** [comment]
nope I definitely am not. I just dragged some Silk cloth to the bar and had it properly show the stack and whatnot. I'm not sure why yours is doing nothing....

Can you try for me temporarily on a clean profile to see if maybe its a profile thing? all of my chars have no problem dragging everyday items onto the bars. The initial bug still stands though, they are all greyed out, I need to figure out how to address that

**Comment by raysmith59** [comment]
I did a profile reset and you're right, I can now drag onto the bar... not sure what was presenting that before.  Downside, I'm now getting a LUA error that I wasn't before (unrelated to the item stack thing) that I'll report separately.
