### ISSUE TITLE
LUA error while in combat while mounted on the Tree of Life

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#137]
From the Darkshore WQ.

Message: [ADDON_ACTION_BLOCKED] AddOn 'Neuron' tried to call the protected function 'NeuronPetButton1:SetAttribute()'.
Time: Thu Jul 26 09:01:35 2018
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Neuron' tried to call the protected function 'NeuronPetButton1:SetAttribute()'.
Interface\AddOns\Neuron\Neuron-Bars.lua:1863: in function `UpdateObjectVisibility'
Interface\AddOns\Neuron\Bar-Modules/Neuron-Pet.lua:426: in function <Interface\AddOns\Neuron\Bar-Modules/Neuron-Pet.lua:426>

Locals: <none>

**Comment by raysmith59** [comment]
I've also seen this a few times on my hunter, not sure what's happening at the time to cause it, though, it's not happening often enough to have caught the pattern.

**Comment by brittyazel** [comment]
Ya fortunately these aren't lua erros, just taint warnings. But I need to fix them anyhow. Neuron has SO MANY taint warnings

**Comment by AlexFolland** [comment]
Advice to work around the issue for now: use BugSack so the messages don't appear intrusively while you're playing, and instead are logged in BugSack for easy viewing later.

**Comment by brittyazel** [comment]
The above error is a taint error and as such would only visibly show if they were using something like bugsack already :-)

**Comment by brittyazel** [comment]
This is fixed
