### ISSUE TITLE
moonkin form seperate bar

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#138]
Not sure if that a real neuron issue or blizzard thing since i see in spell pane that moonkin form isnt considered shapeshift like other forms .Is that intened behavior that when ppl switch into moonkin form they dont get new bars for that form or bug?First i thought it was conected to talents and balance afinity but same behavoir is in balance spec. Perhaps its fine for balance spec to use same buttons /bar for normal form and balance form(even thought it would be nice to have option and new bar for moonkin form + to fill  bar for normal and balance at the same time). but when youare  in bear spec not having bar for moonkink form adds spells that you need to put in action bar 3,4,....  because other bars are already filled with  bear spells and the its get messy if want to use moonkin spells .

**Comment by brittyazel** [comment]
This has been fixed. Blizzard decided to take the "name" return parameter away from GetShapeshiftFormInfo(), and thus I've now had to make a table of the Form name strings and spellIDs and do a spellID querry each time...bleh! Thanks blizz :-|
