### ISSUE TITLE
[Bug] Cast Bar Failed on Spam Casting

### ISSUE THREAD

**Issue by ZeroPoin7** [brittyazel/Neuron#143]
The cast bar shows "Failed" with a red cast bar when you spam spells over each other. Your character is still casting the original spell, but the cast bar does not show it anymore. The cast bar should keep displaying the original spell name, icon and cast background/progress color.

In addition, it would be nice if we can size and position the cast icon if possible.

**Comment by brittyazel** [comment]
Yeah this was a side effect of an API change that blizzard out in. The game no longer reports which spell failed to cast when you cancel the cast. I need to figure out a way to get this info from someone else now. I don't know why vluzz removed all this useful info from the game API
