### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#145]
Was updateing my chars bar and when i got to my hunter this errors started to pop up and mess up half my bars ,not main one but additional omes where i put my macros,flyouts,profession stuff ,using certain items etc..
Message: ..\AddOns\Neuron\Neuron-Flyouts.lua line 810:
   Error: No flyout found for ID=%i
Debug:
   [C]: GetFlyoutInfo()
   Neuron\Neuron-Flyouts.lua:810:
      Neuron\Neuron-Flyouts.lua:808
   (tail call): ?
   Neuron\Neuron-Flyouts.lua:891: Flyout_UpdateButtons()
   Neuron\Neuron-Flyouts.lua:1174: UpdateFlyout()
   Neuron\Neuron-Buttons.lua:3315: SetAux()
   Neuron\Neuron-Bars.lua:1221: LoadObjects()
   Neuron\Neuron-Bars.lua:3423: Load()
   Neuron\Neuron-Bars.lua:262:
      Neuron\Neuron-Bars.lua:249
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:571: EnableAddon()
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:651:
      ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:445: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:488: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:1193:
      ..\FrameXML\UIParent.lua:1089
   [C]: ?

Message: ..\AddOns\Neuron\Neuron-GUI.lua line 496:
   attempt to concatenate field 'objCount' (a nil value)
Debug:
   Neuron\Neuron-GUI.lua:496: UpdateBarGUI()
   Neuron\Neuron-GUI.lua:1056:
      Neuron\Neuron-GUI.lua:1030
Locals:
self = <table> {
 SubFrameHoneycombBackdrop_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:236
 BarListScrollFrameUpdate = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1115
 updateIconList = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2839
 modules = <table> {
 }
 BarEditor_DeleteBar = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1249
 NeuronPanelTemplates_DeselectTab = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:288
 flyoutTypeSetter = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3587
 visOptionOnClick = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1553
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 NeuronPanelTemplates_TabResize = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:324
 VisEditorScrollFrame_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1939
 IsEnabled = <function> defined @Interface\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 ObjEditor_OnClick = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:4015
 ActionListScrollFrameUpdate = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2409
 hookHandler = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3526
 ADDON_LOADED = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:159
 RegisterMessage = <function> defined @Interface\AddOns\AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 UnregisterMessage = <function> defined @Interface\AddOns\AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 MainMenu_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3513
 hooks = <table> {
 }
 BarOptions_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1314
 runUpdater = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3539
 ObjEditor_OnEnter = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3995
 macroIconOnClick = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2820
 SetEnabledState = <function> defined @Interface\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @Interface\AddOns\AchieveIt\libs\AceHook-3.0\AceHook-3.0.lua:274
 macroNoteEdit_OnTextChanged = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2780
 ColorPicker_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3489
 SubFrameBlankBackdrop_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:222
 sbTypeOnClick = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:4290
 OnEnable = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:121
 updateCustomState = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:852
 ObjectEditor_OnShow = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2278
 target_options = <table> {
 }
 BarEditor_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:885
 NewModule = <function> defined @Interface\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:266
 EditBox_PopUpInitialize = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:383
 DeleteButton_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1240
 remapOnTextChanged = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1682
 BarList_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1000
 PLAYER_SPECIALIZATION_CHANGED = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:152
 GetName = <function> defined @Interface\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 createflyoutmacro = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3608
 SubFrameBlackBackdrop_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:200
 name = "Neuron_GUI"
 VisEditor_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1911
 ButtonEditor_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3032
 Disable = <function> defined @Interface\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddo

Message: ..\AddOns\Neuron\Neuron-Bars.lua line 1247:
   bad argument #1 to 'ipairs' (table expected, got nil)
Debug:
   [C]: ipairs()
   Neuron\Neuron-Bars.lua:1247: SetObjectLoc()
   Neuron\Neuron-Flyouts.lua:1389:
      Neuron\Neuron-Flyouts.lua:1389
Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

Message: ..\AddOns\Neuron\Neuron-Bars.lua line 2156:
   attempt to compare nil with number
Debug:
   Neuron\Neuron-Bars.lua:2156: AddObjectsToBar()
   Neuron\Neuron-GUI.lua:987:
      Neuron\Neuron-GUI.lua:987
Locals:
self = <table> {
 CDAlphaSet = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:3346
 modules = <table> {
 }
 SetState = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:2253
 OnKeyDown = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:1603
 CreateNewBar = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:1968
 PadVSet = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:3002
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 CreateHandler = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:800
 ScaleBar = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:3050
 SetDefaults = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:1361
 IsEnabled = <function> defined @Interface\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 ConcealBar = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:2703
 SpellGlowSet = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:2562
 IsMouseOverSelfOrWatchFrame = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:349
 RegisterMessage = <function> defined @Interface\AddOns\AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 UnregisterMessage = <function> defined @Interface\AddOns\AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 Pulse = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:1726
 RemoveObject = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:2178
 Stick = <function> defined @Interface\AddOns\Neuron\Neuron-SnapTo.lua:153
 SetPerimeter = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:1320
 Hook = <function> defined @Interface\AddOns\AchieveIt\libs\AceHook-3.0\AceHook-3.0.lua:274
 SetRemap_Paged = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:1378
 OnEnable = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:249
 OnKeyUp = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:1634
 OnInitialize = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:210
 UnregisterAllEvents = <function> defined @Interface\AddOns\AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 spellGlowMod = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:2531
 ToolTipSet = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:2832
 RemoveObjectsFromBar = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:2216
 PadHSet = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:2979
 AddVisibilityDriver = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:583
 OnClick = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:1461
 SetVisibility = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:2389
 CreateWatcher = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:1045
 GetName = <function> defined @Interface\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 name = "Neuron_Bar"
 Disable = <function> defined @Interface\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:345
 Unhook = <function> defined @Interface\AddOns\AchieveIt\libs\AceHook-3.0\AceHook-3.0.lua:418
 LoadData = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:1820
 AuraTextSet = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:3371
 HideZoneAbilityBorder = <function> defined @Interface\AddOns\Neuron\Bar-Modules/Neuron-ZoneAbility.lua:495
 CountTextSet = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:3271
 SetCastingTarget = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:3439
 ClearVisibilityDriver = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:604
 AlphaUpSpeedSet = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:3136
 ColumnsSet = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:2896
 moduleName = "Bar"
 UnregisterEvent = <function> defined @Interface\AddOns\AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 SetObjectLoc = <function> defined @Interface\AddOns\Neuron\Neuron-Bars.lua:1233
 OnEnter =

**Comment by brittyazel** [comment]
I can't replicate this. I need to know more how you can replicate this 100% of the time so I can investigate further

**Comment by Addonman** [comment]
Hard to tell you how to replicate this since i happens right as i log in. 3 out of 5 action bars gone and i could even delete or do anthing to them them since i got this neuron gui error. Btw where is Neuron storing profiles these days since i tried deleting neuron profile from my char wtf folder but nothing happened .In the end i went to another char and delete profile from there and that finally worked so i could recreate bars from start and fix my problem(hopeing it wont happen again in future).
Message: ..\AddOns\Neuron\Neuron-GUI.lua line 496:
   attempt to concatenate field 'objCount' (a nil value)
Debug:
   Neuron\Neuron-GUI.lua:496: UpdateBarGUI()
   Neuron\Neuron-Bars.lua:1520: OnClick()
   Neuron\Neuron-Bars.lua:1931:
      Neuron\Neuron-Bars.lua:1931
Locals:
self = <table> {
 SubFrameHoneycombBackdrop_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:236
 BarListScrollFrameUpdate = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1115
 updateIconList = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2839
 modules = <table> {
 }
 BarEditor_DeleteBar = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1249
 NeuronPanelTemplates_DeselectTab = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:288
 flyoutTypeSetter = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3587
 visOptionOnClick = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1553
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\TradeSkillInfo\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 NeuronPanelTemplates_TabResize = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:324
 VisEditorScrollFrame_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1939
 IsEnabled = <function> defined @Interface\AddOns\TradeSkillInfo\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ObjEditor_OnClick = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:4015
 ActionListScrollFrameUpdate = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2409
 hookHandler = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3526
 ADDON_LOADED = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:159
 RegisterMessage = <function> defined @Interface\AddOns\CallbackHandler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\CallbackHandler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 MainMenu_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3513
 hooks = <table> {
 }
 BarOptions_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1314
 runUpdater = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3539
 ObjEditor_OnEnter = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3995
 macroIconOnClick = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2820
 SetEnabledState = <function> defined @Interface\AddOns\TradeSkillInfo\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Interface\AddOns\TradeSkillInfo\Libs\AceHook-3.0\AceHook-3.0.lua:274
 macroNoteEdit_OnTextChanged = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2780
 ColorPicker_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3489
 SubFrameBlankBackdrop_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:222
 sbTypeOnClick = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:4290
 OnEnable = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:121
 updateCustomState = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:852
 ObjectEditor_OnShow = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2278
 target_options = <table> {
 }
 BarEditor_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:885
 NewModule = <function> defined @Interface\AddOns\TradeSkillInfo\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 EditBox_PopUpInitialize = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:383
 DeleteButton_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1240
 remapOnTextChanged = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1682
 BarList_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1000
 PLAYER_SPECIALIZATION_CHANGED = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:152
 GetName = <function> defined @Interface\AddOns\TradeSkillInfo\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 createflyoutmacro = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3608
 SubFrameBlackBackdrop_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:200
 name = "Neuron_GUI"
 VisEditor_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1911
 ButtonEditor_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3032
 Disable = <function> defined @Interface\Add

**Comment by brittyazel** [comment]
The profiles are all stored at the account level. There should be one .lua
file for neuron and that's it.
 Sorry you got the error, it might be an old profile thing coming back to
haunt. And unfortunately those are near impossible to replicate. If the
profile system we're designed better we could avoid much more of these, but
alas it's still a dinosaur that I'm scared to death of to touch.

**Comment by Addonman** [comment]
After recreating bars for all specs i went to bm and use call of pets abitlity and this error happened
Count: 1
Message: ..\AddOns\Neuron\Neuron-Buttons.lua line 1345:
   attempt to index a nil value
Debug:
   Neuron\Neuron-Buttons.lua:1345: MACRO_UpdateUsableSpell()
   Neuron\Neuron-Buttons.lua:1453: MACRO_UpdateButton()
   Neuron\Neuron-Buttons.lua:1328: MACRO_UpdateAll()
   Neuron\Neuron-Buttons.lua:1661: ?()
   Neuron\Neuron-Buttons.lua:1757: MACRO_OnEvent()
   Neuron\Neuron-Buttons.lua:3377:
      Neuron\Neuron-Buttons.lua:3377

**Comment by Addonman** [comment]
Did realod and again 
Message: ..\AddOns\Neuron\Neuron-Buttons.lua line 1345:
   attempt to index a nil value
Debug:
   Neuron\Neuron-Buttons.lua:1345: MACRO_UpdateUsableSpell()
   Neuron\Neuron-Buttons.lua:1453: MACRO_UpdateButton()
   Neuron\Neuron-Buttons.lua:1328: MACRO_UpdateAll()
   Neuron\Neuron-Buttons.lua:1656: ?()
   Neuron\Neuron-Buttons.lua:1757: MACRO_OnEvent()
   Neuron\Neuron-Buttons.lua:3377:
      Neuron\Neuron-Buttons.lua:3377

**Comment by brittyazel** [comment]
I think this is fixed with dd9885317f6e858e0b1a7cb88d2b6c15ebdb915a
