### ISSUE TITLE
modifiers in macros and "Function" key bindings

### ISSUE THREAD

**Issue by spamwax** [brittyazel/Neuron#146]
I used the button edit feature and added the following macro

```lua
#showtooltip
/cast [mod:ctrl,@player] [@cursor] Sigil of Flame
```
Assigning key bindings such as `1` or `F` to the button makes it work as expected with and without holding down the `ctrl` key. However, the button fails to work with some specific key bindings such as `F5` or `F6`!!!

I do not have any other addon that uses these bindings and I have checked all the bindings in the "Key Bindings" interface to make sure they are not used.

The reason I am reporting this as a bug is that the same macro and keybindings (`F5`) work in other action bar addons.

**Comment by brittyazel** [comment]
Are you 100% sure you don't have anything bound to f5 or f6? Someone reported the same issue a couple months ago and it was that they were bound to some obscure thing in blizzard keybinding window

**Comment by spamwax** [comment]
> Someone reported the same issue a couple months ago and it was that they were bound to some obscure thing in blizzard keybinding window

You were right, though it was not a blizzard binding but a *disabled* addon that had `ctrl-F5` key binding. I am not sure how a disabled addon can still affect the bindings, had to enable all addons to figure this out 💃
