### ISSUE TITLE
Macros from the Blizz UI stay in place when changing specs

### ISSUE THREAD

**Issue by N4s7y** [brittyazel/Neuron#148]
When I drag a macro from the Blizzard UI into a Neuron button it stays there even when I change spec (with Multi-spec enabled for the bar). This overrides any other spell for that second spec.

The reason I want to use the Blizzard macro UI is that I want to use the macros created by the TalentMacros addon. This saves a lot of time on alts. And I want the macros in different places for each spec so this behaviour gets in the way.

In the meantime I've created some macros in Neuron like this:

#showtooltip
/cast [talent:1/1] Eye of the Tiger
/cast [talent:1/2] Chi Wave
/cast [talent:1/3] Chi Burst

Unfortunately the don't show an icon or tooltip if I picked the passive which looks weird. Is there a way to do that?

**Comment by brittyazel** [comment]
you can always specify #showtooltip "blah", I'm not sure about differential #showtooltips though depending on the spell. If you chose a passive it makes sense that it goes blank though, as that's not a spell and the actionbar doesn't know what to do with it

I'll look into why blizzard macros are acting funny though

**Comment by N4s7y** [comment]
It does make sense I suppose. I liked that I could instantly see what talent I picked. But if anyone's interested I found this way to display a standard icon, that's greyed out when a passive is selected:

#showtooltip [talent:1/2] Chi Wave; Chi Burst

**Comment by brittyazel** [comment]
I can't replicate this anymore, please reopen if this is still an issue
