### ISSUE TITLE
Fix the global vs character saved variable infrastructure

### ISSUE THREAD

**Issue by brittyazel** [brittyazel/Neuron#15]
The global vs character saved variable system is a bit in shambles, and pretty hacky. I had to employ a hack fix to the menu and bag bars today just to get their size/position to be saved per character rather than per account.

I'd like to have a more elegant way of going about this.

**Comment by brittyazel** [comment]
Status bars are also per account rather than per character. This is wrong. I think bag bars might also fall victim to this.

**Comment by teh-fixerer** [comment]
pet bars also fall into this category.  
I manually edit the .toc files for the modules,
SavedVariables: 
SavedVariablesPerCharacter: 

is that what you are doing?

**Comment by brittyazel** [comment]
As a hack I'm actually editing the register bar data call, rather than the .toc. this really isn't the ideal solution though, but it is just a patch

**Comment by brittyazel** [comment]
Ok this is fixed, but the outcome is not idea. For our the for Neuron modules I removed the distinction between CDB and GDB and now all settings for these are stored in a *DB value which is saved per character. There are no more global saves for these bars. In the future, there really should not be too many variables saved globally aside from profiles.
