### ISSUE TITLE
LUA error after logging in - Attempt to index a nil value

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#153]
Started happening after I reset my profile and had put my hunter's usual buttons back on the bar, I now get this every time I log in on that toon.

14x Neuron\Neuron-Buttons.lua:1345: attempt to index a nil value
Neuron\Neuron-Buttons.lua:1345: in function `MACRO_UpdateUsableSpell'
Neuron\Neuron-Buttons.lua:1453: in function `MACRO_UpdateButton'
Neuron\Neuron-Buttons.lua:1328: in function `MACRO_UpdateAll'
Neuron\Neuron-Buttons.lua:1661: in function `?'
Neuron\Neuron-Buttons.lua:1757: in function `MACRO_OnEvent'
Neuron\Neuron-Buttons.lua:3377: in function <Neuron\Neuron-Buttons.lua:3377>

Locals:
InCombatSkipped

**Comment by brittyazel** [comment]
Yeah you're not the only person getting this on their hunters. Is it only your hunter?

I tried to replicate this on my hunter and I just can't

**Comment by raysmith59** [comment]
Long story (problem went away, eventually figured it out), when I first dragged the Command Pet (Primal Rage in this case) spell out of my spellbook to the action bar it actually put it in as /cast Primal Rage(), that's what was causing the problem (I duplicated by just manually creating the button with Primal Rage).  At some point I noticed that the button wasn't working so I removed it and re-created it, that time it did create it correctly as /cast Command Pet() and the problem went away at that point.

So, the issue could be when a pet spell is put on a non-pet action bar button or related to the Command Pet replaceable spell (not sure how else to describe that).

To quickly test that I tried creating a button with just /cast Growl() at which point I got non-stop LUA errors:

258x integer overflow attempting to store 3238005337
[C]: in function `GetSpellInfo'
Neuron\Neuron-Buttons.lua:1345: in function `MACRO_UpdateUsableSpell'
Neuron\Neuron-Buttons.lua:1453: in function `MACRO_UpdateButton'
Neuron\Neuron-Buttons.lua:1490: in function `MACRO_OnUpdate'
Neuron\Neuron-Buttons.lua:3391: in function <Neuron\Neuron-Buttons.lua:3391>

Locals:
(*temporary) = 3238005337

Hopefully that helps and let me know if you need anything else.

**Comment by raysmith59** [comment]
Tried on my warlock, put the demon dps ability on the action bar and it worked immediately but after a reboot I got another bunch of integer errors but not the original one reported above.  Not sure what to conclude from that but hopefully gives you enough info to test/duplicate.  This integer issue should probably be reported separately, let me know if you need that done.

Message: integer overflow attempting to store 3238006404
Time: Sat Aug  4 18:42:09 2018
Count: 1
Stack: integer overflow attempting to store 3238006404
Interface\AddOns\Neuron\Neuron-Buttons.lua:1328: in function `MACRO_UpdateAll'
Interface\AddOns\Neuron\Neuron-Buttons.lua:1661: in function `?'
Interface\AddOns\Neuron\Neuron-Buttons.lua:1757: in function `MACRO_OnEvent'
Interface\AddOns\Neuron\Neuron-Buttons.lua:3385: in function <Interface\AddOns\Neuron\Neuron-Buttons.lua:3385>

Locals: self = <table> {
 MACRO_SetItemIcon = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:863
 MACRO_UpdateUsableSpell = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1340
 MACRO_ACTIVE_TALENT_GROUP_CHANGED = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1629
 modules = <table> {
 }
 AutoCastStop = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:351
 SecureHook = <function> defined @Interface\AddOns\Chatter\Libs\AceHook-3.0\AceHook-3.0.lua:336
 ButtonProfileUpdate = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:3674
 SetType = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:3357
 AutoUpdateMacro = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:3604
 MACRO_SPELL_UPDATE_CHARGES = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1736
 MACRO_SPELL_UPDATE_USABLE = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1665
 SetDefaults = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:3337
 SetTimer = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:615
 IsEnabled = <function> defined @Interface\AddOns\Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 MACRO_PlaceBlizzMacro = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1830
 MACRO_ITEM_LOCK_CHANGED = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1687
 RegisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 MACRO_PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1653
 MACRO_UpdateButton = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1433
 UNIT_SPELLCAST_SENT = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:288
 hooks = <table> {
 }
 MACRO_UNIT_SPELLCAST_FAILED = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1588
 AutoCastStart = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:338
 GetDefaults = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:3352
 MACRO_StopGlow = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1010
 SetEnabledState = <function> defined @Interface\AddOns\Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @Interface\AddOns\Chatter\Libs\AceHook-3.0\AceHook-3.0.lua:274
 ACTION_UpdateUsable = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1404
 MACRO_PlaceBattlePet = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:2070
 MACRO_SetSpellIcon = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:804
 OnEnable = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:235
 MACRO_ACTIONBAR_HIDEGRID = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1696
 ACTION_UpdateState = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1076
 MACRO_PET_JOURNAL_LIST_UPDATE = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1660
 OnInitialize = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:170
 NewModule = <function> defined @Interface\AddOns\Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 MACRO_COMPANION_UPDATE = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1543
 MACRO_StartGlow = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:998
 MACRO_UNIT_ENTERED_VEHICLE = <function> defined @Interface\AddOns\Neuron\Neuron-Buttons.lua:1588
 GetName = <function> defined @

**Comment by brittyazel** [comment]
fixed, thanks @veyh !
