### ISSUE TITLE
Neuron buttons layout vs bartender4 layout

### ISSUE THREAD

**Issue by jomo666** [brittyazel/Neuron#154]
When trying replace my bartender setup with Neuron, I found an issue:

Bartender4 allows let say 2-row setup where the 2nd row (e.g. in 12-buttons, the buttons 7-12) are **ABOVE** the 1st row (buttons 1-6). When trying to achieve the same 2-row setup in Neuron the buttons 7-12 are BELLOW buttons 1-6.

Maybe not very frequently used feature, but for me  absolutely crucial because I'm using an gaming keyboard with such button configuration. (see https://www.extremegamingdevices.com/detailed_specification_pages/a4tech_x7g100_gaming_keyboard_pro.html)

I attached some images  with some visual explanation:

![neuron](https://user-images.githubusercontent.com/719714/43779187-07a0ff94-9a58-11e8-82f1-b3c2659148d1.jpg)
![bt4](https://user-images.githubusercontent.com/719714/43779196-12146ede-9a58-11e8-9d0e-f8d9b132d4a5.jpg)
![keyboard](https://user-images.githubusercontent.com/719714/43779219-1b8561c6-9a58-11e8-9694-216774770f5b.jpg)

**Comment by brittyazel** [comment]
Have you tried rebinding the keys to match the number layout on your keypad? The literal button number (not the keybind) is somewhat arbitrary, and the keybinds (the numbers that'll you see on the button) were just the defaults. They can be changed to be whatever you like by shift + left clicking the minimap button. Hence, you can easily bind the bottom row to be 1-6 and the top to be 7-=

**Comment by jomo666** [comment]
True, this solves the problem, thank you.

And I didn't tried it because the confusing part is the "naming". :) When the feature is called as: **Toggle keybinding mode** (this is showed when I hoower on the minimap button)- it evokes the presumption that it WILL change the keybindings, but in the reality it just changes it only for the addon.

So yes - it could be marked as "closed", but (maybe) would be more understandable for beginners follow the "default" thinking logic. :) 

Thank you - closing.

**Comment by brittyazel** [comment]
I'll keep that in mind. Thanks for the feedback!

**Comment by jomo666** [comment]
Reopening the issue, because when remapping as you recommending, then I must press for example `7` (instead of `1`) when some extra-actionbar comes up. (Like in the Darkmoon-faire games and such).

**Comment by brittyazel** [comment]
Hrm, I'm not quite following, can you post a screenshot?

**Comment by brittyazel** [comment]
BTW, do you have the vehicle state anabked for your main bar? That might help in this situation

**Comment by jomo666** [comment]
The issue is simple: The keybindings and the layout are two different things. Binding the key: `7` to button `1` isn't the right thing and therefore the simple things get messed up.  Here is a screenshot from the binding:

![wow1](https://user-images.githubusercontent.com/719714/43987024-cae9f41e-9d1a-11e8-9a0d-d42c7207c549.jpeg)

The easy step-by-step how to reproduce:

1. install only the neuron addon, and clean-up the WTF.
2. make the two-row layout where the buttons 7-12 are ABOVE the buttons 1-6. Because the addon doesn't allows such layout, you recommended solve this by keybindings. Make sure that you done this step.
3. go to darkmoon faire race
4. take some vehicle
5. you will get

![wowscrnshot_081118_032421](https://user-images.githubusercontent.com/719714/43986934-c3920d7e-9d19-11e8-8876-274b110841e8.jpg)

So, as you can see, the neuron got the buttons 1-4 (from the race vehicle) and showing them as buttons 7-10. Moreover, to use the ability `1` now I need press the button `7` (of course, because we are only binded the key `7` to button `1` - see the 1st screenshot in this comment.

Simply, too many different and strange actions should be done to achieve the simple two row layout as the bartender allows by the "vertical grow upward" feature. (see the second screenshot in this issue-page). 

This is clearly a bug and definitely should be addressed in similar way as other bar addons does, e.g. allowing  define a layout independently from the actual keybindings.

Unfortunately i know only `bash` and `perl` so can't help with `lua`.

**Comment by brittyazel** [comment]
For the time being, you can create two 6 button bars and have them stacked on top of eachother. You can then enable the vehicle state solely on the bottom row of 6. This isn't as convenient as a toggle that allows you to change which direction the bars grow, but the desired effect is the same

**Comment by jomo666** [comment]
Thank you.  If want - close the issue - I not playing wow now. :)

Good luck with the addon - it is promising. :)
