### ISSUE TITLE
Extra action bar - Blizzard button still visible

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#157]
Hi,
The Blizzard extra action button is still present even when the Neuron's one is up.
![image](https://user-images.githubusercontent.com/20615278/43914264-b3ca5e54-9c07-11e8-8324-62494bd97bbd.png)
(Barrel button on this picture)

**Comment by brittyazel** [comment]
It shouldn't be... Does this happen even through a /reload? If you just made the button it's possible that it takes a /reload before the blizzard disablement happens

**Comment by SirLagardere** [comment]
I've delete and re-create this button, and yes I have tried a reload and a logout/login.
Same behaviour.
I haven't reset my profile yet, but I can try if you want.

**Comment by brittyazel** [comment]
Are other toons with different profiles also having this issue? Did it just start? Unless blizzard changed something on Tuesday, this shouldn't be happening

**Comment by SirLagardere** [comment]
I must try with another toon, and it's not a new thing, I'm just lazy some times ^^.
Both zone button and extra button were in this state (neuron & Blizzard), then you fixe the zone button with the alpha trick (if I'm right) but the extra button stay in "double" mode.

**Comment by SirLagardere** [comment]
Ok, since the game latest version and your latest version, the Blizzard Extra button is now hidden... Don't know exactly what has changed but I close the issue

**Comment by SirLagardere** [comment]
Just a last comment. I finally found the culprit, it was MoveAnything (I must have touched the Blizz Extra Frame and now on it was always visible).
I noticed in the Neuron-extra that you didn't use "ExtraActionButton1:Hide()" but, If I follow, you move the Extra button away. Is that intended ? (I'm very curious I know ^^)

**Comment by brittyazel** [comment]
Yeah for some reason hiding it wasn't doing the job because it kept coming back each time a new extra button event would hapoen, so I took a hint from Bartender and moved it off the screen avoiding these issues lol
