### ISSUE TITLE
Actionbar 1 reset to default with version 0.9.32

### ISSUE THREAD

**Issue by BillWiegert** [brittyazel/Neuron#163]
I updated to version 0.9.32 and actionbar1 was completely reset to default. No macro data or keybinds. Reverting to 0.9.31d restored actionbar1 with all my settings and macros.

**Comment by brittyazel** [comment]
Well shit. Interestingly the same thing happened to me when I was implementing this yesterday, but I reverted the changes that, at least for me, caused the issue. So now I have no idea what is causing it

**Comment by brittyazel** [comment]
Are you still experiencing the issue?

**Comment by Xurkon** [comment]
I had to delete it and reinstall because the only way I could get buttons to work was by manually editing and putting the macro for it in, for literally everything.

**Comment by BillWiegert** [comment]
Tried updating to the new version, same issue. All action bars set to default

**Comment by brittyazel** [comment]
Ugh. I truely don't know what could have caused that, I don't experience any if these things.

**Comment by Fizgig1973** [comment]
Had the same issue here. But after redoing the bar everything is saving again like normal.

**Comment by brittyazel** [comment]
I'm reverting back to where we were in 0.9.31e until I can figure out what is going on. Hopefully that won't causing anyone even more grief.

**Comment by brittyazel** [comment]
Is this still an issue with 0.9.33a?
