### ISSUE TITLE
Button flash with 0.9.32

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#165]
Did you do something that changed how buttons react? For instance spells were flashing(dimed to indicate i cant use them but flash still visiable) when they werent avaiable to use at all,someimes they didnt flash when expected,.... basicly they are behaving differently then they used too.

**Comment by brittyazel** [comment]
I did change stuff to try to optimize. I'm reverting those changes until I can more thoroughly test

**Comment by brittyazel** [comment]
Can you check with 0.9.32c and see if this fixes your issue?

**Comment by Addonman** [comment]
Late night here but ill try in the morning

**Comment by Fizgig1973** [comment]
Might be the same issue I am experiencing. Procc'd abilities are no longer flashing to indicate the proc (Omen of Clarity on druid).

Using 0.932c

**Comment by brittyazel** [comment]
Is this still an issue with 0.9.33a?

**Comment by Addonman** [comment]
Confirmed it fixed.
