### ISSUE TITLE
Can't drag the pet utility flyout to the action bar from the spell book anymore

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#166]
As of the most recent build my flyout buttons were greyed out so I removed it and tried to re-add the flyout, thinking something had changed, but I can't drag it to the action bar anymore.

**Comment by brittyazel** [comment]
@AlexFolland This might be on you man. We might need some sort of condition in the RegisterCorrectEvents call for flyouts. Can you look into this for me?

**Comment by AlexFolland** [comment]
Yeah, I'll look into it after work.

**Comment by brittyazel** [comment]
Is this still an issue with 0.9.33a?

**Comment by raysmith59** [comment]
Nope, back to normal now.  Closing.
