### ISSUE TITLE
Blood Boil Tooltip

### ISSUE THREAD

**Issue by TruthNZ** [brittyazel/Neuron#167]
As of today's update, my Blood Boil spell (Blood DK) is showing the pet battle for it's tooltip, not the spell.
I tried adding #showtooltip, but result is the same.

**Comment by TruthNZ** [comment]
And it's trying to summon the pet, instead of cast the spell too ...

**Comment by brittyazel** [comment]
Is this still an issue with 0.9.33a?

**Comment by TruthNZ** [comment]
No, fixed - thank you!
