### ISSUE TITLE
LUA error when dragging a mount from my collections on top of an existing mount on my action bar

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#168]
I'll add the LUA error the next time I try it, just wanted to get this in.

**Comment by brittyazel** [comment]
Is this still an issue?

**Comment by raysmith59** [comment]
Not with 33a, it's back to its usual kinda works but the bar stays in the wrong state situation.  I've been ignoring those for the past while, figured I'd wait until BfA was out and stable before bringing those back.  :)

Closing it.
