### ISSUE TITLE
Issue with Masque: Cirque

### ISSUE THREAD

**Issue by patandpet** [brittyazel/Neuron#17]
Masque: Cirque is an Addon which provides circular buttonskins for Masque.
(https://www.curseforge.com/wow/addons/masque-cirque)

First i thought Neuron would have problems with circular Buttonskins in general but it seems that it only struggles with Cirque. I tried two different circular Skins (Masque: Serenity, Masque: Gears) and both worked perfectly with Neuron. I also use Cirque to masque buttons from Bartender4 and Weakauras2 which works perfectly but Neuron somehow can not handel the corners... (see the screenshot)
 
Thank you in advance and keep up your great work man!

![masque cirque_neuron vs bartender](https://user-images.githubusercontent.com/33988975/33234891-1ad3634c-d22e-11e7-918f-958b67d5ee34.jpg)

**Comment by patandpet** [comment]
i noticed that it only creates those black corners by adding any ability in the bar/grid...

**Comment by brittyazel** [comment]
I'll look into it. I'm not really sure how Masque theming works 100%, but I'll see if it's something on our end that we can fix

**Comment by brittyazel** [comment]
I don't think this a Neuron issue. I'd go upstream with the request
