### ISSUE TITLE
Bug with name of macro thats put on bar

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#173]
If you drag a macro into bar it doesnt show name of macro so you have to go into button configuration and there if you put re input name of macro and save it is shown on bar.

**Comment by brittyazel** [comment]
A macro as in a blizzard macro? Or just a normal ability?

**Comment by Addonman** [comment]
I got addon called Easydisenchant and made macro having only /disenchant  (to call addon window not to disenchant item ) in it ,but when i put macro on bar it didnt pull name of macro on button. So i had to go into button configuration (mind  it already got name there) and reenter name there  and then it would show up on button.

**Comment by AlexFolland** [comment]
You have Neuron and you made a default Blizzard macro in the default Blizzard macro interface?  Why not just edit a Neuron button instead?

**Comment by Addonman** [comment]
I guess its a habit. Also i guess i am not sure if i edit Neuron button where is Neuron storing those macros and how to get them on another char.

**Comment by Addonman** [comment]
Also when i tried it i didnt get passed selecting icon without bug. On top of that when i tried moving macro from 1 button to next text was goe so i needed to go into options again.

**Comment by brittyazel** [comment]
Is this still an issue? If it is please repopen

**Comment by brittyazel** [comment]
When I fixed it I meant I fixed the bug with saving the names on initial drag, I didn't however retroactively add names to all buttons that were effected by this bug :-\ Newly dragged abilities should get button names

**Comment by Addonman** [comment]
Now i think you are talking about differnt bug i reported  in  i think #226. Neuron is macro based, right ? But you have 2 type of macros -one which is fixed is spellbook to bars and names wrorks fine there. Other is "real" macros from /macro window which are working half way. What i mean half way is that if you edit (right click ) you can see name in macro name box but not on button on bars. But if i edit 1 macro/button name for just 1 letter i get names on bars on all macros.
