### ISSUE TITLE
[@playername] modifier doesn't seem to work anymore.

### ISSUE THREAD

**Issue by 40P3** [brittyazel/Neuron#174]
There was an update I just reallized -dunno which one precisely but recent one- where the below macro stopped working:
/cast [@charactername,mod:ctrl]racial ability name;[@character2name,mod:ctrl]racial ability name

Basically whenever I used the same class, e.g. demon hunter, but on ally and horde side everything can be identical, except the racial ability. And targetting myself (@charactername) was working and I could use exactly identical buttons/macros.

Now I cannot, it stopped working. Can you check please?

**Comment by brittyazel** [comment]
Does this work in the built in macro system? I want to know if it's a Neuron specific issue or a blizzard macro specific issue

**Comment by 40P3** [comment]
Thanks for the response Britty,

Well the strange thing is that in default macro it didn't work for me. People suggested on Wow UI forum to try this out, because no racial identifyer condition exists in the game currently (never were :)).

However I clearly remember that it was working with Neuron. :)

E.g. for WoW macro:
Two DK is troll (Drakhul) and crimsondeath (huma).

```
#showtooltip
/cleartarget [nocombat,dead]
/cast [@drakhul,mod:ctrl]Berserking;[@crimsondeath,mod:ctrl]Every Man for Himself;[nocombat,noharm]Acherus Deathcharger;[spec:1]Heart Strike;[spec:2]Obliterate;[spec:3]Scourge Strike
```
If it doesn't work now and should require extensive macro coding what can you suggest how to use one interface profile for two different race (so all buttons are the same but racial is different? I couldn't identify racials from spellbook, couldn't find the way, like how talents can be identifyied/found if you have them activated.

Any help appreciated.
Big fan since years and great to talk with such a high profile Addon maker! 💃 
H0PE

**Comment by raysmith59** [comment]
Best I can recall you've never been able to macro to a character name directly, best you can do is @focus and set your macro target as the focus.  I spent a lot of time trying to get this working mid-Legion and completely failed so if Neuron ever did have some sort of built-in function (in theory on the back end it could set the focus target to your @name target, target focus, cast the spell, then remove the focus) it hasn't worked for a while.  I also doubt Blizzard would allow an add-on to do this... although it'd be fantastic if it was possible to do.

**Comment by AlexFolland** [comment]
No, macros that cast on specific characters have worked since TBC at least.  Only in recent years have there been problems with them.  I used them all the time in MoP and WoD, with Ion.

**Comment by brittyazel** [comment]
If he only intends to Target himself with the macro as well I believe you can use the @player modifier

**Comment by brittyazel** [comment]
I'm going to close this because it seems like this is not a Neuron issue

**Comment by 40P3** [comment]
Yeah I was wondering if the macro part of neuron could help me do some advanced macros. @player didn't help, @charactername seems working, except a little glitch with the icon showing, but I guess I can live with that and try to figure it out. E.g.:

```
#showtooltip [@Crimsonsmash-Darkmoon Faire,mod:shift] Gift of the Naaru;[@Soulscraper-The Venture Co,mod:shift] Arcane Torrent;[@mouseover,harm,nodead,mod:shift][harm,mod:alt]Justicar's Vengeance;[nocombat,noharm]Bleakhoof Ruinstrider;[@mouseover,harm,nodead,nomod][ ]Judgment
/cleartarget [dead]
/use  [@Crimsonsmash,mod:shift] Gift of the Naaru
/use  [@Soulscraper,mod:shift] Arcane Torrent
/cast [@mouseover,harm,nodead,mod:shift][harm,mod:alt]Justicar's Vengeance;[nocombat,noharm]Bleakhoof Ruinstrider;[@mouseover,harm,nodead,nomod][ ]Judgment
```
