### ISSUE TITLE
Extra Action Button Keybind Not Persistent

### ISSUE THREAD

**Issue by HolteUnderscore** [brittyazel/Neuron#175]
The extra action button is not retaining it's keybinding between sessions, I'm having to reset it every logon.

**Comment by brittyazel** [comment]
Did it used to save between sessions and now it isn't?

**Comment by HolteUnderscore** [comment]
Yes, it used to save.  It's hard to say exactly when it stopped as there have been a few new builds lately (appreciate all the hard work you are putting in btw)

**Comment by brittyazel** [comment]
Fixed, will be in the next release

**Comment by TruthNZ** [comment]
Got this happening again in 1.0.7f

**Comment by brittyazel** [comment]
I do not have this issue. What exactly is happening? For me the keybind is working just as it should upon login

**Comment by TruthNZ** [comment]
Keybind is still listed correct as what I'd set it before logout - but isn't actually working upon login. I have to rebind it for it to register the keypress, for that session.

**Comment by TruthNZ** [comment]
Ps. I'm testing in the Waycrest area with the Alliance shotgun ability.
But I noticed it in raid as well (e.g. picking up Barrels on Jaina).

Not helped by the fact you can't bind anything to it without having an active extra action ability for the bar/button to show.

**Comment by brittyazel** [comment]
Yes, you can key-bind it without an active extra action ability. Do you have some strange visibility toggles on it? Maybe try deleting your extra action button and re-making it just for good measure. It seems there's some wonkyness with yours

**Comment by TruthNZ** [comment]
Ok - will try and update this evening (at work now).

**Comment by TruthNZ** [comment]
Sorry, didn't make it home for a couple of days.

However, this is weird:
On my warlock, it's working fine. Keybind is working, ready to go, cooldown shows.
_But_ the extra action button stays visible when I leave the area.

On my DK, I can't see the button at all (even in config or bind mode), unless I have a valid extra action button ability (e.g. be in Warcrest area, pick up a barrel on Jaina). It shows the keybind I put in before relogging - but isn't correctly activating on keypress (but works fine on mouse-click).

Same PC, same account, same server, same other addons (with same settings - except weak auras).

I haven't yet deleted and re-recreated them on either toon (got caught up in guild drama). I'll update here when I get the chance (irl also very busy too).
But I was thinking on this - is it possible to through in some sort of start up check that checks for incorrect configuration on these, and attempts to correct it? Suggestion based on the number of issues I see raised around it - and the fact I've clearly got some old/incorrect config on one or more toons.

**Comment by brittyazel** [comment]
I do have a startup checker that does this as best as it can, but I try to limit it as much as possible. I get super stressed out whenever I have to touch a persons database, as one wrong semicolon can ruin 1000+ peoples profiles :-/

The issue here preventing me from performance a fix is that I don't know which configuration option or flag is the culprit

**Comment by TruthNZ** [comment]
Before I delete and re-create them (didn't get time last night), is there something I could capture to help you?

**Comment by brittyazel** [comment]
If you want to send me your Neuron.lua file in your WTF folder, that'd be awesome. I can parse through it and see what's going on

**Comment by brittyazel** [comment]
And your toons name that has the issue, so I can find it in the table

**Comment by TruthNZ** [comment]
After deleting and recreating I'm getting the same behaviour on my toons.
Unfortunately its the issue where the keybind doesn't work after relogging.
(But does disappear correctly when you no longer have an extra action ability).

I emailed you my Neuron.lua file before I deleted and recreated.

**Comment by brittyazel** [comment]
I believe I fixed this with my latest changes.
