### ISSUE TITLE
Druid Travel Form not working

### ISSUE THREAD

**Issue by wowregistering** [brittyazel/Neuron#178]
Dragging 'Travel Form' from the spell book to a bar to auto create a macro does not cast.
Setting '/cast Travel Form' as the action bar button does not cast.
Dragging or creating a macro for 'Stag Form' does cast.

I know this was working before, I am not sure what caused it to stop working today for me, I tried disabling all other addons, and reloading my interface multiple times but the issue persists.

Logging in and out resolves the issue temporarily.

**Comment by brittyazel** [comment]
It's a bug with the game actually, if you make the macro "/cast Travel Form (shapeshift)" it should work consistently. I don't know why the game is being weird

**Comment by wowregistering** [comment]
Thank you very much for the reply. :)

I really enjoy this addon for my Druid so thank you for all of the effort!

**Comment by ylixir** [comment]
this doesn't seem to be an issue anymore, i just dragged travel and mount form onto a bar and they both worked in 10.0.2
