### ISSUE TITLE
Further to Issue #175 - Extra Action Button

### ISSUE THREAD

**Issue by HolteUnderscore** [brittyazel/Neuron#179]
Not sure if this has been mentioned before, I can't find a previous issue mentioning it but, it is not possible to set the keybind for the extra action button unless there is actually an action on it.  Shift clicking on the minimap button allows the setting of all other keys but, that one doesn't show up.

**Comment by brittyazel** [comment]
Yeah I've been trying to figure this one out for a LONG time. I cannot for the life of me figure out why it is hidden. I don't think it's Neuron code that's doing it, it may be something in game

**Comment by brittyazel** [comment]
Fixed

**Comment by TruthNZ** [comment]
Got this happening again in 1.0.7f
