### ISSUE TITLE
Multiple XP bars sync up

### ISSUE THREAD

**Issue by Fyrhtu** [brittyazel/Neuron#18]
When creating multiple XP bars (for the purpose of tracking XP and Artifact XP side-by-side,) they will occasionally upon gaining Artifact or Character XP (haven't yet identified anything more specific that causes the sync) sync so that both bars display the same type of XP, where they remain until such time as they both sync the other type, and back and forth as you play.

**Comment by brittyazel** [comment]
I think I might have assigned global assignments to the bar state, rather than per-bar assignments

**Comment by brittyazel** [comment]
Still working on this one. Will be fixed soon

**Comment by brittyazel** [comment]
Ok I think I fixed this one. Do you mind testing it for me? You should be able to drag and drop just the Neuron-Status.lua file into your Neuron folder and /reload to get the new fix

**Comment by brittyazel** [comment]
Nvm I can verify that it is fixed. Will be released with the next version tonight
