### ISSUE TITLE
Multi condition buttons got cd text "reset".

### ISSUE THREAD

**Issue by 40P3** [brittyazel/Neuron#180]
Somehow I constantly see duplicate cd text. Using neuron and omnicc.
I turn off neuron's cd text. Then I use my skills (all my buttons are with mod:ctrl/alt/shift conditions on all my toons) and then the neuron CD reappears under onmnicc's cd text. Made some screenshots but lol I can't see them in the screenshot folder I'll add some later.

**Comment by brittyazel** [comment]
can you post the screenshots here please

**Comment by 40P3** [comment]
Hi,
This evening I'll update this case and attach some screenshots from my PC.
I've also checked the forum for OmniCC and the devs over there are struggling with the issue as well unfortunately. Wanted to give you example ticket link for their github unfortunately it seems they closed and removed such tickets. :(

I'll get back to you this evening with examples.

**Comment by 40P3** [comment]
One more addition, you can see when normal mode there is a CD visible (I believe it's neurons). When I hit ALT to show the other spell, then you can see double CD (when omniCD shows the proper CD on the button. Talking about the second from right of course.
![multicdneuron02](https://user-images.githubusercontent.com/20872247/47873516-ba86b200-de11-11e8-8a5d-b7f46602f7bf.jpg)

**Comment by brittyazel** [comment]
Ok, thanks for the screenshots. I'll download OmniCC at some point soon and play around with it. I've never heard about it before prior to people bringing up this issue.

**Comment by 40P3** [comment]
You're a rockstar! Thanks!
And really really thank you for this bar addon. Something like this I was missing badly for years, since the other addons like Macaroon is "out of order" for a while. :)

**Comment by 40P3** [comment]
This is still a weird issue for me, and the annoyance is when there is a cooldown on the button and I shift/alt/ctrl the bar out, I still see the cooldown and not sure which spell has the cooldown. Bah! :D

**Comment by brittyazel** [comment]
Is this still an issue?

**Comment by 40P3** [comment]
Not anymore, and duplicate tickets. Thank you!
