### ISSUE TITLE
Neuron latest version

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#185]
When i entered game all my buttons are gone:number of buttons are gone to 0 and i cant even add 1 button to bar.

Error occured in: Global
Count: 15
Message: ..\AddOns\Neuron\Neuron-Flyouts.lua line 237:
   attempt to index upvalue 'anchorUpdater' (a nil value)
Debug:
   ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:612:
      ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:574
   (tail call): ?
   Neuron\Neuron-Flyouts.lua:237: ?()
   ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AddOns\AchieveIt\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\AchieveIt\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Error occured in: Global
Count: 1
Message: ..\AddOns\Neuron\Neuron-GUI.lua line 498:
   attempt to concatenate field 'objCount' (a nil value)
Debug:
   ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:612:
      ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:574
   [C]: ?
   Neuron\Neuron-GUI.lua:498: UpdateBarGUI()
   Neuron\Neuron-Bars.lua:1390: OnClick()
   Neuron\Neuron-Bars.lua:1786:
      Neuron\Neuron-Bars.lua:178

Error occured in: Global
Count: 3
Message: ..\AddOns\Neuron\Neuron-Buttons.lua line 3071:
   attempt to index field 'statedata' (a nil value)
Debug:
   ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:612:
      ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:574
   (tail call): ?
   Neuron\Neuron-Buttons.lua:3071: LoadData()
   Neuron\Neuron-Buttons.lua:2762: CreateNewObject()
   Neuron\Neuron-Bars.lua:213: CreateBarsAndButtons()
   Neuron\Neuron-Bars.lua:127:
      Neuron\Neuron-Bars.lua:95
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:529: InitializeAddon()
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:644:
      ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:636

Error occured in: Global
Count: 114
Message: ..\AddOns\Neuron\Neuron-Flyouts.lua line 159:
   attempt to index upvalue 'ANCHOR_LOGIN_Updater' (a nil value)
Debug:
   ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:612:
      ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:574
   (tail call): ?
   Neuron\Neuron-Flyouts.lua:159: ?()
   ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AddOns\AchieveIt\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\AchieveIt\libs\AceEvent-3.0\AceEvent-3.0.lua:119

Error occured in: Global
Count: 1
Message: ..\AddOns\Neuron\Neuron-Flyouts.lua line 185:
   attempt to index upvalue 'anchorUpdater' (a nil value)
Debug:
   ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:612:
      ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:574
   (tail call): ?
   Neuron\Neuron-Flyouts.lua:185: ?()
   ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AddOns\AchieveIt\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\AchieveIt\libs\AceEvent-3.0\AceEvent-3.0.lua:119

Error occured in: Global
Count: 1
Message: ..\AddOns\Neuron\Neuron-Buttons.lua line 2909:
   attempt to index field 'data' (a nil value)
Debug:
   ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:612:
      ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:574
   (tail call): ?
   Neuron\Neuron-Buttons.lua:2909: SetData()
   Neuron\Neuron-Bars.lua:1095: LoadObjects()
   Neuron\Neuron-Bars.lua:3277: Load()
   Neuron\Neuron.lua:299:
      Neuron\Neuron.lua:257
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:651:
      ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: ?
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:489: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:1194:
      ..\FrameXML\UIParent.lua:1090
   [C]: ?

Error occured in: Global
Count: 1
Message: ..\AddOns\Neuron\Neuron-Flyouts.lua line 68:
   attempt to index global 'NeuronTooltipScan' (a nil value)
Debug:
   ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:612:
      ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:574
   (tail call): ?
   Neuron\Neuron-Flyouts.lua:68:
      Neuron\Neuron-Flyouts.lua:64
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:529: InitializeAddon()
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:644:
      ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:636

Error occured in: Global
Count: 1
Message: ..\AddOns\Neuron\Utilities/DB-Fixer.lua line 67:
   attempt to index field '?' (a nil value)
Debug:
   ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:612:
      ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:574
   (tail call): ?
   Neuron\Utilities/DB-Fixer.lua:67: DBFixer()
   Neuron\Neuron.lua:206:
      Neuron\Neuron.lua:181
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:529: InitializeAddon()
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:644:
      ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:636

**Comment by HolteUnderscore** [comment]
I'm getting these errors:

Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
Time: Mon Oct 29 12:48:10 2018
Count: 1
Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
(tail call): ?
Interface\FrameXML\SecureHandlers.lua:359: in function <Interface\FrameXML\SecureHandlers.lua:354>
(tail call): ?
[C]: in function `Hide'
Interface\AddOns\Neuron\Neuron-Buttons.lua:3124: in function `SetObjectVisibility'
Interface\AddOns\Neuron\Neuron-Bars.lua:1100: in function `LoadObjects'
Interface\AddOns\Neuron\Neuron-Bars.lua:3277: in function `Load'
Interface\AddOns\Neuron\Neuron.lua:299: in function <Interface\AddOns\Neuron\Neuron.lua:257>
[C]: ?
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: (*temporary) = <function> defined =[C]:-1
==================================================================
Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
Time: Mon Oct 29 12:48:10 2018
Count: 1
Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: func = <function> defined @Interface\AddOns\Neuron\Neuron.lua:257
type = <function> defined =[C]:-1
xpcall = <function> defined =[C]:-1
errorhandler = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:61
================================================================
Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
Time: Mon Oct 29 12:48:10 2018
Count: 4
Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)

Locals:

**Comment by HolteUnderscore** [comment]
No clue why that text has gone so large :P

**Comment by brittyazel** [comment]
I cannot replicate this. The error doesn't seem possible with how addons load/work. I'm quite confused. Do you have flyouts with companion pets on them?

**Comment by brittyazel** [comment]
> I'm getting these errors:
> 
> Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "	if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
> Time: Mon Oct 29 12:48:10 2018
> Count: 1
> Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "	if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
> (tail call): ?
> Interface\FrameXML\SecureHandlers.lua:359: in function <Interface\FrameXML\SecureHandlers.lua:354>
> (tail call): ?
> [C]: in function `Hide' Interface\AddOns\Neuron\Neuron-Buttons.lua:3124: in function `SetObjectVisibility'
> Interface\AddOns\Neuron\Neuron-Bars.lua:1100: in function `LoadObjects' Interface\AddOns\Neuron\Neuron-Bars.lua:3277: in function `Load'
> Interface\AddOns\Neuron\Neuron.lua:299: in function <Interface\AddOns\Neuron\Neuron.lua:257>
> [C]: ?
> ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
> ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon' ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605> [C]: in function `LoadAddOn'
> Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn' Interface\FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
> Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>
> 
> Locals: (*temporary) = defined =[C]:-1
> 
> ==================================================================
> 
> Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "	if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
> Time: Mon Oct 29 12:48:10 2018
> Count: 1
> Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "	if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
> ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
> ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon' ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605> [C]: in function `LoadAddOn'
> Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn' Interface\FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
> Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>
> 
> Locals: func = defined @interface\AddOns\Neuron\Neuron.lua:257
> type = defined =[C]:-1
> xpcall = defined =[C]:-1
> errorhandler = defined @interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:61
> 
> ================================================================
> 
> Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "	if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
> Time: Mon Oct 29 12:48:10 2018
> Count: 4
> Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "	if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
> 
> Locals:

This seems like a different bug, please report it on its own

**Comment by brittyazel** [comment]
So it seems like the database migration failed on your profile or something. And the lack of bars and buttons is the fact that 90% of Neuron isn't loaded, hence no functionality. Now's the question of why the DB migration failed....

**Comment by brittyazel** [comment]
I have hardened the database migration a good bit. Are you still getting these errors?

**Comment by Addonman** [comment]
Latest c version.
Still bars empty of buttons. I can readd them but they are still a mess like not all of them are there and order is messed up. Getting 2 errors downbelow. And i dont have companion pets on flyout.
Error occured in: Global
Count: 1
Message: ..\AddOns\Neuron\Neuron-Bars.lua line 1669:
   attempt to get length of field 'name' (a nil value)
Debug:
   ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:612:
      ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:574
   (tail call): ?
   Neuron\Neuron-Bars.lua:1669: LoadData()
   Neuron\Neuron-Bars.lua:1785: CreateBar()
   Neuron\Neuron-Bars.lua:1808: CreateNewBar()
   Neuron\Neuron-Bars.lua:206: CreateBarsAndButtons()
   Neuron\Neuron-Bars.lua:127:
      Neuron\Neuron-Bars.lua:95
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:529: InitializeAddon()
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:644:
      ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:636

Error occured in: Global
Count: 16
Message: ..\FrameXML\RestrictedExecution.lua line 431:
   Call failed: [string "						if (not self:GetParent():GetAttribute..."] line 2:
   bad argument #1 to 'gmatch' (string expected, got nil)
Debug:
   ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:612:
      ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:574
   [C]: ?
   [C]: ?
   ..\FrameXML\RestrictedExecution.lua:431:
      ..\FrameXML\RestrictedExecution.lua:420
   (tail call): ?
   (tail call): ?
   ..\FrameXML\SecureHandlers.lua:359:
      ..\FrameXML\SecureHandlers.lua:354
   (tail call): ?
   [C]: Hide()
   Neuron\Neuron-Buttons.lua:3085: SetObjectVisibility()
   Neuron\Neuron-Bars.lua:1099: LoadObjects()
   Neuron\Neuron-Bars.lua:1999: AddObjectsToBar()
   Neuron\Neuron-GUI.lua:987:
      Neuron\Neuron-GUI.lua:987

**Comment by brittyazel** [comment]
Ok give me 2 hours and I'll have a version for you to test

**Comment by brittyazel** [comment]
Is this every character? Do you have any alt characters that you can try a fresh profile on? I want to know if it's systemic or a database issue

**Comment by Addonman** [comment]
https://www.wowinterface.com/downloads/fileinfo.php?id=10636#comments
Basicaly Radoznali on wowinterface is me commenting.
3 chars tested --1 seems ok ,but 2 totaly messed up.You can sort of make it back and forth  with adding and subsctracting buttons,but not sure if would trust that everything is back.On top of it i have bar thats totaly empty but stays on top of my screen(probably totaly messed up vehicle bar)

**Comment by brittyazel** [comment]
I have no idea how it's saying "name" is a nil value.

Can you past this into line 1669 in Neuron-Bars.lua instead of what is there:
`	if (not bar.data.name) then`

let me know if this fixes the bug for you

**Comment by Addonman** [comment]
Not sure if it going to help,but i copy profile from my ally shammy .Had to do complete logout (not just /reload ) and then bars where back.I did same fix on my dh(my 3rd char ) and it also fixed him.

**Comment by brittyazel** [comment]
Wait so you just copied the profile from a different toon and it works now? So something DID get messed up in the database copy. I have no idea what it could have been, I through I accounted for everything pretty thoroughly. When you first updated was the game running when you did it? The new database pulls defaults from a new file, and without a full client restart it wasn't pulling that file. Maybe that caused the database copy to screw up

**Comment by Addonman** [comment]
I never update addons with game on since i know from exp that can be a mess so i do it before i go into game.I think only update that during a game running is Tsm but its only because there aplication need to be on or it gives some warning.

I did what you asked and changed line and i dont see any errors on my fixed char.

**Comment by brittyazel** [comment]
Ok cool. I still don't know what caused this bug, so I'm afraid to close it.
