### ISSUE TITLE
Keybinds Gone and Can't Reset Them

### ISSUE THREAD

**Issue by HolteUnderscore** [brittyazel/Neuron#186]
Get the following error when trying to set them:

Message: Interface\AddOns\Neuron\Neuron-KeyBinder.lua:235: attempt to index field 'hotKeys' (a nil value)
Time: Mon Oct 29 12:56:17 2018
Count: 3
Stack: Interface\AddOns\Neuron\Neuron-KeyBinder.lua:235: attempt to index field 'hotKeys' (a nil value)

Locals:

**Comment by HolteUnderscore** [comment]
It gets better, or should I say much worse - I went back to the old version and now my bar setup has completely gone and restored to default....

**Comment by brittyazel** [comment]
Yeah with the new database you can't go backwards. I haven't seen that error and I've been trying to recreate it. I'll add some code to work around it for the time being
