### ISSUE TITLE
New Version Issue -  Separate Issue Raised As Requested

### ISSUE THREAD

**Issue by HolteUnderscore** [brittyazel/Neuron#187]
I'm getting these errors:

Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "	if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
Time: Mon Oct 29 12:48:10 2018
Count: 1
Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "	if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
(tail call): ?
Interface\FrameXML\SecureHandlers.lua:359: in function <Interface\FrameXML\SecureHandlers.lua:354>
(tail call): ?
[C]: in function Hide' Interface\AddOns\Neuron\Neuron-Buttons.lua:3124: in function SetObjectVisibility'
Interface\AddOns\Neuron\Neuron-Bars.lua:1100: in function LoadObjects' Interface\AddOns\Neuron\Neuron-Bars.lua:3277: in function Load'
Interface\AddOns\Neuron\Neuron.lua:299: in function <Interface\AddOns\Neuron\Neuron.lua:257>
[C]: ?
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function EnableAddon' ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605> [C]: in function LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function UIParentLoadAddOn' Interface\FrameXML\UIParent.lua:565: in function TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: (*temporary) = defined =[C]:-1

==================================================================

Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "	if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
Time: Mon Oct 29 12:48:10 2018
Count: 1
Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "	if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function EnableAddon' ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605> [C]: in function LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function UIParentLoadAddOn' Interface\FrameXML\UIParent.lua:565: in function TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: func = defined @interface\AddOns\Neuron\Neuron.lua:257
type = defined =[C]:-1
xpcall = defined =[C]:-1
errorhandler = defined @interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:61

================================================================

Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "	if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
Time: Mon Oct 29 12:48:10 2018
Count: 4
Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "	if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)

Locals:

**Comment by brittyazel** [comment]
You are getting these even with the 0.9.36c release?

**Comment by brittyazel** [comment]
I can't for the life of me replicate this. What is the class, race, level, etc. I need to track this down

**Comment by brittyazel** [comment]
Is this on every toon? Or only on a singe toon?

**Comment by HolteUnderscore** [comment]
I've not tried yet with 0.9.36c - let me try now.  I'll let you know asap.

**Comment by brittyazel** [comment]
Ok, I actually released a 0.9.36d version an hour ago. I'd try that one, it has 1 more bug fix in it

**Comment by HolteUnderscore** [comment]
I'll get that now, with the "c" version I'm still getting the error - it appears on char login, not doing any action and the keybindings are gone again.

**Comment by HolteUnderscore** [comment]
Still getting an error but, some line numbers have changed slightly:

Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
Time: Mon Oct 29 22:50:26 2018
Count: 1
Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
(tail call): ?
Interface\FrameXML\SecureHandlers.lua:359: in function <Interface\FrameXML\SecureHandlers.lua:354>
(tail call): ?
[C]: in function `Hide'
Interface\AddOns\Neuron\Neuron-Buttons.lua:3085: in function `SetObjectVisibility'
Interface\AddOns\Neuron\Neuron-Bars.lua:1099: in function `LoadObjects'
Interface\AddOns\Neuron\Neuron-Bars.lua:3254: in function `Load'
Interface\AddOns\Neuron\Neuron.lua:289: in function <Interface\AddOns\Neuron\Neuron.lua:247>
[C]: ?
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: (*temporary) = <function> defined =[C]:-1

===============================================================

Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
Time: Mon Oct 29 22:50:26 2018
Count: 1
Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: func = <function> defined @Interface\AddOns\Neuron\Neuron.lua:247
type = <function> defined =[C]:-1
xpcall = <function> defined =[C]:-1
errorhandler = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:61

================================================================

Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
Time: Mon Oct 29 22:50:26 2018
Count: 8
Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)

Locals:

**Comment by HolteUnderscore** [comment]
Still getting the old keybind error when trying to reset them:

Message: Interface\AddOns\Neuron\Neuron-KeyBinder.lua:236: attempt to index field 'hotKeys' (a nil value)
Time: Mon Oct 29 22:52:52 2018
Count: 1
Stack: Interface\AddOns\Neuron\Neuron-KeyBinder.lua:236: attempt to index field 'hotKeys' (a nil value)

Locals:

**Comment by HolteUnderscore** [comment]
Here's a weird one, I logout the character and then log it back in - no errors and I can set the keybinds.

Most odd.

**Comment by HolteUnderscore** [comment]
Final test, I completely closed out of Wow - started it up again and logged in the char, no errors and can set keybinds.  Seems like a one off thing when it does the DB conversion the first time.

**Comment by HolteUnderscore** [comment]
Just to be thorough, tried another char (120 blood elf male affliction warlock) - got only one error on logon:

Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
Time: Mon Oct 29 23:00:37 2018
Count: 9
Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)
[C]: ?
Interface\FrameXML\RestrictedExecution.lua:431: in function <Interface\FrameXML\RestrictedExecution.lua:420>
(tail call): ?
(tail call): ?
Interface\FrameXML\SecureHandlers.lua:359: in function <Interface\FrameXML\SecureHandlers.lua:354>
(tail call): ?
[C]: in function `Hide'
Interface\AddOns\Neuron\Neuron-Buttons.lua:3085: in function `SetObjectVisibility'
Interface\AddOns\Neuron\Neuron-Bars.lua:1099: in function `LoadObjects'
Interface\AddOns\Neuron\Neuron-Bars.lua:3254: in function `Load'
Interface\AddOns\Neuron\Neuron.lua:289: in function <Interface\AddOns\Neuron\Neuron.lua:247>
[C]: ?
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: (*temporary) = "Call failed: [string "						if (not self:GetParent():GetAttribute..."]:2: bad argument #1 to 'gmatch' (string expected, got nil)"

**Comment by brittyazel** [comment]
Strange.... So you're good then?

*edit: Did that other character's error go away when relogging?

**Comment by HolteUnderscore** [comment]
This char can't set keybinds on initial logon either but, can when logged off and back on again.

The initial error went away on relog, yes

**Comment by brittyazel** [comment]
Yeah I know about the needing to /reload before keybdinds can be set. That's unfortunately a side effect, and I need to look further into why. For now the first reload fixes it for good.

**Comment by HolteUnderscore** [comment]
You can close this issue, I'll just do the double logon for all my chars.

**Comment by brittyazel** [comment]
Ok, sorry about that. Do you mind trying refreshing the profile on some alt that you don't play? I'm curious as to if this error shows up on a clean profile or if it's a migration thing

**Comment by HolteUnderscore** [comment]
I think I have an alt that doesn't have a profile, failing that I'll create a new char and let you know.

**Comment by HolteUnderscore** [comment]
No errors on a fresh char/profile.

**Comment by brittyazel** [comment]
Well that's good at least. I'll just chalk it up to conversion-pains.

**Comment by raysmith59** [comment]
I'm also getting this issue, just to confirm that it isn't just HolteUnderscore.  Seems to just be a one-time thing for each toon for me as well.
