### ISSUE TITLE
Action Blocked Error

### ISSUE THREAD

**Issue by 40P3** [brittyazel/Neuron#190]
Now that I'm on the roll:

45x [ADDON_ACTION_BLOCKED] AddOn 'Neuron' tried to call the protected function 'OverrideActionBarButton6:Show()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `Show'
FrameXML\ActionButton.lua:364: in function <FrameXML\ActionButton.lua:338>
[C]: in function `ActionButton_Update'
FrameXML\ActionButton.lua:720: in function `ActionButton_OnEvent'
FrameXML\ActionButton.lua:207: in function <FrameXML\ActionButton.lua:204>

Locals:
InCombatSkipped

**Comment by brittyazel** [comment]
Yep this is one of many taint warnings. It's on my list to get to the bottom of these, I just cannot for the life of me figure out where this error stems from
