### ISSUE TITLE
Zone Action Bar

### ISSUE THREAD

**Issue by mgkurt** [brittyazel/Neuron#192]
Not sure if this was happening in legion or before in BFA, There is no recorded issues about this or maybe i am doing something wrong. 

I was doing the quest Opening The Way (https://www.wowhead.com/quest=52511/opening-the-way#comments) to reach Fate's End for Jaina Questline, and the "Zone Action Bar 1" did not appear so i had to disable the addon to complete the quest. Then i went to Dreanor and Argus and i still had the problem. 
I tried to fix with edit/config options but couldn't find anything to fix the issue. tried to re-create the bar and now the Create New Bar option doesnt have the Zone Action Bar, and couldn't find the option to turn the standart Action Bar to Zone Action Bar.

Is this a Bug due to a patch or something or did i do something wrong ?

**Comment by brittyazel** [comment]
The zone action bar is its own bar type, so you don't turn a regular action bar into a zone action bar. Also you can only have 1 zone action bar, so the option to make one won't show as long as one already exists. So if it's not showing the option to make a zone action bar, you might have one hidden somewhere :-/

Also, are you sure this is a zone ability button that shows or the extra action button that shows? I haven't leveled an alliance toon yet, so I don't know  the quest you're referring to, but I haven't had any issues with quests on my horde toon bringing up the extra bar and zone ability bars.

Do you have an extra action bar/button?

**Comment by mgkurt** [comment]
Thanks for the reply!

From what i understand from your answer that the Zone Action Bar and Extra Action Bar (which shows up on some specific quests or events ) are not the same thing. I though they were same since they are pretty similar.

But even though they are different, I don't have an Extra Action Bar in the bar list and tit doesn't show up when they needed to. But the Zone Action Bar showed up again in the list after a relog, though it doesn't show up in that specific zones like Argus or Dreanor.  

So basicly i don't have that shining action bar that shows up in specific events or zones, and couldn't fix with the options of the addon.

**Comment by brittyazel** [comment]
So you don't have an extra action bar? And you can't make a new one? It's the extra action bar that shows up during the quests and such, so it's super important that you specifically have that button. The zone action button just does things like the Garrison ability and follower summoning. 

Is it possible you do have an extra action bar hidden behind something and you just removed the button from it? You should see the option to make an extra action button if you truely don't have one, which makes me suspect that it's hidden somewhere

**Comment by mgkurt** [comment]
As i remember i never had a bar in the list named "Extra Action Bar".  I had "Zone Action Bar 1" which is why i though they are the same thing. And even though i all the hide options are off, the bar doesn't show up. 

![untitled1](https://user-images.githubusercontent.com/44157440/48227649-ed055180-e3b3-11e8-988f-95bb5057adb4.png)
![untitled2](https://user-images.githubusercontent.com/44157440/48227650-ed055180-e3b3-11e8-8c1b-907130c9da8a.png)

The addon is pretty good. i use a lot of lua scripts in macros and 1k character is literally an improvement for me. But it is annoying to turn off the addon just for some quests and areas.

**Comment by brittyazel** [comment]
You don't have to disable it. You need to create an extra action bar. Please click Create new Bar --> Extra Action Bar --> and add a single button to it. This solve all your problems.

**Comment by mgkurt** [comment]
yeah but there is no Extra Action Bar option
![untitled](https://user-images.githubusercontent.com/44157440/48229587-93078a80-e3b9-11e8-93fe-409014edac80.png)

**Comment by brittyazel** [comment]
Ok I'll look into that. That shouldn't be the case if your truly don't have an extra actio button

**Comment by brittyazel** [comment]
While I work on this, for the time being can you type "/neuron create extrabar" into the chat box. This should make a new blank extra bar that you can add a button to. I think the bar name is "extrabar", but if that's not it then just type "/neuron create" and it should give you a list of what the bar types are that you can create

**Comment by brittyazel** [comment]
Alright this is fixed in the latest release I just pushed. It should be available in a few hours once it gets approved. Closing this issue as you can now create a new Extra Action Bar (and make sure to add 1 button to it). You can also run the command "/neuron create extrabar" now (if you're antsy) and can get the same result.
