### ISSUE TITLE
Keybinds stoping working after few min

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#195]
Did you cahnge something for keybind in bild from like 1-2 days ago?For some reason i started losing keybind after few min of play.Mostly when i get on flight or there is some intro in game i lose all my keyboard keybinds.At first i thought it was my keyboard thinhg but now i think its Neuron fault.Why ?Well i can easily wright 123 in chat but keybind for 123 dont react at the moment i lose keybinds.(when i say lose i means i press buton but nothing happens.)If i relog they come back.

**Comment by brittyazel** [comment]
I did nothing to how the keybind code works, and the keybind code works perfectly fine for me and for others I have talked to. Can you go to a fresh toon and see if there error is true for you on a fresh profile?
