### ISSUE TITLE
Macro Auto Write error

### ISSUE THREAD

**Issue by LBBlue** [brittyazel/Neuron#196]
I found an error in line 3333 of Neuron-Buttons.lua.

Where it says elseif (bar.data.mouseOverCast and NeuronDB.mouseOverMod == "NONE" )

should be corrected to DB.mouseOverMod. This fixes an issue auto creating mouse over macros for spells and placing them on the bar

**Comment by brittyazel** [comment]
Excellent catch, I feel silly for missing that with my big DB port. I'll have this fixed in the next minor release out probably on Monday. (I'm on vacation atm)

**Comment by LBBlue** [comment]
It happens to everyone. that's what making it open source is for right? Enjoy the rest of your vacation and thanks for your work!

**Comment by brittyazel** [comment]
Haha thanks. I'll just keep this open till I can make the change. I don't wanna forget about it
