### ISSUE TITLE
Enhancement Suggestion - Profile Export / Import to/from text file.

### ISSUE THREAD

**Issue by HolteUnderscore** [brittyazel/Neuron#198]
I mentioned this before in an old issue and you thought it was a great idea, so I didn't want it to get lost as a consequence of the old issue being closed.

**Comment by brittyazel** [comment]
Cool, thanks for keeping it on my mind. I think I can make this happen easier now. Now that we're using 100% Ace3-DB I think we can use the Ace3-Serializer for this. I'll have to do research on how exactly to make this happen. I've never do anything like this before, so this will be a 1st

**Comment by ylixir** [comment]
i believe the experimental section of the settings now has an option for importing/exporting profiles via copy paste.

does this feature do what you need it to @HolteUnderscore ?
