### ISSUE TITLE
Dont work /petautocasttoggle on Enslave Demons ( Eredar Chaosbringer)

### ISSUE THREAD

**Issue by noisex** [brittyazel/Neuron#20]
it`s dont work from chat slash command too, but work with standart Blizzard pet-panel. 
thanks.

**Comment by brittyazel** [comment]
Is this a warlock thing? Sorry can you explain it to me more, I've never played a warlock before so I better want to understand the issue

**Comment by noisex** [comment]
all pets ( hunt or warlock) can disable autocast with slashcommad "petautocasttoggle spellname", "petautocastoff spellname" or right-click on spell from pet-bars... good. 
in the Arcway warlocks usually use "Enslave Demon" to control Eredar Chaosbringer, who have autocast "Brand of the Legion" on random party players... not good, all want this buff on self.
this spell is present on pet-bar, but him not managed by slashcommands and your cannot disable it from the "Neuron-petbar", but if your try it on Blizzard pet-bar you will succeed. Blizzard dit not use slashcommand as you on right-clicks ( "/petautocasttoggle "..spell)... it`s not good.

- normal pets work fine through scommand and rclick on pet-bar ( Blizzard / Neuron)

- controlled pet dont work through scommand ( Blizzard / Neuron)
- controlled pet dont work through rclick on pet-bar (  Neuron)
- controlled pet work fine through rclick on pet-bar ( Blizzard) - how do they do it? :)

i`m so sorry, it's not English, but a set of familiar words to me. thanks.

**Comment by brittyazel** [comment]
Which language locale do you play in? And if not the English client, does your issue happen with the English client?

**Comment by noisex** [comment]
forget it
