### ISSUE TITLE
8.1 errors

### ISSUE THREAD

**Issue by NuubEitrigg** [brittyazel/Neuron#203]
I rolled back to 0.9.37c and the issue is not present

2352x Neuron\Objects/BAR.lua:117: attempt to index global 'self' (a nil value)
Neuron\Objects/BAR.lua:117: in function `controlOnUpdate'
Neuron\Neuron-0.9.38.lua:659: in function `?'
...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0-8.lua:90: in function <...\ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:87>

Locals:
elapsed = 0.017000
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
  = NeuronBarHandler5 {
 }
}
(for control) = NeuronActionBar5 {
 0 = <userdata>
 index = 5
 elapsed = 0
 class = "bar"
 UnwrapScript = <function> defined @FrameXML\SecureHandlers.lua:788
 dragged = false
 createMsg = "1Action Button"
 shift = <table> {
 }
 messagebg = NeuronActionBar5MessageBG {
 }
 objPrefix = "NeuronActionButton"
 objMax = 250
 text = NeuronActionBar5Text {
 }
 message = NeuronActionBar5Message {
 }
 driver = NeuronBarDriver5 {
 }
 barType = "ActionBar"
 alt = <table> {
 }
 toggleframe = NeuronActionBar5 {
 }
 right = 345.000061
 data = <table> {
 }
 handler = NeuronBarHandler5 {
 }
 objTable = <table> {
 }
 barDB = <table> {
 }
 microAdjust = false
 alphaUp = "Off"
 posSet = true
 objTemplate = <table> {
 }
 left = 1.000020
 WrapScript = <function> defined @FrameXML\SecureHandlers.lua:782
 bottom = 724.500000
 objCount = 40
 Execute = <function> defined @FrameXML\SecureHandlers.lua:777
 alpha = 1
 objType = "Action Button"
 top = 939.499939
 barLabel = "Action Bar"
 vis = <table> {
 }
 selected = false
 SetFrameRef = <function> defined @FrameXML\SecureHandlers.lua:793
 keybind = NeuronActionBar5KeyBind {
 }
}
k = NeuronActionBar5 {
 0 = <userdata>
 index = 5
 elapsed = 0
 class = "bar"
 UnwrapScript = <function> defined @FrameXML\SecureHandlers.lua:788
 dragged = false
 createMsg = "1Action Button"
 shift = <table> {
 }
 messagebg = NeuronActionBar5MessageBG {
 }
 objPrefix = "NeuronActionButton"
 objMax = 250
 text = NeuronActionBar5Text {
 }
 message = NeuronActionBar5Message {
 }
 driver = NeuronBarDriver5 {
 }
 barType = "ActionBar"
 alt = <table> {
 }
 toggleframe = NeuronActionBar5 {
 }
 right = 345.000061
 data = <table> {
 }
 handler = NeuronBarHandler5 {
 }
 objTable = <table> {
 }
 barDB = <table> {
 }
 microAdjust = false
 alphaUp = "Off"
 posSet = true
 objTemplate = <table> {
 }
 left = 1.000020
 WrapScript = <function> defined @FrameXML\SecureHandlers.lua:782
 bottom = 724.500000
 objCount = 40
 Execute = <function> defined @FrameXML\SecureHandlers.lua:777
 alpha = 1
 objType = "Action Button"
 top = 939.499939
 barLabel = "Action Bar"
 vis = <table> {
 }
 selected = false
 SetFrameRef = <function> defined @FrameXML\SecureHandlers.lua:793
 keybind = NeuronActionBar5KeyBind {
 }
}
v = NeuronBarHandler5 {
 0 = <userdata>
 WrapScript = <function> defined @FrameXML\SecureHandlers.lua:782
 SetFrameRef = <function> defined @FrameXML\SecureHandlers.lua:793
 Execute = <function> defined @FrameXML\SecureHandlers.lua:777
 fadeSpeed = 0.250000
 UnwrapScript = <function> defined @FrameXML\SecureHandlers.lua:788
 bar = NeuronActionBar5 {
 }
}
(*temporary) = nil
(*temporary) = NeuronActionBar5 {
 0 = <userdata>
 index = 5
 elapsed = 0
 class = "bar"
 UnwrapScript = <function> defined @FrameXML\SecureHandlers.lua:788
 dragged = false
 createMsg = "1Action Button"
 shift = <table> {
 }
 messagebg = NeuronActionBar5MessageBG {
 }
 objPrefix = "NeuronActionButton"
 objMax = 250
 text = NeuronActionBar5Text {
 }
 message = NeuronActionBar5Message {
 }
 driver = NeuronBarDriver5 {
 }
 barType = "ActionBar"
 alt = <table> {
 }
 toggleframe = NeuronActionBar5 {
 }
 right = 345.000061
 data = <table> {
 }
 handler = NeuronBarHandler5 {
 }
 objTable = <table> {
 }
 barDB = <table> {
 }
 microAdjust = false
 alphaUp = "Off"
 posSet = true
 objTemplate = <table> {
 }
 left = 1.000020
 WrapScript = <function> defined @FrameXML\SecureHandlers.lua:782
 bottom = 724.500000
 objCount = 40
 Execute = <function> defined @FrameXML\SecureHandlers.lua:777
 alpha = 1
 objType = "Action Button"
 top = 939.499939
 barLabel = "Action Bar"
 vis = <table> {
 }
 selected = false
 SetFrameRef = <function> defined @FrameXML\SecureHandlers.lua:793
 keybind = NeuronActionBar5KeyBind {
 }
}
(*temporary) = false
(*temporary) = nil
(*temporary) = "attempt to index global 'self' (a nil value)"

**Comment by brittyazel** [comment]
Sorry about that. This is now fixed, a new build is being spun up as I type this. Check for it in a few min

**Comment by NuubEitrigg** [comment]
Thanks for the heads up!

For reference, I'm used_to_be_nice_guy on Reddit, and Nuub-Eitrigg in your
neuron community.
