### ISSUE TITLE
Create new bar

### ISSUE THREAD

**Issue by Dasaneux** [brittyazel/Neuron#204]
When I click create new bar and the select which type of bar, it just goes back to the main gui window without creating the new bar.

**Comment by Dasaneux** [comment]
Is this background to the gui intended?
![wow 1](https://user-images.githubusercontent.com/44789225/49839551-acaa5080-fe03-11e8-9cc1-932f41228d5c.jpg)

**Comment by brittyazel** [comment]
This is a bug. I'll have this fixed later on tonight, for now just use the /neuron create command to make bars

**Comment by Dasaneux** [comment]
Thanks for all the quick replies.

Um, I forgot how to change an XP bar to show azurite :P
