### ISSUE TITLE
Vehicle bar showing wrong icon.

### ISSUE THREAD

**Issue by Dasaneux** [brittyazel/Neuron#206]
When in a vehicle the main action bar is showing my mount icon in button 1 and some of my other ability icons farther along the bar.

![wow 2](https://user-images.githubusercontent.com/44789225/49847187-f9515400-fe22-11e8-983b-5e528650941b.jpg)

![wow 3](https://user-images.githubusercontent.com/44789225/49847204-0bcb8d80-fe23-11e8-90a8-dcb945198b04.jpg)

**Comment by brittyazel** [comment]
hrm that's an odd one. I was just doing a vehicle quest earlier with no problem

**Comment by Dasaneux** [comment]
I have this macro on my first action button ..

#Showtooltip
/cast [talent:3/3][nochanneling] Fel Barrage; Consume Magic

Could that be the issue?

**Comment by Dasaneux** [comment]
Seems to be all fixed.

Thanks again for all the hard work you've put into Neuron :)

**Comment by brittyazel** [comment]
Thank you!
