### ISSUE TITLE
LUA error when hearthed to Boralus - New version

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#207]
I didn't get an error logging into the toon but I hearthed back to Boralus and got it when I arrived at the inn.  I haven't touched any of my buttons since updating.  It was my mage so he has portal and teleport flyouts.

4x ...aceNeuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:963: attempt to call method 'SetObjectLoc' (a nil value)
...aceNeuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:963: in function <...aceNeuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:963>

Locals:
self = NeuronFlyoutBar1 {
 0 = <userdata>
 WrapScript = <function> defined @FrameXML\SecureHandlers.lua:782
 index = 1
 keybind = NeuronFlyoutBar1KeyBind {
 }
 Execute = <function> defined @FrameXML\SecureHandlers.lua:777
 text = NeuronFlyoutBar1Text {
 }
 data = <table> {
 }
 handler = NeuronFlyoutHandler1 {
 }
 UnwrapScript = <function> defined @FrameXML\SecureHandlers.lua:788
 objCount = 13
 SetFrameRef = <function> defined @FrameXML\SecureHandlers.lua:793
 objPrefix = "NeuronFlyoutButton"
 elapsed = 0
 messagebg = NeuronFlyoutBar1MessageBG {
 }
 class = "bar"
 message = NeuronFlyoutBar1Message {
 }
}
(*temporary) = nil
(*temporary) = NeuronFlyoutBar1 {
 0 = <userdata>
 WrapScript = <function> defined @FrameXML\SecureHandlers.lua:782
 index = 1
 keybind = NeuronFlyoutBar1KeyBind {
 }
 Execute = <function> defined @FrameXML\SecureHandlers.lua:777
 text = NeuronFlyoutBar1Text {
 }
 data = <table> {
 }
 handler = NeuronFlyoutHandler1 {
 }
 UnwrapScript = <function> defined @FrameXML\SecureHandlers.lua:788
 objCount = 13
 SetFrameRef = <function> defined @FrameXML\SecureHandlers.lua:793
 objPrefix = "NeuronFlyoutButton"
 elapsed = 0
 messagebg = NeuronFlyoutBar1MessageBG {
 }
 class = "bar"
 message = NeuronFlyoutBar1Message {
 }
}
(*temporary) = "attempt to call method 'SetObjectLoc' (a nil value)"

**Comment by brittyazel** [comment]
This should be fixed! I'll spin up a new minor release now with the fix
