### ISSUE TITLE
#show doesn't work anymore

### ISSUE THREAD

**Issue by pottervogel** [brittyazel/Neuron#208]

**Comment by brittyazel** [comment]
Can you please describe the issue further for me? I'm not sure what #show does

**Comment by pottervogel** [comment]
the tooltip works fine, but the icon is always the ?

**Comment by pottervogel** [comment]
#show item or ability shows the item or ability icon an the buttons
#showtooltip does the same + tooltip when you hover a button 

now the tooltip is show by both commands, but the icon is always the questionmark

**Comment by brittyazel** [comment]
Cool fixed. Thanks for the report

**Comment by brittyazel** [comment]
New version out, can you confirm for me if 0.9.38d fixes this issue for you?

**Comment by pottervogel** [comment]
wow this was fast! i'll test it  now, give me a second ...

**Comment by pottervogel** [comment]
YES! Awesome, thank you, everythings fine again. 👍

**Comment by brittyazel** [comment]
Great! Glad I could figure out what was causing it lol

**Comment by pottervogel** [comment]
U are my hero :-)

**Comment by brittyazel** [comment]
Hah you can return the favor by doing the German translation *wink wink nudge nudge*
