### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by pottervogel** [brittyazel/Neuron#209]
In the  Bar_Configuration_FAQ is mentioned that you can leave it with ESC, but that is not the case anymore - will this come again or should i leave it from the translation?

**Comment by AlexFolland** [comment]
Woah, this functionality is gone?  This is exclusively how I've cleared focus when editing Macaroon/Ion/Neuron macros in the past.  I hope it's present when I come back to WoW.

**Comment by brittyazel** [comment]
Oh uh, I'm not exactly sure. I can check it out.

Also @pottervogel, are you doing the translations through curseforge it straight from the file? You should do them through the GUI in curseforge

**Comment by pottervogel** [comment]
yep, this i use

**Comment by brittyazel** [comment]
I fixed this. Put the pitchforks down ;-)

**Comment by AlexFolland** [comment]
Haha, nice uncommenting fix.  Thanks, duderino!

**Comment by brittyazel** [comment]
The best kind of fix is the one where I don't have to type anything :-)

**Comment by pottervogel** [comment]
I made a mistake with the localization, did the slash commands config and edit by mistake. Changed it again now - I will check the rest of them in the evening and do more translating  the next couple days. (hehe, now i know why the macro conditions of blizzard item categories have been translatet  :D )

**Comment by pottervogel** [comment]
maybe the slash commands (not the descriptions) should not be localized at all and get out of the localization file?

**Comment by brittyazel** [comment]
That seems reasonable. Ill look at it soon and see what is up. I appologise for my ignorance when it comes to localization, I unfortunately only speak English so I can never test this kind of stuff

**Comment by pottervogel** [comment]
heyho, I'm terribly sorry but got so much family stuff to do til after the holidays - but I'm on it! promised! 

what are you talking about? you speak english and lua and probably a lot more programming languages^^

wish you happy x-mas!

**Comment by brittyazel** [comment]
No sweat! Take your time. Family always comes first
