### ISSUE TITLE
#showtooltips not displaying

### ISSUE THREAD

**Issue by wowregistering** [brittyazel/Neuron#210]
When attempting to put #showtooltip spellname on a button the icon does not change, these are buttons that were working before the most recent update.

An example would be this macro I use on my rogue

#showtooltip Symbols of Death
/cast Shuriken Storm

I use this so I can double or triple up on grouping of my cooldowns to make them easier to see at a quick glance, on top of that there is no reason to be able to see the actual icon for Shuriken Storm.

Using the above macro on Blizzard action bars still works as intended and displays the icon for Symbols of Death.

Edit to add more info:

When using an ability that triggers my global cooldown it does not display on the above macro despite still showing the icon for Shuriken Storm, an ability that is on the global.

When using Symbols of Death the macro will display the cooldown for Symbols of Death while still showing the Icon for Shuriken Storm

When mousing over the button that the macro is on it will display the tooltip for Symbols of Death but still shows the icon for Shuriken Storm

A short clip of the issue
https://gfycat.com/ImmediateSplendidFlyingfish
The Left icon, bound to 'T', is the one using the macro I put earlier in this post and the Right icon, bound to 'Y', is just a normal Shuriken Storm button.

**Comment by wowregistering** [comment]
Below are some of the errors I was getting with only Neuron enabled.

Message: Interface\AddOns\Neuron\Objects/BAR.lua:1035: attempt to perform arithmetic on local 'padH' (a nil value)
Time: Wed Dec 12 22:08:19 2018
Count: 2
Stack: Interface\AddOns\Neuron\Objects/BAR.lua:1035: attempt to perform arithmetic on local 'padH' (a nil value)
Interface\AddOns\Neuron\Objects/BAR.lua:1035: in function `SetObjectLoc'
...ace\AddOns\Neuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:383: in function `updateFlyoutBars'
...ace\AddOns\Neuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:544: in function `Flyout_UpdateButtons'
...ace\AddOns\Neuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:702: in function `UpdateFlyout'
Interface\AddOns\Neuron\Objects/ACTIONBUTTON.lua:1428: in function `?'
Interface\AddOns\Neuron\Objects/ACTIONBUTTON.lua:1543: in function `MACRO_OnEvent'
Interface\AddOns\Neuron\Objects/ACTIONBUTTON.lua:462: in function <Interface\AddOns\Neuron\Objects/ACTIONBUTTON.lua:462>

Locals: self = NeuronFlyoutBar2 {
 0 = <userdata>
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:782
 index = 2
 keybind = NeuronFlyoutBar2KeyBind {
 }
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
 text = NeuronFlyoutBar2Text {
 }
 data = <table> {
 }
 handler = NeuronFlyoutHandler2 {
 }
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
 objCount = 8
 SetFrameRef = <function> defined @Interface\FrameXML\SecureHandlers.lua:793
 objPrefix = "NeuronFlyoutButton"
 elapsed = 0
 messagebg = NeuronFlyoutBar2MessageBG {
 }
 class = "bar"
 message = NeuronFlyoutBar2Message {
 }
}
width = 43
height = 43
num = 0
count = 8
origCol = 8
x = nil
y = nil
object = NeuronFlyoutButton10 {
 macroname = NeuronFlyoutButton10MacroName {
 }
 shine5 = NeuronFlyoutButton10Shine5 {
 }
 flyoutborder = NeuronFlyoutButton10FlyoutBorder {
 }
 elapsed = 0
 class = "flyout"
 flyoutright = NeuronFlyoutButton10FlyoutRight {
 }
 shine12 = NeuronFlyoutButton10Shine12 {
 }
 shine11 = NeuronFlyoutButton10Shine11 {
 }
 shine16 = NeuronFlyoutButton10Shine16 {
 }
 stored = false
 iconframebackground = NeuronFlyoutButton10IconFrameBackGround {
 }
 objTIndex = 10
 gloss = NeuronFlyoutButton10Gloss {
 }
 count = NeuronFlyoutButton10Count {
 }
 hitbox = NeuronFlyoutButton10HitBox {
 }
 SetData = <function> defined @Interface\AddOns\Neuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:743
 bar = NeuronFlyoutBar2 {
 }
 flyoutbordershadow = NeuronFlyoutButton10FlyoutBorderShadow {
 }
 auracolor1 = <table> {
 }
 iconframeaurawatchtimer = NeuronFlyoutButton10IconFrameAuraWatchTimer {
 }
 shine13 = NeuronFlyoutButton10Shine13 {
 }
 data = <table> {
 }
 cdcolor2 = <table> {
 }
 objType = "FLYOUTBUTTON"
 debuffcolor = <table> {
 }
 normaltexture = NeuronFlyoutButton10NormalTexture {
 }
 shine3 = NeuronFlyoutButton10Shine3 {
 }
 macroparse = " 
/cast [nobtn:2] Path of the Bloodmaul() 
"
 rangecolor = <table> {
 }
 shine8 = NeuronFlyoutButton10Shine8 {
 }
 shine6 = NeuronFlyoutButton10Shine6 {
 }
 FlyoutArrow = NeuronFlyoutButton10FlyoutArrow {
 }
 hotkey = NeuronFlyoutButton10HotKey {
 }
 FlyoutBorderShadow = NeuronFlyoutButton10FlyoutBorderShadow {
 }
 shine15 = NeuronFlyoutButton10Shine15 {
 }
 shine14 = NeuronFlyoutButton10Shine14 {
 }
 flyoutleft = NeuronFlyoutButton10FlyoutLeft {
 }
 shine9 = NeuronFlyoutButton10Shine9 {
 }
 iconframeaurawatch = NeuronFlyoutButton10IconFrameAuraWatch {
 }
 anchor = NeuronActionButton70 {
 }
 mac_flash = false
 unit = "target"
 pushedtexture = NeuronFlyoutButton10PushedTexture {
 }
 highlighttexture = NeuronFlyoutButton10HighlightTexture {
 }
 spellID = 159895
 shine = NeuronFlyoutButton10Shine {
 }
 shine2 = NeuronFlyoutButton10Shine2 {
 }
 cdcolor1 = <table> {
 }
 autocastable = NeuronFlyoutButton10AutoCastable {
 }
 macrospell = "Path of the Bloodmaul()"
 noAction = "Interface\Buttons\UI-Quickslot"
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
 iconframeflash = NeuronFlyoutButton10IconFrameFlash {
 }
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.

**Comment by wowregistering** [comment]
Message: ...ace\AddOns\Neuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:926: attempt to index field 'watchframes' (a nil value)
Time: Wed Dec 12 22:08:19 2018
Count: 2
Stack: ...ace\AddOns\Neuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:926: attempt to index field 'watchframes' (a nil value)
...ace\AddOns\Neuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:926: in function `Flyout_ReleaseBar'
...ace\AddOns\Neuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:670: in function `Flyout_RemoveBar'
...ace\AddOns\Neuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:682: in function `UpdateFlyout'
Interface\AddOns\Neuron\Objects/ACTIONBUTTON.lua:1428: in function `?'
Interface\AddOns\Neuron\Objects/ACTIONBUTTON.lua:1543: in function `MACRO_OnEvent'
Interface\AddOns\Neuron\Objects/ACTIONBUTTON.lua:462: in function <Interface\AddOns\Neuron\Objects/ACTIONBUTTON.lua:462>

Locals: self = NeuronActionButton70 {
 0 = <userdata>
 shine5 = NeuronActionButton70Shine5 {
 }
 shine1 = NeuronActionButton70Shine1 {
 }
 auraText = false
 iconframeicon = NeuronActionButton70IconFrameIcon {
 }
 tooltips = true
 shine12 = NeuronActionButton70Shine12 {
 }
 shine11 = NeuronActionButton70Shine11 {
 }
 shine16 = NeuronActionButton70Shine16 {
 }
 iconframefiller = NeuronActionButton70IconFrameFiller {
 }
 iconframebackground = NeuronActionButton70IconFrameBackGround {
 }
 bindColor = "1;1;1;1"
 spellGlowDef = true
 gloss = NeuronActionButton70Gloss {
 }
 shine7 = NeuronActionButton70Shine7 {
 }
 macroText = false
 multiSpec = true
 bar = NeuronActionBar2 {
 }
 flyoutbordershadow = NeuronActionButton70FlyoutBorderShadow {
 }
 auracolor1 = <table> {
 }
 macroColor = "1;1;1;1"
 shine13 = NeuronActionButton70Shine13 {
 }
 rangeInd = true
 barLock = false
 unit = "target"
 tooltipsCombat = false
 countText = true
 flyout = <table> {
 }
 debuffcolor = <table> {
 }
 keys = <table> {
 }
 upClicks = true
 tooltipsEnhanced = true
 macroshow = "Will of the Forsaken"
 macroname = NeuronActionButton70MacroName {
 }
 flyoutborder = NeuronActionButton70FlyoutBorder {
 }
 macroparse = " 
#showtooltip Will of the Forsaken 
"
 noAction = "Interface\Buttons\UI-Quickslot"
 config = <table> {
 }
 elapsed = 0
 shine6 = NeuronActionButton70Shine6 {
 }
 showGrid = true
 barLockCtrl = false
 hotkey = NeuronActionButton70HotKey {
 }
 class = "bar"
 FlyoutBorderShadow = NeuronActionButton70FlyoutBorderShadow {
 }
 flyoutright = NeuronActionButton70FlyoutRight {
 }
 spellGlow = true
 cdAlpha = 1
 objTIndex = 70
 count = NeuronActionButton70Count {
 }
 shine14 = NeuronActionButton70Shine14 {
 }
 hitbox = NeuronActionButton70HitBox {
 }
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
 updateGroup = 1
 shine9 = NeuronActionButton70Shine9 {
 }
 downClicks = false
 iconframeaurawatchtimer = NeuronActionButton70IconFrameAuraWatchTimer {
 }
 barLockShift = false
 data = <table> {
 }
 cdcolor2 = <table> {
 }
 objType = "ACTIONBUTTON"
 normaltexture = NeuronActionButton70NormalTexture {
 }
 mac_flash = false
 shine3 = NeuronActionButton70Shine3 {
 }
 rangecolor = <table> {
 }
 shine8 = NeuronActionButton70Shine8 {
 }
 FlyoutArrow = NeuronActionButton70FlyoutArrow {
 }
 pushedtexture = NeuronActionButton70PushedTexture {
 }
 DB = <table> {
 }
 checkedtexture = NeuronActionButton70CheckedTexture {
 }
 shine15 = NeuronActionButton70Shine15 {
 }
 iconframecooldowntimer = NeuronActionButton70IconFrameCooldownTimer {
 }
 shine = NeuronActionButton70Shine {
 }
 shine2 = NeuronActionButton70Shine2 {
 }
 cdcolor1 = <table> {
 }
 binder = NeuronActionButton70BindFrame {
 }
 buffcolor = <table> {
 }
 flyoutleft = NeuronActionButton70FlyoutLeft {
 }
 shine10 = NeuronActionButton70Shine10 {
 }
 iconframeaurawatch = NeuronActionButton70IconFrameAuraWatch {
 }
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
 countColor = "1;1;1;1"
 border = NeuronActionButton70Border {
 }
 cdText = false
 auraInd = false
 bindText = true
 shine4 = NeuronActionButton70Shine4 {
 }
 spellGlowAlt = false
 highlighttext

**Comment by wowregistering** [comment]
Message: ...ace\AddOns\Neuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:919: attempt to index local 'bar' (a nil value)
Time: Wed Dec 12 22:08:35 2018
Count: 2
Stack: ...ace\AddOns\Neuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:919: attempt to index local 'bar' (a nil value)
...ace\AddOns\Neuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:919: in function `Flyout_ReleaseBar'
...ace\AddOns\Neuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:670: in function `Flyout_RemoveBar'
...ace\AddOns\Neuron\Objects/ACTIONBUTTON_FLYOUTBTN.lua:682: in function `UpdateFlyout'
Interface\AddOns\Neuron\Objects/ACTIONBUTTON.lua:1428: in function `?'
Interface\AddOns\Neuron\Objects/ACTIONBUTTON.lua:1543: in function `MACRO_OnEvent'
Interface\AddOns\Neuron\Objects/ACTIONBUTTON.lua:462: in function <Interface\AddOns\Neuron\Objects/ACTIONBUTTON.lua:462>

Locals: self = NeuronActionButton70 {
 0 = <userdata>
 shine5 = NeuronActionButton70Shine5 {
 }
 shine1 = NeuronActionButton70Shine1 {
 }
 auraText = false
 iconframeicon = NeuronActionButton70IconFrameIcon {
 }
 tooltips = true
 shine12 = NeuronActionButton70Shine12 {
 }
 shine11 = NeuronActionButton70Shine11 {
 }
 shine16 = NeuronActionButton70Shine16 {
 }
 iconframefiller = NeuronActionButton70IconFrameFiller {
 }
 iconframebackground = NeuronActionButton70IconFrameBackGround {
 }
 bindColor = "1;1;1;1"
 spellGlowDef = true
 gloss = NeuronActionButton70Gloss {
 }
 shine7 = NeuronActionButton70Shine7 {
 }
 macroText = false
 multiSpec = true
 bar = NeuronActionBar2 {
 }
 flyoutbordershadow = NeuronActionButton70FlyoutBorderShadow {
 }
 auracolor1 = <table> {
 }
 macroColor = "1;1;1;1"
 shine13 = NeuronActionButton70Shine13 {
 }
 rangeInd = true
 barLock = false
 unit = "target"
 tooltipsCombat = false
 countText = true
 flyout = <table> {
 }
 debuffcolor = <table> {
 }
 keys = <table> {
 }
 upClicks = true
 tooltipsEnhanced = true
 macroshow = "Will of the Forsaken"
 macroname = NeuronActionButton70MacroName {
 }
 flyoutborder = NeuronActionButton70FlyoutBorder {
 }
 macroparse = " 
#showtooltip Will of the Forsaken 
"
 noAction = "Interface\Buttons\UI-Quickslot"
 config = <table> {
 }
 elapsed = 0
 shine6 = NeuronActionButton70Shine6 {
 }
 showGrid = true
 barLockCtrl = false
 hotkey = NeuronActionButton70HotKey {
 }
 class = "bar"
 FlyoutBorderShadow = NeuronActionButton70FlyoutBorderShadow {
 }
 flyoutright = NeuronActionButton70FlyoutRight {
 }
 spellGlow = true
 cdAlpha = 1
 objTIndex = 70
 count = NeuronActionButton70Count {
 }
 shine14 = NeuronActionButton70Shine14 {
 }
 hitbox = NeuronActionButton70HitBox {
 }
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
 updateGroup = 1
 shine9 = NeuronActionButton70Shine9 {
 }
 downClicks = false
 iconframeaurawatchtimer = NeuronActionButton70IconFrameAuraWatchTimer {
 }
 barLockShift = false
 data = <table> {
 }
 cdcolor2 = <table> {
 }
 objType = "ACTIONBUTTON"
 normaltexture = NeuronActionButton70NormalTexture {
 }
 mac_flash = false
 shine3 = NeuronActionButton70Shine3 {
 }
 rangecolor = <table> {
 }
 shine8 = NeuronActionButton70Shine8 {
 }
 FlyoutArrow = NeuronActionButton70FlyoutArrow {
 }
 pushedtexture = NeuronActionButton70PushedTexture {
 }
 DB = <table> {
 }
 checkedtexture = NeuronActionButton70CheckedTexture {
 }
 shine15 = NeuronActionButton70Shine15 {
 }
 iconframecooldowntimer = NeuronActionButton70IconFrameCooldownTimer {
 }
 shine = NeuronActionButton70Shine {
 }
 shine2 = NeuronActionButton70Shine2 {
 }
 cdcolor1 = <table> {
 }
 binder = NeuronActionButton70BindFrame {
 }
 buffcolor = <table> {
 }
 flyoutleft = NeuronActionButton70FlyoutLeft {
 }
 shine10 = NeuronActionButton70Shine10 {
 }
 iconframeaurawatch = NeuronActionButton70IconFrameAuraWatch {
 }
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
 countColor = "1;1;1;1"
 border = NeuronActionButton70Border {
 }
 cdText = false
 auraInd = false
 bindText = true
 shine4 = NeuronActionButton70Shine4 {
 }
 spellGlowAlt = false
 highlighttexture = NeuronActi

**Comment by wowregistering** [comment]
fixed with 0.9.38d

**Comment by brittyazel** [comment]
Haha you had such a thorough and well written big report, I was super excited to fix it. It's a shame I already fixed the issue haha
