### ISSUE TITLE
Hivemind quest

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#215]
I did mout chain. Not sure if you know quest/scenario ( https://warcraft-secrets.com/guides/the-hivemind  ) but on part of chain you get on floating circle and jump form one to another but in end or if you messed something you need to leave that circle but when you press exit button nothing happens.Fortunatly relog did same thing so i was able to continue.
Same thing happens on last part of chain when you need to get of platform.Press exit and nothing. I had to disable Neuron to finsih chain.

**Comment by brittyazel** [comment]
Hrm, I wonder why VehicleExit() doesn't work... I'll have to check and see what other options we have, unfortunately I only have a few ways to execute an "exit", as many are prohibited by blizz. I'll see what they're using though
