### ISSUE TITLE
Rogue Vanish state (Assa or Outlaw)

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#22]
I'm working on a french translation for Neuron, and it's nearly done, but as I test it I think I've find a strange beahavior. In Ass or Outlaw spec, when I vanish, my "action bar 1" (keeping the default one after a profile reset) is empty, and as soon as the vanish buff ends the bar is replaced by the state "stealth".
Looking at the code I think, we get the "stealth" with "GetNumShapeshiftForms()", and rogue only get one "stance" => "stealth".
So, I came with this solution inspired by the "shadow dance" workaround. In Neuron.lua : 
After this : 
`
		--Adds Shadow Dance State for Subelty Rogues
		if (NEURON.class == "ROGUE" and GetSpecialization() == 3 ) then
			NEURON.STATES["stance2"] = L.SHADOW_DANCE
			NEURON.StanceIndex[2] = 185313
			states = states.."[stance:2] stance2; "
		end
`

I add this : 
`	        --Adds Vanish State for Assa or Outlaw Rogues
		if (NEURON.class == "ROGUE" and (GetSpecialization() == 1 or GetSpecialization() == 2) ) then
			NEURON.STATES["stance2"] = "Vanish"
			NEURON.StanceIndex[2] = 1856
			states = states.."[stance:2] stance2; "
		end
`

Then, I can use the remap option from stealth to vanish, and "voila", it works like intended.
(Maybe the true solution is to automate the remap... I don't know).

If you agree with this solution, you should add a L.VANISH entree in the localization files and replace "Vanish" with this one.

P.S. : Sub is not a problem with the Shadow dance remap (Vanish seems to be on stance2 too so, Shadow  dance and vanish use the same state)

**Comment by brittyazel** [comment]
Ok I'll look into this tonight. I don't have a rogue so testing this will be tricky...hrm...

**Comment by SirLagardere** [comment]
Humm you can put it on hold... Since the latest changes (especially the localization reworks) I don't encounter this behavior anymore.  I'll keep you inform if at some point it reapears.

**Comment by SirLagardere** [comment]
Hi,
So I find a way to reproduce the problem. If I uncheck the "Stealth" in the GUI Homestate square (you find there Paged/Stealth(rogue)/Pet) of a bar, then check it back, I loose all the actions that was previously register to the stealth/vanish state and moreover I have again the "Vanish" problem (during the vanish phase (different buff ie "improved stealth) my bar is empty, and came back as soon as my stealth become active (buff is stealth)
