### ISSUE TITLE
Feature Request: Macro conditions

### ISSUE THREAD

**Issue by Apoxiosis** [brittyazel/Neuron#220]
Howdy, I picked up neuron and gotta say its a very pretty mod.

I asked about @cursor macros for neuron on reddit and I dont think I worded my question properly. I was wondering if I could create any button i wanted, or indeed an actionbar, that functions as an @cursor macro no matter what I put on it. I myself have a very specific use-case where I play with an xbox controller due to an injury, so @cursor macros take one extra step of clicking my thumbstick out of the equation, but even up to very high end raiders and pvpers, they all use @cursor macros. Is it possible to create a button/bar that will by default function as @cursor without having to make individual macros or edit the button individually?

**Comment by brittyazel** [comment]
Hrm I can look into it for sure. For right now, like I said on Reddit you have to add in the @cursor to a given button manually, there's no global @cursor default. Do you happen to know what happens if you put an @cursor conditional on a spell that doesn't have a cursor component?

**Comment by Apoxiosis** [comment]
the @cursor conditional seems to be ignored. i havent went and tried it with every spell, but I did try /cast [@cursor]Immolation Aura and it just cast immolation aura as normal, no weird things

**Comment by brittyazel** [comment]
Strange, it works great for me. When I do "/cast [@cursor] Efflorescence()" it pops the Efflorescence right where my mouse is without having to click

**Comment by Dasaneux** [comment]
Immolation Aura doesn't have a cursor component.

**Comment by brittyazel** [comment]
Ooooh I see. I'll look into adding the @cursor bar wide. No ETA on when this will happen though. I have other pressing things on my list

**Comment by Apoxiosis** [comment]
> Strange, it works great for me. When I do "/cast [@cursor] Efflorescence()" it pops the Efflorescence right where my mouse is without having to click

yeah, thats how it should work. im saying even using the cursor conditional on spells that dont have a cursor component works fine

> Ooooh I see. I'll look into adding the @cursor bar wide. No ETA on when this will happen though. I have other pressing things on my list

awesome. sounds good to me. when you do get to it, can you also look into doing the same for the extra action button? when i played around with it, i didnt find any way to set macr oconditionals to the extra action button.

quite annoyingly, there are tons of cases of extra action button functions having a cursor component (the flight mechanic on eonar, a world quest in one of the invasions has the same. throwing the orb in temple of sethraliss and also throwing the orb on the ghuun fight) and itd be nice to see the same functioality extended there if its not too much of a feat of engineering.

my apologies for the late reply btw, i dont frequent github or my email.

**Comment by DejayRezme** [comment]
You could add a separate tab to generate an #autowrite macro. And add things like @focus, @mouseover etc to it too. So the button knows what spell ID you dropped into it and when you check one of those modifiers it replaces the macro with a new autowrite macro. This would make these functions more accessible.

Ideally I think the flyout tab should work like this too. You can edit the macro by hand but for most cases it's autogenerated and you just check UI elements or add things to the keywords.

**Comment by Apoxiosis** [comment]
i actually havent used neuron for a while because i was just too used to bartender. has anything else changed since my OP in 2019 to facilitate y usecase? im pretty unfamiliar with the addon i general so i dont even know how i would set it up how you mentioned, but i would be willing to try it

**Comment by DejayRezme** [comment]
No these are just ideas that would need to be programmed for the addon.

I just play wow off and on so every time I come back and/or make anew character I need to make mouseover macros and forget the syntax. It would be nice if I could just drag flash heal to a button, then edit it and click on "mouseover" checkbox. The same for targeted aoe abilities.

Right now you need to type /m, click a few times to make a new macro, type in the syntax, then drag it to a button. Then do the same for every new targeted or mouseover ability you want. 

Thinking of it like that neuron is already better than separate macros, but this would put it over the top. But I think it shouldn't be a separate tab, just some small checkboxes that are only usable if you have a simple ability or "autowrite macro".

**Comment by DejayRezme** [comment]
This actually seems to have been a planned or removed feature, found this the ingame faq:

> Spell Target Options
> Spell target options allow you to automatically add certain cast modifiers to spells added to the bar.  Only spells dragged to the bar from the spell book will have these modifiers added.  A way to check to see if a spell will be affected is to look at the button using the macro editor.  If the macro has "#autowrite" at the beginning, then it can use the targeting options.
> 
> Self-Cast by Modifier:  When enabled, any spell cast while holding the selected modifier key will try to be cast on your character. Note the selected modifier for this setting is global and will be the same for every bar.  Changing it on one bar will change it for all.
> 
> Focus-Cast by modifier:  When enabled, any spell cast while holding the selected modifier key will try to be cast on your character's focus target. Note the selected modifier for this setting is global and will be the same for every bar.  Changing it on one bar will change it for all.
> 
> Right-Click Self-cast: When enabled, any spell cast by right-clicking on the button will try to be cast on your character
> 
> Mouse-Over Casting:  When enabled, any spell cast while holding the selected modifier key will try to be cast on the mob that the mouse cursor is currently over.  If the modifier for this option is set to "None" then it will always be on.

**Comment by Apoxiosis** [comment]
@brittyazel sorry for the ping, im unfamiliar with github and if you would have seen this naturally, but since this thread was pretty much necrod i figured it'd be safe. has this been looked into?

**Comment by DejayRezme** [comment]
brittyazel mentioned in another reply that he is busy with RL atm.

I've looked a bit into the code to learn wow addon coding and to fix some bugs, and those spell target options were actually made as bar options, which I think is the wrong place to do it. It also seems to have only worked with modifier keys. Not sure how people use these target options. I generally don't use modifier keys.

I've seen that the NeuronNext branch does some much needed refactoring. Which you really want before adding new UI features like this. Unfortunately this seems to have gotten a bit sidetracked and then 9.0.1 made changes to the master branch necessary.

So my guess is that any new UI features will have to wait until NeuronNext and first for merging the 9.0.1 changes into that branch.

**Comment by schmurfy** [comment]
@DejayRezme I miss this feature but I am pretty sure this was implemented in trinity bars but maybe a wow update broke that feature.

**Comment by ylixir** [comment]
closing in favor of #466
