### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by pottervogel** [brittyazel/Neuron#221]
Got couple hours free and updated, now there is this lua error, no action bars at all, no minimap button.
Someone mentioned this may be because of renamed bars? All my bars are renamed and I added some bars that where not originally there.

I'll recheck asap with no other addons, if there is something different.

2x SharedXML\Util.lua:191: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
SharedXML\Util.lua:191: in function `CopyTable'
Neuron\Utilities/DB-Fixer.lua:142: in function `DBFixer'
Neuron\Neuron-1.0.0.lua:167: in function <Neuron\Neuron.lua:142>
[C]: ?
...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:498: in function `InitializeAddon'
...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:613: in function <...aceMasque\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>

**Comment by pottervogel** [comment]
ok, no other addon but buggrabber, still no bars ^^

**Comment by brittyazel** [comment]
Ya the no bars is because of the Lua error early on in the add-on loading process. I'll add some safety checks and get a new version out today. Until then just hang tight on the previous release

**Comment by brittyazel** [comment]
Ok I think I fixed it, can you test with the latest code from MASTER and let me know if it solves your problem? If it does, I'll release a new version

**Comment by pottervogel** [comment]
Checked it. There are the  bars, but no buttons. Only lua message from bug grabber 30x nil.

**Comment by brittyazel** [comment]
This is so weird. Something is fully broken in your database for this to keep hitting the same nil error. I don't have any more safety checks I can do. This is so weird. How long have you been using this same profile?

**Comment by brittyazel** [comment]
Is this the same for all of your toons?

**Comment by pottervogel** [comment]
would it help to send you the db file?
I have this since neuron started, well no first there where different files per char in the chars savedvars directory, but beside that since start.
[Neuron.zip](https://github.com/brittyazel/Neuron/files/2706850/Neuron.zip)

**Comment by pottervogel** [comment]
I don't use the statusbars and bagbar, maybe this has to do with it?

**Comment by brittyazel** [comment]
Hrm, I'm thinking maybe the profile is just really old and there was some low level corruption in it, i.e a loopback table or a funky old setting. Just an fyi without the status bars you wont have any castbar or mirror bars.

Anywho, I'll double check your profile to see what I can see, but the odds of it jumping out to me just by sight is probably pretty slim. As much as I hate to say it, you may need to remake your profile :-/ Now that we're at a stable 1.0 release there won't be any more database breakages, but sadly the major changes got your profile caught in the crossfire

**Comment by pottervogel** [comment]
no, not so much - the mirror, status, bag... was modular so i did't use them at all. For me it was fine to have the lua file per char cause i have a lot of toons and if something is wrong it didn't effect everything. also (i'm not completely sure about it but i think)  the bars could be edited while i used both accounts at the same time, and this does not work anymore. ok - you say i have to do it all over - sigh - well the translation will have to wait a little longer  ;-)
