### ISSUE TITLE
Neuron does not load on shadow priest. 

### ISSUE THREAD

**Issue by TBABlackPanther** [brittyazel/Neuron#223]
After Update i can play with Neuron on all chars. But when i logg in in with my shadow priest i cant see any Bars or something. And get this error:

2x Neuron\Utilities/DB-Fixer.lua:64: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
Neuron\Utilities/DB-Fixer.lua:64: in function `DBFixer'
Neuron\Neuron-1.0.0.lua:167: in function <Neuron\Neuron.lua:142>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:529: in function `InitializeAddon'
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:644: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>

**Comment by brittyazel** [comment]
Yeah your not the first with this. Can you download the latest build from GitHub to let me know if my patches fix your issue? If they do I'll out out the new version with the fix. (You can also roll back to the previous release)

**Comment by TBABlackPanther** [comment]
Ok thank you.

**Comment by Addonman** [comment]
Its not fixed.Getting this
Message: ..\SharedXML\Util.lua line 191:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:613:
      ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:575
   (tail call): ?
   [C]: pairs()
   ..\SharedXML\Util.lua:191: CopyTable()
   Neuron\Utilities/DB-Fixer.lua:143: DBFixer()
   Neuron\Neuron.lua:167:
      Neuron\Neuron.lua:142
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:529: InitializeAddon()
   ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:644:
      ...\AddOns\AchieveIt\libs\AceAddon-3.0\AceAddon-3.0.lua:636

**Comment by brittyazel** [comment]
ok can you test the latest build now?

**Comment by brittyazel** [comment]
I swear the database migrations are going to be the death of me. I get so stressed out whenever I have to do anything to your guys' profiles
