### ISSUE TITLE
Action bar 1 not changing when possessed / in vehicle.

### ISSUE THREAD

**Issue by Dasaneux** [brittyazel/Neuron#229]
After the last update, my main action bar is not changing to the new skills given when doing possessed or vehicle type quests. I can use the buttons as if they're changed, but the bar is not showing any changes.

For example the Tortollan beachhead world quests, I can still shoot the skill by pressing 1, but my bar looks normal.

I tried making a new bar, but had the same thing happen.

**Comment by brittyazel** [comment]
Is this on the latest release? 1.0.2b had this issue, but it should have been fixed in 1.0.2c
