### ISSUE TITLE
Translation causing issues

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#23]
With my testing,I stumble across a translation issue with Neuron. It seems that "the code" try to use the localized version of the states in ref to there indexes, and... It can not work ^^.
To avoid this, I've change this in Neuron.lua : 
`NEURON.STATEINDEX = {
	paged = "paged",
	stance = "stance",
	pet = "pet",
	alt = "alt",
	ctrl = "ctrl",
	shift = "shift",
	stealth = "stealth",
	reaction = "reaction",
	combat = "combat",
	group = "group",
	fishing = "fishing",
	vehicle = "vehicle",
	possess = "possess",
	override = "override",
	extrabar = "extrabar",
	prowl = "prowl",
	custom = "custom",
	target = "target",
}`
Then, translation and addon works flawlessly :)

**Comment by brittyazel** [comment]
You're absolutely right. Nice catch, being that I only use English I hadn't run into this error yet. I implemented this fix
