### ISSUE TITLE
New profile: Incoherent Scaling

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#230]
Hi there :)
Just a little bug when you reset your profile : 
![image](https://user-images.githubusercontent.com/20615278/50558579-d7474500-0cef-11e9-80f0-b45973f9258c.png)
The first two action bars are the default one, the 3rd one was added by me, and, from the scale option of each bars, each one is at 1...
Hope you could look into it :)

**Comment by SirLagardere** [comment]
FYI, I've uninstall completly Neuron, wipe clean saved variable, and install it again, and the scaling seems to be coherent again.

**Comment by brittyazel** [comment]
So this issue isn't a problem anymore? I was playing around with it and it wasn't a problem for me any longer. Can we close this ticket?

**Comment by SirLagardere** [comment]
Yes we can, retry today and everything is on track ;)
