### ISSUE TITLE
Adding action bars from scratch: incoherent enumeration

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#231]
To sort temporaly my scaling problem (#230), I've try to wipe all the action bars and create new one.
I couldn't delete all of them, every time one was staying on screen (initial shape, no button on it)
And if I create bars, I'll finished in this situtation : 
![image](https://user-images.githubusercontent.com/20615278/50558699-c0552280-0cf0-11e9-8126-de04c6e2fe89.png)
Only 2 actions bars listed in the conf window, 3 bars on my screen, 2 of them with the same name.

**Comment by brittyazel** [comment]
Yeah I'll look into this. Usually a /reload sorts this type of behavior out

**Comment by brittyazel** [comment]
fixed
