### ISSUE TITLE
How to get vehicle abilities to show up in bars

### ISSUE THREAD

**Issue by Vorcikle** [brittyazel/Neuron#232]
for example there's a quest where you mount a gryphon but i'm not sure how to display the abilities on the actual bar.

**Comment by brittyazel** [comment]
Whatever bar you consider your "main" bar needs to have the vehicle, possess, and override states checked in the bar configuration window

**Comment by Vorcikle** [comment]
I actually got vehicle working now except now the icons for it are invisible.

**Comment by brittyazel** [comment]
That shouldn't be the case. Which version of Neuron are you on and are you sure you are up to date? On all of my toons vehicle buttons work exactly as they should
