### ISSUE TITLE
Custom Icon not overriding Spell Icon

### ISSUE THREAD

**Issue by wowregistering** [brittyazel/Neuron#233]
When attempting to use the icon changer in the button editor it fails to display the selected icon or custom texture and continues showing the icon of the spell in the button macro.

If you open the button editor and make the macro '/cast Shadow Dance' and then try to change the icon to one of the icons from the list or to a custom icon it will continue showing the icon for Shadow Dance.

If you make the same macro using the Blizzard macro interface, change the icon to something else, and then drag that macro to the Neuron bar it will display the icon you selected properly instead of just showing the icon of the spell in the macro.

Using #showtooltip spellname or id does work to change the icon, it is just the custom icon selection in the Neuron button editor that seems to not be changing icons properly.

**Comment by brittyazel** [comment]
This should now be fixed. I rewrote the entire macro  parse pipeline
