### ISSUE TITLE
Range not updating or slow to update

### ISSUE THREAD

**Issue by wowregistering** [brittyazel/Neuron#234]
I have recorded a short clip displaying the range check issue I am experiencing.
Buttons
1: /cast Shadowstep
2: /cast [@mouseover] Shadowstep
3: /cast [@mouseover,exists] Shadowstep; Shadowstep
4: /cast Shadowstep/cast Kick
5: /cast Toxic Blade

Button 5, with Toxic Blade on it, is only being used so I have a button I can press that will not cause me to hit or teleport to the target while still displaying when I am entering a keypress that triggers an update of the range.

The white numbers below the bar are displaying my current distance to the target, when it displays 20-25 or less I am in range to Shadowstep and when it displays 25-30 or more then I am out of range to Shadowstep.

Video Timeline
0:00-0:02 I move my mouse over the target and there is about 1s of delay before it displays out of range, this is a mouseover only macro

0:04-0:07 I move in range of Shadowstep, wait a few seconds, and then press Toxic Blade to update the range display

0:07-0:11 I move out of range of Shadowstep, wait a few seconds, and then press Toxic Blade to update the range display

0:14-0:17 I move closer to the target until the range display updates to show Shadowstep as 'in range' while not pressing Toxic Blade to force it to update the range.

0:17-0:25 I move out of range of Shadowstep and wait for the range to display that I am no longer in range.  I am out of range at 22.3s and the range display updates at around 24.3s

0:25-0:33 I move in range of Shadowstep and wait for the range to display that I am in range without me pressing Toxic Blade to cause the range to be updated.  I am in range at 26s and it updates the display of my range at 33s.

https://gfycat.com/ColdSeriousBurro

I had an issue similar to this when using [harm] [help] conditionals on my Druid in the past but I just ignored it, never caused me any issues.  My Druids bars are not set up again yet, if you want me to test those on my Druid I can do that as soon as I get a chance.

_Originally posted by @wowregistering in https://github.com/brittyazel/Neuron/issues/211#issuecomment-450702563_

**Comment by brittyazel** [comment]
Yeah so it turned out that 98% of the considerable addon CPU usage was just for range checking, so I've been experimenting lately with new and better ways of handling accurate range checking with out literally checking each button each frame of the game. Right now I have the range check bound to specific in game events that are happening, but it seems like I don't have all of the events accounted for.

I'm going to play around with adding more event watchers to get the range timing down even moreso than now.

**Comment by wowregistering** [comment]
It is not that much of an issue, being able to see the range on the bar does not matter that much.

I just happened to notice the range display being weird while I was setting up the bars on my rogue, not normally going to be staring at my bars to notice it.
