### ISSUE TITLE
Grid shows up on its own after some amount of time

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#238]
I have grids disabled on all my bars so I don't see blank buttons, however, in the latest release the grid just shows up at some point.  Notably, it's happened twice while I was logging out of my toon during the 20 second timer, once with 7s left, once with 3s left.  No error is showing up so I can't provide any reference as to why it's happening.

The grid also shows up when I first log into the toon which it shouldn't, going into and out of config mode gets rid of it temporarily until it comes back as above.

**Comment by Dasaneux** [comment]
Having the same issue.

**Comment by raysmith59** [comment]
Seems okay now.
