### ISSUE TITLE
Issues with stance/forms

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#24]
I thought this may have been improved/fixed previously but it's still ongoing.

For my Boomkin druid, switching to cat/bear and back to Boomkin doesn't switch the bars to the Boomkin set, they stay as cat/bar.  As a workaround I have to go into Travel or Caster form first, then to Boomkin... not the end of the world but costs a GCD each time and requires that I have additional hotkeys available to shift out of a stance I'm already in.

There's a secondary issue if my cat is in prowl/stealth at the time of transitioning out, in that case the Travel/caster form transition doesn't change the bars so I have to basically go out of stealthed cat, back into cat, then into Travel/caster, then into Boomkin... this at least doesn't happen while I'm in combat but it's very clunky to get out of.

As well, shaman wolf form and priest shadow form are also acting as stances (ie. separately tracked bars), however they shouldn't be.  I'm not aware of this issue on other classes but there may be others.

I haven't noticed any rogue stealth issues, for what it's worth, although I don't tend to play him in stealth, I mostly use it for the passive speed boost talent when moving around indoors.

**Comment by brittyazel** [comment]
I've heard that shadow priest, wolf form, and shadow form are being tracked as separate stances, but know my shaman at least it is not. I have to try to replicate this and figure out what's going on

**Comment by SirLagardere** [comment]
Hope it could help : 
I just test it on my setup, are you using the "stance" propertie of the selected bar ? (In GUI, Bar States, should be in the middle of the top-left square).
When you use the "stance" state, every stance get a valid state for the bar (you could validate this by entering editing button mode, and right click one of them, you should find an entry for each form)

**Comment by raysmith59** [comment]
Yes, I use that Stance setting for my main action bar, it's the one causing the problem.  That some "non-stances" have their own bar is an annoyance but not a huge deal, the bigger issue is with the druid where in some pretty typical circumstances I'm not getting the Moonkin bar to show up when I shift to that form.  I've included more detail in the comments section on WoW Interface, I just created this for tracking purposes.

My only workaround I can think of is to disable stances and instead do every button as a macro with stance modifiers for each desired stance... I assume that would work but it's ugly and I'm avoiding doing it as long as possible.

**Comment by brittyazel** [comment]
I'm sure I can fix this. I get back this evening, so I can take a look at it tomorrow afternoon.

**Comment by brittyazel** [comment]
Ok I reverted a change to prowl causing some form switch state issues.

As far as the other forms, double check in the bar editor mode under states where the state is mapped to. By default I believe moonkin form is mapped to the caster form state (a blizzard decision), however you can map it to its own state form there. Do this the same with wolf form and priest shadow form, if you don't want them to have their own forms just map those states to the homestate(caster state or whatever).
Can you test this out and report back if you're still having issues? If that was the problem, I'll make sure to make these options much more apparent and visible with the GUI rework.

**Comment by raysmith59** [comment]
I'm still having issues going directly from cat to moonkin without making any other changes and I don't currently have anything mapped, I still have go go either to caster or travel form and then shift to moonkin.  For what it's worth all 3 of those forms have the same buttons on the bar and I'm pretty sure I didn't specifically set them up that way so at least from a Neutron perspective they seem to be sharing a set of buttons but the cat->moonkin or bear->moonkin shift isn't accounting for that.
I wasn't even aware of the remapping function but it doesn't seem to do anything, I tried mapping moonkin->caster and caster->moonkin, in neither case did it change the bar when I went from cat->moonkin.
Seems this is still an issue, unfortunately.
Upside, I'm blaming this double-shift requirement for my middling dps this tier so far, once it gets fixed I'm going to have to find a new excuse.

**Comment by brittyazel** [comment]
Haha I'll keep looking into it. This whole idea of three forms having the same buttons is concerning to me. The druid forms should all be on a "stance bar", can you confirm that you are using the stance bar?
I'll have to double check on my end, but in my testing last night I didn't seem to have any issue with my moonkin bar loading straight from cat form. Can you maybe drag moonkin form and bear/cat form onto some other button somewhere (drag it straight from your spellbook to avoid weirdness), and see if the same things happens? I'm just trying to get a sense if it is an underlying code bug or a weird button bug.

**Comment by raysmith59** [comment]
Never even thought to mention it but I don't use the actual stance bar, I have the forms keybound on my main action bar.  I did just try the stance bar buttons and they're doing the same thing, too.... I change from Moonkin to Cat and I get the Cat action bar, then I go back to Moonkin and it's still with the Cat buttons.  In case this is some legacy taint I tried removing the buttons from my action bar and dragging them back on and there was no change.  I'll do some more screwing around this weekend but if you're not seeing that symptom then I may just change the buttons to be stance-aware and get rid of the stance aspect of the action bar.

**Comment by raysmith59** [comment]
I never got around to really testing, I ended up just disabling the stance bar option and created the multi-stance buttons.  It worked, it's just a pain in the ass to set up.  Since it sounds like you're not having the same issue (and I haven't seen anyone else report it) I'm assuming it's on my end so you can close this one off.  At this point the only thing I can think to do is to completely remove the add-on and start from scratch and that isn't in the cards right now, I may do it between expansions though.

**Comment by Xurkon** [comment]
I'm having a similar issue with stealth and [stance:2] for some reason no matter what I do the bar goes blank on subterfuge/vanish. I've tried editing the button with custom stances and it still goes blank but comes back after that stance ends.

**Comment by brittyazel** [comment]
@Xurkon it sounds like it's treating subterfuge/vanish as a new stance and thus providing a new bar. Do you have this option checked in the bar-states? I believe rogues get an extra state that the other classes don't get for sub/vanish

**Comment by Xurkon** [comment]
That's what I was saying, it's suppose to be stance2 for rogues, but no I don't see a specific preset state for that specifically.

**Comment by SirLagardere** [comment]
I think it could be related to #22

**Comment by Xurkon** [comment]
Yea I agree, I went ahead and just wrote macros for all my abilities with the button editor and that works for now.

**Comment by brittyazel** [comment]
OK I fixed the druid part of this issue for good I think. It really is Blizzards fault that I need to hack around their code, but whatev. From my testing this is stable. Xurkon, your issue is different, can you provide more info on a different bug report so I can track it. I'd like to close this one.
