### ISSUE TITLE
Bars not showing any buttons.

### ISSUE THREAD

**Issue by Dasaneux** [brittyazel/Neuron#241]
I created a profile that I can use as a global setup. What happens though is that when I enable the profile for a new character, quite often I am unable to put any skills onto a bar.

In the screenshot you can see that my main action bar and the small 2 button bar to the left of it have no grid, despite having grid enabled.

When I close the Neuron GUI and drag an ability from my spellbook to where my main action bar should be, nothing happens. No blank bar, or anything else, shows.

![wow 1](https://user-images.githubusercontent.com/44789225/50590071-7715f600-0edd-11e9-976e-ebca8cf66210.jpg)

**Comment by brittyazel** [comment]
I'm pretty sure this is fixed. It took more hours than I care to admit, but I think it's working

**Comment by Dasaneux** [comment]
Certainly, I'd be happy to any release :)
