### ISSUE TITLE
Bar with a stealth mode doesn't come back when leaving stealth

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#247]
I have an action bar that's set to Stealth, it seems to correctly switch into Stealth mode but when Stealth ends the bar goes blank until I go into and out of config mode.

**Comment by brittyazel** [comment]
hrm, I don't have this issue. On my low level rogue I can go back and forth between my stealth bar and normal bar just fine

**Comment by AlexFolland** [comment]
Maybe it only happens if you leave stealth in combat.

**Comment by brittyazel** [comment]
Rogue, I was at the target dummy when I tested. I can test on my druid also in a bit

**Comment by raysmith59** [comment]
Interesting, I was on my rogue standing at the mailbox.  I don't think I'd relogged at the time, though, I'll try doing that.

(behaviour before and after relogging can vary quite a bit and I don't always think to relog before testing/submitting)

**Comment by raysmith59** [comment]
Yep, working now after the relog.  Closing.
