### ISSUE TITLE
Mount button indicator

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#248]
Not really sure what's going on so I'll document it here.  Setup: Logged into toon, not mounted.

Button (correctly) looks like:
![image](https://user-images.githubusercontent.com/2917594/50654027-7ae75e00-0f59-11e9-8bb1-8372ed723021.png)

When I mount up it gets a yellow border that I can't account for (not sure I've seen it before and none of the optional aura configs would explain it), I'm expecting it to have the green aura indicator, not the yellow one... maybe a temporary state during the cast that isn't completing properly?
![image](https://user-images.githubusercontent.com/2917594/50654101-bf72f980-0f59-11e9-9eef-3ef8687ca333.png)

After I dismount:
![image](https://user-images.githubusercontent.com/2917594/50654155-e4676c80-0f59-11e9-8b2f-b4c00650c8dc.png)

**Comment by brittyazel** [comment]
Weird, I have no idea what is causing the yellow like that. Are you using Masque? Maybe it's a Masque setting

**Comment by raysmith59** [comment]
No, but to test further I tried disabling all add-ons except Neuron and it's doing the same thing.  Seems to be Neuron.

Here are my bar settings in case this helps:

![image](https://user-images.githubusercontent.com/2917594/50666290-0d035c80-0f82-11e9-96e7-a5a939f7814f.png)

**Comment by brittyazel** [comment]
Ooh it might be the aura border

**Comment by brittyazel** [comment]
I think there's a base color that shows when your mounted, and it's being compounded with the aura border

**Comment by brittyazel** [comment]
So with the default UI when you are currently "using" a button, i.e. on a mount, you get a yellow border around the button. That's where the yellow is coming from. The green aura glow also just happens also because the mount acts as an aura.

To get around this I'd suggest a Masque theme. I don't want to change the stock theme from differing too much from the stock blizz UI

**Comment by raysmith59** [comment]
This is still an issue, the yellow should only show up while the cast is happening.  Right now the yellow remains, up to and including when I'm automatically dismounted when entering a building... which doesn't make sense.  I don't believe this is normal behaviour for the stock UI either.

**Comment by raysmith59** [comment]
Not sure how I missed this before now but profession buttons are doing the same thing, they're staying yellow even after the profession window is closed.

**Comment by brittyazel** [comment]
I fixed this for the mount. I'll add in the fix for the profession windows once I get home.
