### ISSUE TITLE
Spells when added aren't reflecting the case of the original spells

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#249]
(OCD FTL... low priority)

Spells when dragged to the bar are all lower case rather than reflecting the original case of the spells (mixed upper/lower) as used to happen.

**Comment by brittyazel** [comment]
In the name or in the macro itself?

**Comment by raysmith59** [comment]
Macro detail itself.  I really should include more screenshots.

![image](https://user-images.githubusercontent.com/2917594/50666331-4e940780-0f82-11e9-946c-a54710674801.png)

**Comment by brittyazel** [comment]
Yeah this was done mostly for uniformity in spell lookups. When saving spells to our spellcache we automatically put them all lowercase, we also put whatever macro is written by the user or autowritten lowercase during the lookup as well, that way no matter how many crazy capitalizations a person does, the right spell will always be found (you just have to spell it right). Unfortunately, this leads to it being lowercase when dragged to the bar. I could probably change this and still keep the uniform check working

**Comment by raysmith59** [comment]
Yeah, I'm mostly just worried that at some point Blizzard will bring in case-sensitivity because that's one of the few things they haven't done to screw me up this expansion.  So many bugs and bad changes...

Probably doesn't matter.

**Comment by raysmith59** [comment]
Good first issue flag?  :)

**Comment by brittyazel** [comment]
haha yeah it's a good one for people wanting to get their feet wet at programming, because it's pretty small to fix. I actually already fixed it though lol. If you're not seeing it, you need to try re-dragging an ability. Unfortunately I can't retroactively rewrite the already written macros
