### ISSUE TITLE
Neuron Bar Disappearing 

### ISSUE THREAD

**Issue by DiggumFrog** [brittyazel/Neuron#250]
Hello again! 

As requested, here is the issue posted on GitHub from our Reddit conversation. What was happening was that I set up a few bars for my Horde Havok Demonhunter. First, I copied the bar from my Alliance Vengeance Demonhunter so I didn't have to recreate the layout from scratch as I use a similar layout for most toons, then I replaced the pertinent class spells. 

EDIT: Forgot the image I was referencing in the next paragraph. https://imgur.com/LH0sFDK

As you can see from my bar layout, there are 3 Neuron bars above the blizzard bar. It was the lower one which started disappearing. The bar still seemed to be there, but the abilities were gone, like empty button windows. I discovered that if I right click the Neuron orb on the minimap frame that they would come back, however, it was a crapshoot whether they'd work or not. Most of the time I had to actually replace the spells back into their cells to get them to function again. 

The behavior seemed to have something to do with the Val'Sharah Zone during a Legion invasion. I was doing the quest where you can hop in a tank and drive around to shoot the demons. When I exited the vehicle, the bar's weird behavior happened and it was repeatable. But it also happened mid flight once while I was going from one world quest to the next. 

I have not noticed this behavior on any of my other toons, and I did the same world quest it was happening the most on with all of my lower level toons in Val'Sharah tonight during the invasion.

**Comment by brittyazel** [comment]
Do you have any strange bar states enabled on that bar? If you are using the default blizzard UI, you should probably make sure possess/override/vehicle are disabled on the other bars
