### ISSUE TITLE
Extra Action, Zone Action and Vehicle Exit bar icons are all greyed out

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#253]
I thought this had been reported at some point but if so I'm not seeing it.  The icons are greyed out even when they're usable.

**Comment by brittyazel** [comment]
Can I have a screenshot of this please?

**Comment by raysmith59** [comment]
Vehicle Exit:
![image](https://user-images.githubusercontent.com/2917594/50858565-bcfc0f80-135e-11e9-811d-6cd276ba9c9e.png)

Zone Action:
![image](https://user-images.githubusercontent.com/2917594/50859136-80311800-1360-11e9-8973-da04b3f56c74.png)

Can't find a scenario for Extra Action to get a screenshot but I'm assuming you'll be able to confirm what whatever's happening with the other two will also be happening with that one.

(and I'm still wanting a way to get rid of the button borders :) )

**Comment by raysmith59** [comment]
This appears to be working correctly in the latest release.
