### ISSUE TITLE
On upgrading to 1.x bars multiply

### ISSUE THREAD

**Issue by dpwrussell** [brittyazel/Neuron#258]
No idea what is going on with this bug. I logged in and:
![wowscrnshot_011519_191307](https://user-images.githubusercontent.com/1889043/51203918-33b68100-18fa-11e9-96ae-acdc4cbd149f.jpg)

If I go to configure one of those bars (which should have 5 buttons each) it says that it has 15 buttons. If I click the button to decrease/increate that number, the number of buttons it says I have stays the same, but the bar does shrink down.

Possibly related is that the profile page is not working like it used to. Sometimes when I select a different existing profile it reloads (like it used to), but mostly it does not. Also, if I copy from an existing profile, it does not reload and basically nothing happens.

In general I think maybe things are getting mixed up between profiles perhaps? I always configure my bars on one char then copy that to all other profiles (which I did months ago) where I replace the macros, not sure if that's relevant, but as most of the extra buttons are from my paladin when I logged on my mage, makes me think it might be.

**Comment by brittyazel** [comment]
Is this your first time upgrading to the 1.x series? This is a unique issue that I haven't seen before. I'm not exactly sure what is going on here. Even after /reload you can decrease the bar size?

**Comment by dpwrussell** [comment]
Ah, are you doing some kind of schema upgrade when installing 1.0? Ive done
it several times when trying the 1.0 series, each time reverting because of
the issue where CD didnt show correctly for multiple charges.

**Comment by dpwrussell** [comment]
Ok, great. I think safe to close this then. I'll start again from scratch ans let you know if the weird issues with profiles persist after that.

**Comment by brittyazel** [comment]
Awesome, thanks. Keep an eye on the cooldowns as well and let me know if they're satisfactory for you. It's easy for me to tweak things now that I rewrote that part of the code
