### ISSUE TITLE
Extra Action Button not clearing

### ISSUE THREAD

**Issue by TruthNZ** [brittyazel/Neuron#259]
With release: 1.0.4b the Extra Action button is staying up, after the action is no longer available.

**Comment by brittyazel** [comment]
Can you try with the code in MASTER to see if this is still an issue? I rewrote the extra action bar yesterday m so it might be fixed already

**Comment by TruthNZ** [comment]
Had to delete and recreate the Extra Action Button bar to get it to work (whatever change you made meant my existing on ceased to work at all).
However once doing so, it's now working perfectly again. Thanks.
