### ISSUE TITLE
Bug 0.9.11

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#26]
Hi,
Something messing around with the NEURON.STATEINDEX  in Neuron.lua : 
At this time : 
NEURON.STATEINDEX = {
	paged = "paged",
	stance = "stance",
	stance = "stance",
	pet = "pet",
	alt = "alt",
	ctrl = "ctrl",
	shift = "shift",
	stealth = "stealth",
	reaction = "reaction",
	combat = "vehicle",
	group = "group",
	fishing = "fishing",
	vehicle = "custom",
	possess = "possess",
	override = "override",
	extrabar = "extrabar",
	custom = "custom",
	target = "target",
}

combat and vehicle should be 
NEURON.STATEINDEX = {
	paged = "paged",
	stance = "stance",
	stance = "stance",
	pet = "pet",
	alt = "alt",
	ctrl = "ctrl",
	shift = "shift",
	stealth = "stealth",
	reaction = "reaction",
	**combat = "combat ",**
	group = "group",
	fishing = "fishing",
	**vehicle = "vehicle ",**
	possess = "possess",
	override = "override",
	extrabar = "extrabar",
	custom = "custom",
	target = "target",
}

Anotherthing, in Neuron-GUI.lua : 
			--Renames Stance for rogues to Stealth as that is what should really be used
			if state == "stance" and (NEURON.class == "ROGUE") then
				f.text:SetText(L["STEALTH"])
			else
				f.text:SetText(state:upper())
			end
			f.option = state

L["STEALTH"] is not ref in the language files.
Maybe you could use something like f.text:SetText(L["Stealth"]:upper())

**Comment by brittyazel** [comment]
You are 100% correct. I have no idea why that happened.... fixed anyhow. New version rolling out now!

**Comment by SirLagardere** [comment]
Maybe you should upper cast the "stealth" string to be more clean on the UI side (right now we've got Stealth in lowercase and Paged and Pet uppercase)
![image](https://user-images.githubusercontent.com/20615278/34494908-ed4d565c-eff2-11e7-8e7b-52ed645e0e64.png)

**Comment by brittyazel** [comment]
Done. I don't have a rogue so I never saw this lol
