### ISSUE TITLE
On GCD cooldown Boneshield stacks aren't showing

### ISSUE THREAD

**Issue by TruthNZ** [brittyazel/Neuron#260]
Release: 1.0.4b. Death Knight: Blood

Marrowrend normally shows the current Boneshield stacks, like charges on other abilities. However for since 1.04b they disappear when the GCD cooldown is occurring, returning as soon as abilities are ready to use again. But given I try to keep as much as possible happening, that leaves it not showing quite a lot of the time.

**Comment by brittyazel** [comment]
Are you using Masque or no? This may be another frame level bug where the text layer is getting overlapped

**Comment by brittyazel** [comment]
I can't replicate this with my druid and Swiftmend. Swiftmend shows the stacks in the bottom right corner even during a GCD with both Masque and without Masque. Is there a way you can screencast or screenshot this for me so I can see what you mean?

**Comment by TruthNZ** [comment]
Not using Masque.

https://youtu.be/lWsN9MEA6Fg
This was actually running the current master branch (commit 213f99f). I initially thought it was just during the GCD cooldown, but looks like it's just cutting in and out. I couldn't quickly find a pattern as to when and why sorry.

**Comment by brittyazel** [comment]
Super weird. I get what you mean now though.

I'll dig into that part of the code tomorrow probably (I'm spent for tonight) and see if something looks fishy. I don't have a DK so I'll be coding somewhat blindly. Are there any other classes with similar abilities you can think of? It makes it way easier to code if I can replicate the issue

**Comment by brittyazel** [comment]
Can you test the latest commits I put into MASTER? I ~think~ I may have caught the issue, but I can't test it myself unfortunately

**Comment by TruthNZ** [comment]
Nope still same in commit 1dbe442 :(

**Comment by brittyazel** [comment]
Damn. This may be asking a lot, but can you test version 1.0.4 and then 1.0.4a then 1.0.4b and confirm is exactly which release this started occurring? If I can pinpoint which release, I may be able to find the exact commit that started the issue

**Comment by brittyazel** [comment]
Alright I made another change, can you try that out for me?

**Comment by brittyazel** [comment]
Awesome! Thanks so much, we'll figure this out eventually ;-)

**Comment by TruthNZ** [comment]
1.0.3d worked perfectly (at least for that).
1.0.4 Doesn't show any stacks or charges for me at all.
1.0.4a shows charges, but has the disappearing stacks (as per that video).

Hope that helps!

**Comment by brittyazel** [comment]
Ok so going back to your video, your number 4 and number 6 abilities don't have this issue. It's something different about this particular ability that is messing up. This is odd to me, and it might be because this isn't a traditional "charge" ability. It's more like a stack size

**Comment by TruthNZ** [comment]
Working perfectly.

Thank you!
