### ISSUE TITLE
Can't use Heart of Azeroth

### ISSUE THREAD

**Issue by Trajin** [brittyazel/Neuron#261]
Just installed the latest version of Neuron and it's trying to target with the Heart of Azeroth.   I'm running the Azerite Wound world quest and each time I try to use the heart of azeroth to heal, it says I have no target.

**Comment by brittyazel** [comment]
Interesting. I'll have this fixed later today, for now feel free to roll back to 1.0.4b if you can't wait. Thanks for the report. (I rewrote the extra action button btw so this is most likely a side effect of that)
