### ISSUE TITLE
Problem with Vehiclebar since 1.0.2 (German Client)

### ISSUE THREAD

**Issue by Solithe** [brittyazel/Neuron#262]
Heya. I have a problem with the Vehicle Bar.

 

When i start a Quest that use the Vehicle bar and i press the 1, 2 or whatever hotkey, the game say : You can´t do that atm

If i click the button with the Mouse, it works.

 

Im on a German Client

 

 

Mfg Soli =)

 

 

Edit:  I Tested all Versions behind 1.0.5c and  1.0.1 is the last Version that works

**Comment by brittyazel** [comment]
Can you post a screenshot of when you are in a vehicle quest? I can't replicate this.

Do you use a separate vehicle bar, or does your main bar become the vehicle bar with the vehicle state enabled?

**Comment by Solithe** [comment]
my mainbar changes to the vehicle bar

https://drive.google.com/file/d/154_q8bQkIQ8n3Wsw2hBCWBrwQdnpqSpb/view

1.0.1 works



https://drive.google.com/file/d/1hEFtghBbQd-pfEVUsJd52_POU8WGrH3a/view

1.0.6 not

**Comment by brittyazel** [comment]
Hrm... interesting. You're the only person so far reporting this issue. Is this true for all of your toons or is it specific to just this single character? Perhaps try deleting that bar and re-creating it. The only other thing that I could think of is that it's German client specific

**Comment by brittyazel** [comment]
@nonamepaul can you open a new ticket for that? I want to keep this one specific to the OPs issue

**Comment by Solithe** [comment]
i have with all chars this problem. i try to delete my mainbar and greate a new one

**Comment by Solithe** [comment]
but it is strange that it works with older versions

**Comment by Solithe** [comment]
I do not know what exactly it was, but with a completely new profile it works again.
also with 1.0.6.

I am allowed to set all my char again. what a fun  =)

But Neuron is simply the best addon

**Comment by brittyazel** [comment]
This is so weird! Haha I'm not sure what the issue is, still. Nothing changed from 1.0.1 to 1.0.2 with keybinds, which is also why it's so confising

**Comment by brittyazel** [comment]
I'm really sorry for the trouble!

**Comment by Solithe** [comment]
No Problem =)
