### ISSUE TITLE
Disable hunter pet bar during Tortollan mini-games

### ISSUE THREAD

**Issue by maldoom** [brittyazel/Neuron#267]
Is it possible to disable the hunter pet bar, or bars in general, when entering a Tortollan mini-game?  I've been fiddling with the action states but none of the ones I have tried so far seem to do the trick.  Perhaps I'm missing something?

Thanks for all your work on this!

**Comment by brittyazel** [comment]
Sadly there's no Tortollan mini game state in the game right now and I don't think there's an explicit Tortollan minigame event for me to hook a function on to make this possible :-/

Why do you specifically want the hunter pet bar removed?

**Comment by brittyazel** [comment]
Can't fix due to in game restrictions. This may change in the future
