### ISSUE TITLE
Rep bar auto still isn't always switching

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#268]
It's been good for a while but I was doing some Armies of the Legionfall quests, it switched to AotL appropriately.  Afterward I did a few Nightfallen quests but it stayed on AotL.  I manually switched it to The Nightfallen, then put it back to Auto and it swapped back to AotL.

**Comment by brittyazel** [comment]
Strange this shouldn't be the case, I thought I fixed this once and for all

**Comment by brittyazel** [comment]
I still can't replicate this, it always works for me. Is the issue only for old reps? All of my testing us with normal bfa daily quests, so maybe it's past expansion reps that are the issue

**Comment by brittyazel** [comment]
This is working properly for me, so I'm closing it. Feel free to reopen if it happens again
