### ISSUE TITLE
bar switch delay from stealthmode to combatmode

### ISSUE THREAD

**Issue by Solithe** [brittyazel/Neuron#270]
When I attack with my rogue from the stealth, my bar always needs 2,5 seconds to switch from the stealth bar to the combat bar.

I do not know what to do

**Comment by brittyazel** [comment]
I'll look into it

**Comment by Solithe** [comment]
https://drive.google.com/open?id=1gwwx9meXCVOB6oPxjvZ5KRjf33Jbs70U

https://drive.google.com/file/d/12S__EaM6DHgboXd-W7f2BdIErZKqX7Fm/view

https://drive.google.com/file/d/1mpPYL_gN4yn70710sjuU97OTWohF2Zln/view

**Comment by brittyazel** [comment]
Questions:
1) Is this new behavior, or did it just recently start and when?
2)It looked like you could still attack after switching, so is it just the icons are taking a while to update but the abilities still work? This will help me narrow down possible solutions

**Comment by Solithe** [comment]
1.  I dont know. i want to start to lvl my rouge alt today.
2.  the attacks u see is autohit
3. no druid rdy atm sry

But I have this issue only when i attack something. out of combat is worls instant.

 if I make the ui completely new, its the same

**Comment by brittyazel** [comment]
Ok I got this fixed. Try with 1.0.7e that I just released just now

**Comment by Solithe** [comment]
works 

ty bro
