### ISSUE TITLE
GCD and timers in general are back to a broken state

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#271]
The main issue is that the GCD sweep is gone, there isn't really any visual "feedback" that a button has been pushed.  We seem to be mostly back to how things were before all of the recent fixes were implemented.  I think there are other things going on but the GCD one is overriding anything else for me.  I'm going to be reverting versions to d once I've finished submitting some reports.

**Comment by brittyazel** [comment]
Ok, I made a couple quick changes to layers yesterday that probably caused the issue. I though it was working ok, but I guess I didn't take as hard of a look as everyone else. The good news is that it's a simple fix to make, I just need to find the correct balance of frame levels and overlapping elements

**Comment by raysmith59** [comment]
That's very good news.  :)
