### ISSUE TITLE
Button icons aren't changing dynamically based on target conditions

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#274]
My healing toons tend to have dual-purpose buttons along the lines of:

/cast [harm] Solar Wrath(); Rejuvenation()

Idea being if a hostile is targeted, the Solar Wrath will show and will be cast if used, otherwise Rejuvenation will show and be cast when used.

At some point this stopped happening.  In testing just now the icon is changing but only when the button is pushed, it isn't changing on target or change/loss of target.

There may be other conditional issues but this is the only one I use regularly and the only one I've noticed.

**Comment by brittyazel** [comment]
Can you test this fix in MASTER and let me know if it fixes it?

**Comment by raysmith59** [comment]
Looks good.
