### ISSUE TITLE
GUI : Homestate & Preset state, translation problem

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#28]
Hi,

It has just strike me, but in the GUI, State Bar tab, the homestate and preset state are not localized. Just the "Stealth" one for rogue.
Maybe you could add a value in the Neuron_state.lua file for the "MANAGED_ACTION_STATES" including the localized string and use them when needed (I successfully done that for the Homestates on my local copy, but since the preset used a table.sort... I can't figure out how to do it right... Working with no sorting is working, but it's not neat...)

Regards

**Comment by brittyazel** [comment]
I can handle this, it shouldn't take too long

**Comment by brittyazel** [comment]
Alright I fixed it. There you go

**Comment by brittyazel** [comment]
Just for my curiosity. Can you send me a screenshot of the GUI in french so I can see what it looks like?

**Comment by SirLagardere** [comment]
Thanks for your fix :D 
And here are the screenshots in french ;) 
![image](https://user-images.githubusercontent.com/20615278/34576496-5de4f5dc-f17e-11e7-8bf4-f9d5ba3fc954.png)
![image](https://user-images.githubusercontent.com/20615278/34576522-76a2b05a-f17e-11e7-833a-ddb92e52908c.png)
and
![image](https://user-images.githubusercontent.com/20615278/34576559-897a981e-f17e-11e7-9d79-1a6442e2cac7.png)

There is two things that could be enhanced (but it's not a priority) : 
- Bottom of the first 2 screenshots you'll find "Action Button Compteur". In french, it shoud be "Nombre de bouton d'action", but only "Count" is available in the localization. If we could get "Action Button Count" it'll be better
- Preset State are sort by the english strings, IE Alt, Combat, Ctrl, etc... and are printed localized so, in french you'll got "Alt, En combat, Ctrl, etc..." it should have been "Alt, Camouflage, Ctrl, etc..."

By the end, I steel need some polish here and there, but it's really good loocking and very "french aware" (from my point ^^)

**Comment by brittyazel** [comment]
I can fix that first one sure.

And I sorted by the english strings on purpose so that way the order wouldn't change from locale to locale, but I can change that to sort by locale as well. I just also wasn't sure how sorting works with regards to non-latin alphabets, i.e. Cyrillic or Chinese

**Comment by SirLagardere** [comment]
ohh yes very true for the last one, I never though of theses alphabets...
I hope you find the french GUI not to clutered :D

**Comment by brittyazel** [comment]
Ok I made the changes, and I changed those 8 strings as well. You're going to have to re-translate those 8
