### ISSUE TITLE
Call Pet flyout not opening recently; Pet Utility flyout working correctly

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#282]
I've been using the same pet for the past few weeks so I'm not sure exactly when this started but all of a sudden my Call Pet flyout (dragged straight from the spell book) no longer opens with right-click after I relog, works fine when first dragged.  My Pet Utility flyout is still working correctly.

Here's the code for the two buttons if it helps, I don't see anything obviously wrong:

						{
							{
								["homestate"] = {
									["macro_Text"] = "#showtooltip Call Pet 1()\n/cast [nobtn:2] Call Pet 1()\n/stopmacro [nobtn:2]\n/flyout blizz:9:l:b:t:1:c",
								},
							}, -- [1]
							["config"] = {
								["date"] = "03/20/19 14:25:40",
							},
						}, -- [1]

						{
							{
								["homestate"] = {
									["macro_Text"] = "#showtooltip Dismiss Pet()\n/cast [nobtn:2] Dismiss Pet()\n/stopmacro [nobtn:2]\n/flyout blizz:103:l:b:t:1:c",
								},
							}, -- [1]
							["config"] = {
								["date"] = "03/20/19 14:25:40",
							},
						}, -- [2]

**Comment by brittyazel** [comment]
Can you check with the latest MASTER? I've done a lot of work on the Flyout and Pet code, so maybe I accidentally fixed it

**Comment by raysmith59** [comment]
No change for the call pet flyout and master caused a bunch of my bars to reset to the centre of my screen (XP, rep, extra action, zone, etc) so that'll need some more work before it goes live.

**Comment by brittyazel** [comment]
Umm that bizarre. None of my bars on any of my toons are having issue, and my call pet flyout works great...so I dunno

**Comment by raysmith59** [comment]
As of the latest release (?) is seems to be working again.

**Comment by brittyazel** [comment]
Yep I added a special condition for this ability. I don't know why but this specific ability needs a slight delay before we update the flyout after loading
