### ISSUE TITLE
Additional Actionbar keybind issue

### ISSUE THREAD

**Issue by gylva** [brittyazel/Neuron#285]
So the regular action bar 1-12 keybinds work as they should. But I cannot bind any keys to new action bars neuron adds. For example Action Bar 2, 3, 4 ect. Going into the game settings to change keybinds for additional action bars does nothing to affect the neuron bars. Where do you set the key binds for the new action bars?

Thank you in advance.

**Comment by brittyazel** [comment]
Did you figure out the keybinding mode? You just shift+left click to enable mouseover keybinding

**Comment by gylva** [comment]
> 
> 
> Did you figure out the keybinding mode? You just shift+left click to enable mouseover keybinding

Yes, I did and I feel stupid for not having found the keybinding options sooner. Sorry about that. Can I delete this issue? It's already closed

**Comment by brittyazel** [comment]
You're fine, closed is basically deleted. I just wanted to make sure you were good lol
