### ISSUE TITLE
0.9.13 : Visibility states trouble

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#29]
Hi,
I've just encounter a bug on bar's visibility states. It seems only applied after a reload of the UI.
I was testing the "out of combat" trigger.
Regards

**Comment by brittyazel** [comment]
Can you be more specific? What troubles are you experiencing, and if you have a LUA error can you post it?

**Comment by brittyazel** [comment]
Is this for just that one state, or do all need a reload first?

**Comment by SirLagardere** [comment]
So, I've just made few more tests. Seems to only be for the "in combat" "out of combat" state. As soon as I add another state like "Alt up" or "Alt down", if I press the Alt key, the visible states are updated as intended, then I can switch bak the "Alt" state to keep my out/in combat and it works.
No lua error is thrown, it just feels like a missing event to refresh the visibility state list of the bar.
My bars only use at this time these triggers (in combat / out of combat), everything else is checked.

**Comment by brittyazel** [comment]
Ok I'll look into it. Thanks for reporting

**Comment by ylixir** [comment]
we've added an "apply" button that reloads the ui when the visibility states are updated which should work around this issue

we should reduce our reliance on reloads, but i view this as something that is better approached through architectural changes than through whack a mole bug fixes.
