### ISSUE TITLE
Travel Form button is no longer working

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#290]
I have no idea where this came from but as of yesterday my druid's Travel Form hotkey no longer does anything, even after removing and re-adding the button.  It was working fine until yesterday and I'm not aware of anything that's changed since it was working.  It works when used out of the spell book and the content of the macro matches what the "buff" text indicates.

**Comment by raysmith59** [comment]
It's working again after a relog but relogging didn't help earlier before I put in the bug.  Zero clue what's going on.

**Comment by brittyazel** [comment]
Yeah this is a blizzard bug unfortunately. Sometimes "/cast Travel Form()" will work, and other times "/cast Travel Form(shapeshift)" will work. I can't figure out a pattern to when the first fail, but like you said it usually take a relog to fix. The second macro always seems to work though, so I edited my macro to add the shapeshift parameter. Note this is also the case for bear form, though weirdly not cat form

**Comment by raysmith59** [comment]
It's been a while since this happened so I'm going to close this off, if it comes back I'll re-open it later.
