### ISSUE TITLE
Keybind and Spellstacks behind the Button

### ISSUE THREAD

**Issue by Solithe** [brittyazel/Neuron#291]
With 1.1 the Keybind and Spellstacks number´s behind the Button

https://drive.google.com/open?id=1HWTUovlPsfUU6gRNgsGbQONV1xhsoaDA

**Comment by brittyazel** [comment]
Huh, odd. I'll get that fixed asap. Not sure why that happened.... I didn't see it because I'm using Masque and it wasn't an issue there

**Comment by brittyazel** [comment]
![WoWScrnShot_040319_112613](https://user-images.githubusercontent.com/3747347/55503396-6885ca80-5603-11e9-9387-f555093958d3.jpg)

Strange, I don't have the issue that you're seeing

**Comment by brittyazel** [comment]
![WoWScrnShot_040319_113117](https://user-images.githubusercontent.com/3747347/55503713-1a24fb80-5604-11e9-8f57-928fc6f0079e.jpg)

Hrm...it's not just hunters either. My hunter doesn't have the issue

**Comment by brittyazel** [comment]
Can you try MASTER and see if the numbers come back for you?

**Comment by Solithe** [comment]
it works. ty
