### ISSUE TITLE
Action Bars

### ISSUE THREAD

**Issue by PapaBear93** [brittyazel/Neuron#292]
First time using the addon but there seems to be an issue with bars and certain buttons resetting position when I reload the UI or restart the game.

**Comment by brittyazel** [comment]
Is this repeatedly happening? I'm not experiencing this on my end

**Comment by brittyazel** [comment]
Also, where are they resetting to? The default position?

**Comment by PapaBear93** [comment]
If I reload it happens about 90% and yes to default.

**Comment by brittyazel** [comment]
Hrm. I can't replicate this no matter what I do. Are you using the English client? Is there anything unique about your setup?

**Comment by PapaBear93** [comment]
Yes the English client and no not at all really. Most things are default. It seems to be mostly the Pet Bar, Extra Action, Zone Action, and Vehicle Exit.

**Comment by brittyazel** [comment]
Do action bars reset at all?

**Comment by brittyazel** [comment]
Also, is there any LUA error?

**Comment by PapaBear93** [comment]
No LUAs and the only time the Action Bars reset is when I reduce their scale size and don't move them after. I would have to re-snap them where I wanted them to be,

**Comment by brittyazel** [comment]
Hrm odd. Well I'll get this ironed out asap once I can figure out what he heck is happening. Sorry about the glitch. Feel free to roll back to the previous release

**Comment by PapaBear93** [comment]
All good thank you for the support though it's great!

**Comment by brittyazel** [comment]
Can you check with the latest version in MASTER has this issue? You will have to download it manually, rename the folder to Neuron, and drop it in the addons folder.

**Comment by raysmith59** [comment]
This sounds like the issue with the previous master that I mentioned where the misc bars (XP, rep, extra action, etc) all reset to the centre of the screen when I used it as well as the latest release version (I reverted from the release since I don't want to have to move buttons on all my toons if a subsequent release fixes it).  I didn't have that issue with action bars, though, except the pet bar.

![image](https://user-images.githubusercontent.com/2917594/55515784-70f8f800-5639-11e9-97fd-744d1a641c55.png)

I'll check master as well.

**Comment by raysmith59** [comment]
No change in master, same as the screenshot above.

When I revert back to 1.0.11 they're still positioned correctly so I think the profiles have the correct location info saved, it just isn't being handled properly when the game loads in the most recent version:

![image](https://user-images.githubusercontent.com/2917594/55516044-2deb5480-563a-11e9-8e58-2fb74d937fef.png)

**Comment by brittyazel** [comment]
Hmm ok, so they're not moving to the default position, but rather to the middle. (I believe you said that before in a different ticket). That's useful information as I was looking in the wrong location thinking they were going going to the default spots.

So my thoughts are this could be a database issue, i.e. the database isn't loaded by the time we try to create the bars, but that seems unlikely. I'm mostly just annoyed that I can't replicate this so I'm just reading through my code looking for stuff blindly.

Cool I'll keep looking at it

**Comment by brittyazel** [comment]
What CPU do you guys have? I'm wondering if I'm calling Load() too fast after creating the bar and I should throttle it a bit. Causality should protect us here, but I've been burned before

**Comment by brittyazel** [comment]
Ok I'm pretty sure I fixed it. I'm putting out a new release with a few other fixes as well.
