### ISSUE TITLE
Override / Possess / Vehicle bars won't show up unless ALL visibility options are checked.

### ISSUE THREAD

**Issue by Sylar-Hao** [brittyazel/Neuron#294]
O/P/V dedicated bars won't show up unless ALL visibility options are checked, meaning it will be either always up or never up. 

If any visibitiy option is unchecked it won't show up, not even if you're under an O/P/V state.

**Comment by ylixir** [comment]
i just disabled override and posses and hopped on a vehicle in the argent tournament grounds and the vehicle bar showed up fine. this seems to have been fixed since this issue was opened
