### ISSUE TITLE
Flickering Button Using Cooldown Transparency

### ISSUE THREAD

**Issue by Hardbunny** [brittyazel/Neuron#295]
Example of the issue:

https://giant.gfycat.com/PhonySlimAsiantrumpetfish.webm

Tested with every addon turned off
Tested with most settings turned off.  Having the same result

**Comment by brittyazel** [comment]
Did this just start happening? I can get this fixed asap

**Comment by Hardbunny** [comment]
I can try rolling back to an older version, just tested the addon for the first time today so I'm not sure.

**Comment by brittyazel** [comment]
No prob, I'll fix this when I get home and will spin out a new release

**Comment by brittyazel** [comment]
fixed. new release coming out now
