### ISSUE TITLE
Keybind priority broke in latest version

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#297]
Works correctly in 1.1.5, I've had to revert back to that version for now.

As of the latest version my priority keybinds are no longer priority, this has happened before but I can't find a previous issue exactly on point so creating a new one.

Scenario:
Action Bar 1 has keybinds
Action Bar 3 has the same keybinds, set as priority
Action Bar 3 has Show Grid disabled and is set for override/vehicle/etc
Start a vehicle quest, note that keybinds are activating Action Bar 1 rather than the priority keybinds on Action Bar 3

**Comment by brittyazel** [comment]
I'll look at it. Whoops.
