### ISSUE TITLE
Resto Shaman : Healing Surge / Cast bar issues

### ISSUE THREAD

**Issue by teh-fixerer** [brittyazel/Neuron#298]
Just recently started playing resto shaman again.  Using Neuron 1.1.6c, and not really sure when this problem crept in.

In Resto spec, I am finding that the healing surge spell (@ level 120) seems to be taking the spell tool tip from Enhancement.  (Elemental seems to use the proper one).  I checked to see if this was a similar situation as some of the other spell-macro conversion problems but the usual methods don't seem to fix the issue.

Also in a heavy healing encounter when you are trying to spam healing surge, I found that the neuron cast bar says that the cast has failed, even though my character completes the cast in-game.  Somewhat confusing spell feedback in these situations. 

(edit) I found that the standard blizzard UI interaction between spell cast and cast bar functions as expected

Not really an unplayable situation but hopefully the problem can be solved.

**Comment by brittyazel** [comment]
Hrm interesting. This is the second report so far about using the wrong tooltip. I'll check it again. The spell naming gets really wonky these days, with many different versions for spell all having the same name. It might be more safe to look up the tooltip info with the spellid rather than the name.

I'll see if I can replicate the cast bar issue on my druid. Sadly I don't have a shaman.

**Comment by teh-fixerer** [comment]
For what it is worth I haven't had this issue on any other healer class yet.  Is there anything I can help with as far as providing more info?  
A long time ago on the ion version before you took over the project there was a bug with spell push back. but not sure if the eventual fix it is related to this.
    On Saturday, June 1, 2019, 11:37:40 a.m. CST, Britt Yazel <notifications@github.com> wrote:  
 
 
Hrm interesting. This is the second report so far about using the wrong tooltip. I'll check it again. The spell naming gets really wonky these days, with many different versions for spell all having the same name. It might be more safe to look up the tooltip info with the spellid rather than the name.

I'll see if I can replicate the cast bar issue on my druid. Sadly I don't have a shaman.

**Comment by teh-fixerer** [comment]
EDIT
I found that the cast bar issue isn't limited to shaman.  An easy way to reproduce this is click on a button set up with your hearthstone and then click it again before it finishes the cast.  The "spell failed" will show up in the neuron cast bar, yet it actually keeps being cast in-game.

**Comment by brittyazel** [comment]
Cool, now I can replicate it and fix it! Awesome, good find

**Comment by WhisperWindE** [comment]
能不能设置  宏名称 /按键名称  文本的大小及字体 颜色
can i edit  macro/button text   font/color/size/position

**Comment by brittyazel** [comment]
Please open this question on another issue, lets keep this issue closed.
