### ISSUE TITLE
Lua error when trying to delete bar

### ISSUE THREAD

**Issue by teh-fixerer** [brittyazel/Neuron#299]
Using 1.1.6c 

Neuron doesn't seem to want to delete action bars.  (Apologies I don't have a bug grabber so copy/pasting from game)

Message: Interface\AddOns\Neuron\Objects/KEYBINDER.lua:163: attempt to call method 'gsub' (a nil value)
Time: Sun Jun  9 06:30:49 2019
Count: 1
Stack: Interface\AddOns\Neuron\Objects/KEYBINDER.lua:163: attempt to call method 'gsub' (a nil value)
Interface\AddOns\Neuron\Objects/KEYBINDER.lua:163: in function `ClearBindings'
Interface\AddOns\Neuron\Objects/BAR.lua:307: in function `RemoveObjectsFromBar'
Interface\AddOns\Neuron\Objects/BAR.lua:209: in function `DeleteBar'
Interface\AddOns\Neuron\Neuron-GUI.lua:1280: in function `BarEditor_ConfirmYes'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: self = <table> {
 OnEnter = <function> defined @Interface\AddOns\Neuron\Objects/KEYBINDER.lua:300
 ProcessBinding = <function> defined @Interface\AddOns\Neuron\Objects/KEYBINDER.lua:216
 CancelTimer = <function> defined @Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:147
 OnKeyDown = <function> defined @Interface\AddOns\Neuron\Objects/KEYBINDER.lua:391
 TimeLeft = <function> defined @Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:172
 new = <function> defined @Interface\AddOns\Neuron\Objects/KEYBINDER.lua:39
 OnShow = <function> defined @Interface\AddOns\Neuron\Objects/KEYBINDER.lua:263
 CancelAllTimers = <function> defined @Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:160
 OnHide = <function> defined @Interface\AddOns\Neuron\Objects/KEYBINDER.lua:294
 OnMouseWheel = <function> defined @Interface\AddOns\Neuron\Objects/KEYBINDER.lua:408
 ClearBindings = <function> defined @Interface\AddOns\Neuron\Objects/KEYBINDER.lua:159
 OnClick = <function> defined @Interface\AddOns\Neuron\Objects/KEYBINDER.lua:343
 GetKeyText = <function> defined @Interface\AddOns\Neuron\Objects/KEYBINDER.lua:121
 ApplyBindings = <function> defined @Interface\AddOns\Neuron\Objects/KEYBINDER.lua:181
 GetBindkeyList = <function> defined @Interface\AddOns\Neuron\Objects/KEYBINDER.lua:102
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:129
 ScheduleTimer = <function> defined @Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:94
 OnLeave = <function> defined @Interface\AddOns\Neuron\Objects/KEYBINDER.lua:336
}
key = NeuronActionBar3_ActionButton8 {
 macroname = NeuronActionBar3_ActionButton8MacroName {
 }
 shine5 = NeuronActionBar3_ActionButton8Shine5 {
 }
 flyoutborder = NeuronActionBar3_ActionButton8FlyoutBorder {
 }
 auraText = false
 class = "ActionBar"
 flyoutright = NeuronActionBar3_ActionButton8FlyoutRight {
 }
 shine12 = NeuronActionBar3_ActionButton8Shine12 {
 }
 shine11 = NeuronActionBar3_ActionButton8Shine11 {
 }
 shine16 = NeuronActionBar3_ActionButton8Shine16 {
 }
 iconframechargecooldown = NeuronActionBar3_ActionButton8IconFrameChargeCooldown {
 }
 bindColor = "1;1;1;1"
 spellGlowDef = true
 gloss = NeuronActionBar3_ActionButton8Gloss {
 }
 count = NeuronActionBar3_ActionButton8Count {
 }
 macroText = true
 multiSpec = false
 bar = NeuronActionBar3 {
 }
 flyoutbordershadow = NeuronActionBar3_ActionButton8FlyoutBorderShadow {
 }
 auracolor1 = <table> {
 }
 macroColor = "1;1;1;1"
 shine13 = NeuronActionBar3_ActionButton8Shine13 {
 }
 rangeInd = true
 iconframechargecooldowntimer = NeuronActionBar3_ActionButton8IconFrameChargeCooldownTimer {
 }
 cdcolor2 = <table> {
 }
 objType = "ACTIONBUTTON"
 countText = true
 debuffcolor = <table> {
 }
 normaltexture = NeuronActionBar3_ActionButton8NormalTexture {
 }
 upClicks = true
 data = <table> {
 }
 shine3 = NeuronActionBar3_ActionButton8Shine3 {
 }
 rangecolor = <table> {
 }
 shine8 = NeuronActionBar3_ActionButton8Shine8 {
 }
 shine6 = NeuronActionBar3_ActionButton8Shine6 {
 }
 showGrid = true
 FlyoutArrow = NeuronActionBar3_ActionButton8FlyoutArrow {
 }
 hotkey = NeuronActionBar3_ActionButton8HotKey {
 }
 FlyoutBorderShadow = NeuronActionBar3_ActionButton8FlyoutBorderShadow {
 }
 rangeTimer = <table> {
 }
 shine15 = NeuronActionBar3_ActionButton8Shine15 {
 }
 cdAlpha = 1
 shine

**Comment by brittyazel** [comment]
Yeah I saw this as well. This is already fixed on my NeuronNext branch. Maybe I can backport it over to the stable series
