### ISSUE TITLE
0.9.13a : Issue with the rep tracking

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#30]
Hi,
Me again...With the last update, I've got some trouble with the "auto select" for the faction tracking. Even with rep gain, nothing change.
Another thing is that every faction is tagged "Reward"
![image](https://user-images.githubusercontent.com/20615278/34685594-2a5a99b4-f4a9-11e7-9ba1-95067959fa87.png)

**Comment by brittyazel** [comment]
Bleh, yep that's my bad. I made a change for testing that I forgot to put back. I'll get a fix rolled out in about an hour

**Comment by brittyazel** [comment]
Fixed is 0.9.13b
