### ISSUE TITLE
can't drag pet bar spells onto pet bar

### ISSUE THREAD

**Issue by teh-fixerer** [brittyazel/Neuron#300]
Using 1.1.16c

Odd problem on a 110 boosted hunter where he can't drag any pet spells onto the pet bar.
My main hunter on a different server seems to have no issue?

Tried re-setting to default profile, still did not work.  Also tried copying profile from other hunter and functionality still not working.

Could it be a blizzard side problem?

(edit)
after deleting WTF, cache and Interface folders, I can now work with pet bar.
Not sure if you still want to have a look at it, but this is an ok work around for me for the time being.

**Comment by teh-fixerer** [comment]
so what happened is my boosted character had another action bar addon enabled to load.  Somehow it was interfering with neuron so i deleted the addon out of my folder and all is well again.  Closing ticket.

**Comment by brittyazel** [comment]
Haha good to know. Which add-on was it just so I know?

**Comment by teh-fixerer** [comment]
one called magnet buttons
