### ISSUE TITLE
No bars, error.

### ISSUE THREAD

**Issue by 40P3** [brittyazel/Neuron#303]
Neuron\Objects/PETBTN.lua:60: Usage: GetPetActionInfo(index)
[C]: in function `GetPetActionInfo'
Neuron\Objects/PETBTN.lua:60: in function `HasPetAction'
Neuron\Objects/PETBTN.lua:387: in function `SetObjectVisibility'
Neuron\Objects/BUTTON.lua:233: in function `SetCooldownTimer'
Neuron\Objects/BUTTON.lua:640: in function `UpdateCooldown'
Neuron\Objects/BUTTON.lua:837: in function `UpdateTimers'
Neuron\Objects/BUTTON.lua:466: in function `SetData'
Neuron\Objects/BAR.lua:1193: in function `LoadObjects'
Neuron\Objects/BAR.lua:2976: in function `Load'
Neuron\Neuron-1.1.7.lua:227: in function <Neuron\Neuron.lua:186>
(tail call): ?
[C]: ?
...
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Accountant\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
Accountant\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:450: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:493: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:1212: in function <FrameXML\UIParent.lua:1108>
[C]: ?

**Comment by brittyazel** [comment]
On all toons or just one? I can add in a safety check for this. You're the
first one to report this so far

**Comment by brittyazel** [comment]
That should fix it!

**Comment by 40P3** [comment]
Hi, sorry for not getting back earlier. Your fix fixed the issue, thank god I thought I had to recreate every toon's bar from scratch!
Many thanks!
