### ISSUE TITLE
Returning player with a question

### ISSUE THREAD

**Issue by Sifuedition** [brittyazel/Neuron#304]
Used this addon when it was Macaroon. By default, it would remember bar positions by spec. I can't seem to find a way for it to do that now. I would like my bar positions different on healers, but changing character spec doesn't seem to affect my neuron bar spec.

Does this need to be done manually now?

**Comment by brittyazel** [comment]
I don't remember a time since I have been in charge of the code where this was an option. It must have been retired before my time as maintainer. It's possible I can add it in going forward, but it won't be for a while that I have time to add it back in. For now, the specs just change the button contents, not the bars themselves.

**Comment by Sifuedition** [comment]
It's possible I am remembering back when it was Ion, even before Macaroon.
So, if I want my bars to be in a different position on the screen when I am in a healing spec...
I can make a healer profile and manually change it when I change spec.
Hiding a bar that only shows in that spec won't work because the keybinds can't be shared between the bars, right?

**Comment by brittyazel** [comment]
You can always load up a different profile, yes.

To answer your other question about sharing keybinds, its a bit messy but
you can set keybinds on oene bar, and then lock them. The keybinds won't
come unlocked then when you bind them to a different bar. I'm not sure how
it would play having certain bars for certain specs. I'd be interested for
you to let me know though

**Comment by Sifuedition** [comment]
Do you have a place for feature requests?
Also, thank you very much for your interactions here to help.

**Comment by brittyazel** [comment]
I'm happy to take feature requests her just please label it as such in the
title, I.e. [feature request]

Just a heads up, I'm rewriting the whole GUI, so that's my priority right
now. Feature requests may take me some time, no promises 😋

**Comment by AlexFolland** [comment]
Yes, it was possible in Macaroon because Macaroon had profiles per spec, but not in Ion.

**Comment by brittyazel** [comment]
Good to know. There's already an issue open requesting profiles per spec, so future discussion should take place there #73
