### ISSUE TITLE
Please help with Neuron (addon) Issues

### ISSUE THREAD

**Issue by Darkohl** [brittyazel/Neuron#307]
First, sorry if I already sent this in, but as I was finishing sending it in the first time, I clicked a button that apparently "closed" the issue.  I don't know what that did, so just to be safe, I'm resending what I wrote.  Sorry if there ends up being a duplicate.  

Ok, so I've been using Bartender for years not but it always bothered me that I couldn't go over the four bar limit.  So I started adding Button Forge, which at first was really nice, but now that it has aged out of the current, 8.2.whatever release, it is starting to have problems that I cannot deal with, such as being unable to remove bars that I no longer use.  So I am taking time, and it has been half a week at this point, to set up Neuron.  One problem I have run into is that somehow, without even knowing what I did, my Reputation Status bar is the only remaining status bar.  I did have another for azerite leveling, but, yes, somehow that vanished.  I've tried making new status bars to use as replacement azerite leveling bars or even a second rep bar, but when I create them, they are short, stubby little frakers that I cannot seem to first, elongate like the existing rep bar, nor second, get them to display anything, let alone the azerite level info or possibly a second rep bar.  My frustration is at the boiling point and liquid stuff of some substance is spilling over the edge.  I really don't want to go back to the regular Bartender and Button Forge(outdated) combo.  Is there any direction you can point me in?  I tried looking at the files that were in the Neuron folder but due to my poor lack of knowledge on programming addons, I wasn't able to figure much out.  Sorry, I tend to type more then I should.

Please send in the cavalry.
Andy

P.S.  Anything you can help me with would be most appreciated.

**Comment by brittyazel** [comment]
When you create a new status bar, it doesn't yet have a type, i.e. XP, Rep, Cast, or Mirror. If you go into the button edit mode (right click the minimap icon) and then right click on a bar, a window should pop up with a whole array of customization options

Missing this setting panel isn't your faultz and it has been fixed in what will be an upcoming release. But for now, it requires this button-edit mode step. (the status bars are just fancy buttons 😋)

**Comment by brittyazel** [comment]
Did that help?

**Comment by Darkohl** [comment]
Wonderfully.  Thank you so much.  Its taken me a while to get everything set up, but now that most of it is up and going, I'm loving it.
Thank you!Andy/Darkohl-Staghelm


The rich would have to eat money if the poor did not provide food. -Russian Proverb 

    On Monday, July 29, 2019, 7:16:29 PM CDT, Britt Yazel <notifications@github.com> wrote:  
 
 
Did that help?
