### ISSUE TITLE
Neuron Request 1. Unclamp Neuron Menu option

### ISSUE THREAD

**Issue by jlspeeddragon** [brittyazel/Neuron#308]

**Comment by jlspeeddragon** [comment]
Allow the neuron config menu to move beyond edge of screen (unclamped). It blocks the view when trying to adjust and or fine tune any bars and buttons without having to constantly close and reopen it..

As I also stated, If this is something that I can do from my end until Implemented into Neuron, and would be considered not to difficult task. What would I need to change and or add to make it happen?

**Comment by brittyazel** [comment]
So this my be implicitly fixed in our Neuron-Next branch, which is a full rewrite of all GUI components (and like 40% of the the rest of the addon as well). The Nuron-Next branch is only about 50% implemented, and can only do bar configuration (button configuration is still a WiP). If you like though, you can test this branch and report back if the new config window does what you'd like it to

**Comment by jlspeeddragon** [comment]
maybe I didn't phrase this quite correctly or I'm not quite sure if we are both thinking the same menu thing.. 
So simplified..
your minimap button - Shift+Right click option.. that overall menu screen.. that one..
basically that menu screen is coded to not allow the borders of it to go beyond the edge of the screen, Therefore it is pretty much clamped within the overall border of the game screen.

I am just starting to learn the coding and steadily getting it.. However,
I believe it is tied to this line of .LUA along with overall code that assigns the overall size and edges of that screen..

MenuFrame:SetWidth(400);
MenuFrame:SetHeight(480);
MenuFrame:SetBackdrop({ bgFile = "Interface\\Tooltips\\UI-Tooltip-Background", edgeFile = "Interface\\Tooltips\\UI-Tooltip-Border", tile = true, tileSize = 8, edgeSize = 12, insets = { left = 2, right = 2, top = 2, bottom = 2 } });
MenuFrame:SetBackdropColor(0.1,0.1,0.2,1);
MenuFrame:SetBackdropBorderColor(0.1,0.1,0.1,1);
MenuFrame:SetMovable(1);
MenuFrame:EnableMouse(1);
MenuFrame:SetToplevel(1);
MenuFrame:SetClampedToScreen(1);
MenuFrame:SetPoint("CENTER");
MenuFrame:Hide();

This is the sourcelecode from my addon CABSkin menu screen which I am able to move and drag anywhere on the screen and almost off the screen... I do not want to pry into your coding and make any changes without your permission. Hopefully sharing this info might allow you to compare with your coding and find the requested option and save you some coding time. :)
