### ISSUE TITLE
/neuron bind

### ISSUE THREAD

**Issue by Arlennis** [brittyazel/Neuron#31]
after two update's /neuron bind stop workink so i can't bind any key anymore. Is there any solution?

**Comment by SirLagardere** [comment]
If you're on a french client, the shortcut has been translated (/neuron associer)
You could call /neuron to list what was localized or not :)

**Comment by Arlennis** [comment]
english localization

**Comment by brittyazel** [comment]
you can alt+click or shift+click (one of the two) the minimap icon to enter bind mode. You can enter any mode from the minimap icon.

I'll work on getting the slash command fixed

**Comment by Arlennis** [comment]
that work thx )

**Comment by brittyazel** [comment]
"/neuron bind" works perfectly for me. Is there a chance you were using a capital 'B' in Bind? Either way, I changed it so that it doesn't matter if you capitalize or not
