### ISSUE TITLE
Charges not showing

### ISSUE THREAD

**Issue by TruthNZ** [brittyazel/Neuron#310]
Just upgraded to Neuron 1.2.0 and not getting any spell charges showing anymore.

(Is otherwise very smooth and responsive)

**Comment by TruthNZ** [comment]
Ooh, add to that no keybinds are visible anymore (shows how much I've gotten used to them and didn't notice they were missing).

**Comment by brittyazel** [comment]
Yeah I screwed up. I pulled that version for the time being, go ahead and revert to 1.1.7b for now.

**Comment by brittyazel** [comment]
fixed
