### ISSUE TITLE
Hidden grid shows when attempting to drag locked action buttons

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#312]
Hide the grid and lock the action buttons, then try dragging a button, the grid will show (all bars, not just the current one).  Cosmetic annoyance but happens to be me more often than it probably should just from normal gameplay where I'm not intending to drag.

**Comment by brittyazel** [comment]
Is this still the case? Sorry I'm going through my bug backlog

**Comment by raysmith59** [comment]
Still happening, yeah.

**Comment by raysmith59** [comment]
Personal request, this has become a high priority issue for me (and probably only for me) due to my specific setup with the second set of priority hotkeys that should only be enabled during vehicle-type events.  When this issue happens (I hit a potion with 1.5s left on the countdown timer but drag it slightly rather than clean clicking) the buttons go into that "show grid" mode which has a side effect of the separate issue I've reported where those priority hotkeys become active even though there aren't any actions on them.  That means I'm stick in click mode for the duration of the fight, I can't use hotkeys.  This happens maybe one pull in 20 so while it isn't constant, it happens at least once most raid nights.

I think technically the fixing of either of the two issues (this one, or the one where the priority hotkeys are enabled simply due to grid being shown) should avoid the issues I'm experiencing but of the two this one is the more annoying to me and would be my preference for a fix if I'm stuck picking one of the two.

**Comment by brittyazel** [comment]
I'll try to get a fix in for this early next week. Sorry swamped at work

**Comment by raysmith59** [comment]
I think this remains my only high priority item, it happened again this week during a +15 key going into the last boss and I had to click-cast on the last boss of SoB... did about 30K less dps and may have cost us the key.  As I mention above, there are actually two issues at play and I think fixing either of the two will make it low priority again, I just figured the dragging while locked issue might be the easier of the two to figure out, probably just have to check for the locked button status earlier in the function before it actually starts to do the drag.

**Comment by brittyazel** [comment]
Alright I added some code to try to address this. Please let me know if it's working for you

**Comment by raysmith59** [comment]
Master, or have you pushed to release?

**Comment by raysmith59** [comment]
... god, I'm actually excited about this ... low bar, apparently.

**Comment by brittyazel** [comment]
It's in MASTER. Pending your confirmation that it's working I'll push a new release

**Comment by raysmith59** [comment]
Looks good in limited testing, thanks!

**Comment by raysmith59** [comment]
I'm going to hate myself for this...

I just noticed a side effect of this fix, while it addresses the original issue, it should only prevent dragging of existing action buttons that are protected by the locked bar setting.  As currently implemented, though, I can't drag spell book spells or essences to the bars, they never cause the grid to show and dragging down into the bar doesn't do anything.  I can manually enable the grid to allow dragging so this isn't a huge deal until it's fixed.

**Comment by brittyazel** [comment]
If the bar is locked, you presumably have a key that unlocks it. I.e. shift, alt, or Ctrl

The way I implemented it is that if you are holding down the modifier, the grid show show as per usual. Try holding down the modifier key while also dragging from the spellbook. It should show the grid fine if you do that

**Comment by AlexFolland** [comment]
It definitely should unlock without holding an extra key when dragging from somewhere else than the locked bar.

**Comment by brittyazel** [comment]
Problem is that these event does provide any information on "what" triggered it. We are hooking the "ACTIOBAR_SHOWGRID" and "ACTIONBAR_HIDEGRIDE" events for this, and multiple different things can trigger them. I'll give another stab at it to see if I can clean it up, but part of this also is coming down to what it 'means' to be locked.

One could interpret "locked" to mean no changes to the bar whatsoever, including dragging new things on as well as current things off. This is the interpretation that I currently coded into the UI, hence if you want to drag new things onto a locked bar you need to hold down the unlock-modifier.

I'm wondering if it is more or less conceptually consistent with "locked" to allow for dragging new things onto a locked bar. Do we restrict the new things to being just from the spellbook? Or should you be able to drag a button from an unlocked bar onto a locked bar?

**Comment by AlexFolland** [comment]
Macaroon and Ion let you drag onto locked bars, and let you lock bars per-bar.  We don't have to rely on a native UI event.  Macaroon has been about overcoming and avoiding the native UI code as much as possible, to bring a better experience.  Post-hooks can be used instead of events to know exact parameters.

**Comment by brittyazel** [comment]
Ok can either of you then please open up a new issue detailing specifically the behavior that you envision and what changes need to be made to the current version to get to that point? I'm happy to concede, I just want to make sure I'm actually making the changes you want so it's not a "two steps forward 1 step back" pattern we fall into

**Comment by raysmith59** [comment]
Frankly, I have no issue with your interpretation of a "locked bar" but that's not how it's worked historically so it probably makes sense to try to get it back to how it was.
