### ISSUE TITLE
Vehicle/Possess States Not Working

### ISSUE THREAD

**Issue by Pelargonia** [brittyazel/Neuron#313]
At first I thought it was just with the Tortollan "Circle of Life" daily where you are suppose to move the crab. The bar state changes to, I assume, vehicle but I have no buttons and the buttons that I am suppose to be able to push to move the crab do not work. Now it is also doing it with the Rustbolt "Nukem Norbert" quest, and the "Sticky Mess" world quest in Stormsong. The Bar state changes but no buttons. Maybe it does it in other vehicle or possess quests as well and I have just not found them yet. Reloading the UI does not fix it. I am using the English client 1.2.1

I have been able to access the vehicle buttons only if I enable the blizzard bar and reload but there (the Blizzard Bar) the button numbers do not work. It says they are numbered but pressing the 1, 2, 3, etc does nothing I have to manually mouse click them. They also, still, do not show on the Neuron bar (still showing behind the Blizzard vehicle bar) which is designated as a vehicle, possess, and fishing bar as well as my main action bar. I have never had this issue before.

All visibility states are checked.

**Comment by brittyazel** [comment]
Hrm this is weird. I haven't had this issue. You do have Vehicle/Possess/Override enabled on just that one bar correct? Sometimes people accidentally toggle those options on a different bar and the buttons appear their instead of on their main bar.

This is on Classic then? Do you have this issue on retail?

**Comment by ulrio** [comment]
I encountered this issue as well while riding caravan. Your fix seemed to resolved the issue, however during combat i cannot use [TAB] to select enemies the same way you can during normal combat and while flying for a bombardment quest i cannot see the target arrow showing the projectiles path.

**Comment by ylixir** [comment]
vehicles are working fine for me after a few rounds of bugfixes
