### ISSUE TITLE
Masque integration breaking

### ISSUE THREAD

**Issue by bolte-io** [brittyazel/Neuron#315]
Steps to reproduce:

When I create an action bar and add it on screen with grid displayed.
And when I have faded the backdrop on masque.
Clicking an empty/not empty action button changes the skin.
Doing a /reload restores the masque skinning.
I am attaching a screenshot for reference.

![image](https://user-images.githubusercontent.com/51535687/65533187-16a86800-def5-11e9-914e-be265f5fcc12.png)

**Comment by brittyazel** [comment]
I'll try to recreate this. Which Masque theme are you attempting to use?

**Comment by bolte-io** [comment]
Zoomed, with a backdrop of around 25% opacity, black

**Comment by brittyazel** [comment]
Is this still the case? Sorry I haven't had a chance to look at this yet. will do so asap

**Comment by bolte-io** [comment]
This issue is still happening.

**Comment by bolte-io** [comment]
Any progress on this? Not pushing, just curious on what the issue is.

**Comment by brittyazel** [comment]
Oh right, crap. I lost track of this one. Let me do some digging. I've been fully rewriting Neuron for Shadowlands and forgot about some of the open bugs 😋 I wish there were 3 of me!

**Comment by bolte-io** [comment]
I hear that, I have my own projects like my UI, a Wow Addon Pack manager (basically it would list the relams/characters, you'd pick one and then choose the UI, press install and it would put it in for you, taking care of the account and character folders as needed). Amongst other projects I'm never going to have time for with this thing called life that gets in the way!

**Comment by bolte-io** [comment]
Unfortunately, this bug is still present...
![image](https://user-images.githubusercontent.com/51535687/96385702-7ec78d00-118d-11eb-9f8f-6ae16e6bb13d.png)
The buttons appear on clicking them, they go from masque theme to classic on a click...

**Comment by brittyazel** [comment]
Yeah I haven't yet looked into it. It's on my 200 mile long todo list. Sorry for the delay

**Comment by bolte-io** [comment]
Alternatively, can you code it to allow macros created with Neuron bars to be added to standard action bars like say Domino/Bartender etc?

**Comment by brittyazel** [comment]
Unfortunately, I don't think so. That said, let's make sure this issue stays on topic to the issue of Masque breaking in certain circumstances.
