### ISSUE TITLE
[classic] Error walking in to and out of instances.

### ISSUE THREAD

**Issue by Dwargh** [brittyazel/Neuron#322]
I get this error when I walk into or out of a dungeon:
[ADDON_ACTION_BLOCKED] AddOn 'Neuron' tried to call the protected function 'NeuronActionBar3_ActionButton7:SetAttribute()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetAttribute'
Neuron\Objects/ACTIONBUTTON.lua:1165: in function `Reset'
Neuron\Objects/ACTIONBUTTON.lua:217: in function `SetType'
Neuron\Objects/ACTIONBUTTON.lua:816: in function `func'
...s\ArcHUD3-classic\Libs\AceTimer-3.0\AceTimer-3.0-17.lua:57: in function <...s\ArcHUD3-classic\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

that's where I have my:
/flyout i:bandage,!recipe:l:b:t:2:c:h

My changes to the flyout functionality shouldn't have anything to do with this.

**Comment by brittyazel** [comment]
Thanks for clarifying this is for classic! I haven't had any time to play classic yet, but I should be able to fix this bug easy enough

**Comment by brittyazel** [comment]
Is this still happening?

**Comment by Dwargh** [comment]
Sorry I've stopped playing.
Perhaps close this and let someone else reopen it if need be.
