### ISSUE TITLE
LUA error when logging in

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#324]
Didn't happen on other toons so not sure what's going on.

31x Neuron\Objects/STATUSBTN.lua:469: attempt to index field '?' (a nil value)
Neuron\Objects/STATUSBTN.lua:469: in function `repstrings_Update'
Neuron\Objects/STATUSBTN.lua:504: in function `?'
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by brittyazel** [comment]
Please check MASTER and report back if the issue is still present. Thanks!

**Comment by raysmith59** [comment]
Quick check, no error with that toon.  Any indication what was happening with that toon that wasn't with the rest of them?
