### ISSUE TITLE
Classic WoW - Key ring (bag) support

### ISSUE THREAD

**Issue by teh-fixerer** [brittyazel/Neuron#325]
Is there a way to access the key ring bag released in the recent patch in Wow Classic using neuron?

**Comment by teh-fixerer** [comment]
EDIT
found this information on Reddit which is a work around:

create a new empty button and use the macro editor to put in the following command:

/script ToggleBag(KEYRING_CONTAINER)

assign an icon of your preference.

clicking the button will toggle the keyring bag on and off.

**Comment by brittyazel** [comment]
Oh man keyrings.... I had forgotten all about those

**Comment by teh-fixerer** [comment]
Me too.  the work around I posted is fine for me at the moment.  Got into Strath just fine.

**Comment by brittyazel** [comment]
This is fixed. It's not the prettiest thing but the keyring is now there.
