### ISSUE TITLE
extra action bar visiable after assaults

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#329]
After finishing assault i still see extra action empty button .After reload its back to normal.

**Comment by brittyazel** [comment]
Yeah I have this too. I've been battling this for the better part of a year and cannot for the life of me find the root cause. It has to do with the cooldown frame, but that's as far as I can trace the pattern back to

**Comment by brittyazel** [comment]
I did it. I finally. Freaking. Fixed it. Absalkdhfjlaksdjflaskdfh
