### ISSUE TITLE
Feature - PvP visibility state

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#33]
Hi,
Just a little request, could it be possible to add a "PvP" trigger to the bar's visibility states ?
I know I could use this one :)

Thanks

**Comment by brittyazel** [comment]
I think so, I have to look into whether or not there's pvp events that fire
off, bit it should be doable

**Comment by brittyazel** [comment]
The whole state code in general needs some more logic. I.e. what to do if two states are active at the same time for the same bar. Combat + Cat Form for example. Does the bar take a combat state or a cat form state, or is there a cat form combat hybrid state that only exists when those two are activated together.

As it is right now, it's a little confusing for people to understand

**Comment by ylixir** [comment]
closing in favor of #466
