### ISSUE TITLE
/use itemname action button looks useable even when item isn't equipped

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#331]
I believe historically it used to either grey out (my preference) or just show a ? (not my preference) but I don't think it showed as available when it isn't.

One note - the current behaviour is probably desired in the case where there's an /equip of the same itemname prior to the /use, my requested change should be limited to a macro that only includes /use.

**Comment by AlexFolland** [comment]
Most usable items are usable from bags, without being equipped.  Most can't even be equipped.

**Comment by raysmith59** [comment]
That's fair too.  Hm.  My main issue is that I have two on-use trinkets I switch between depending on circumstances and since it looks like both are available I'm often clicking the wrong one under pressure.  Mind you, I only had to do this since /use 14 doesn't currently show the cooldown so once that's fixed I'll go back to doing that.

Yeah, never mind, closing this.
