### ISSUE TITLE
Changeing spec on lock from affliction to destro

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#333]
This poped up
Error occured in: Global
Count: 1
Message: ..\AddOns\Neuron\Objects\BAR.lua line 1283:
   attempt to perform arithmetic on local 'padH' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "@Neuron\Objects\BAR.lua"]:1283: SetObjectLoc()
   [string "@Neuron\Objects\ACTIONBUTTON_Flyout.lua"]:450: updateFlyoutBars()
   [string "@Neuron\Objects\ACTIONBUTTON_Flyout.lua"]:597: Flyout_UpdateButtons()
   [string "@Neuron\Objects\ACTIONBUTTON_Flyout.lua"]:755: UpdateFlyout()
   [string "@Neuron\Objects\ACTIONBUTTON.lua"]:797: ?()
   [string "@AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119:
      ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [string "=[C]"]: ?
   [string "@AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29:
      ...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   [string "@AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: Fire()
   [string "@TradeSkillInfo\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120:
      ...ns\TradeSkillInfo\Libs\AceEvent-3.0\AceEvent-3.0.lua:119

**Comment by brittyazel** [comment]
this is fixed
