### ISSUE TITLE
New 'b' version causes action buttons not to activate when available

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#337]
I only noticed it in a raid and downgraded as soon as I noticed the issue but basically some abilities (Eye Beam was the one I noticed) that were greyed out while on CD weren't reverting to their usual available look; they can be pushed, though, so it's just cosmetic.

**Comment by brittyazel** [comment]
kk I think I caught this bug. Will be fixed in the "c" version shortly

**Comment by brittyazel** [comment]
Can you test with version 1.2.7 and let me know if this is still a problem

**Comment by raysmith59** [comment]
It's better but still not perfect.  I haven't been able to figure out what's causing it work or not work, I've had entire play sessions be fine and other times half my buttons are greyed out even though they're available.

**Comment by brittyazel** [comment]
do you know if there is a LUA error when it happens that the buttons stay greyed out?

I.e. we have a function whose job it is to set if the spell is usable or not: ACTIONBUTTON:SetUsableSpell()

If this function has a LUA error it may stop it from being executed for future cycles

**Comment by raysmith59** [comment]
I don't think so, I'm certainly not getting a LUA error.  If it helps, for diagnostic purposes in Master I'd be fine with you adding some code to put some text into the chat window when I mouseover a button so I can report back what it says for an inactive button that should be active vs otherwise.  It'll be spammy but I should be able to get back to you pretty quickly with the info.

**Comment by raysmith59** [comment]
I should also mention that once I use an inactive button it generally fixes itself, at least for a while.  They don't stay grey.

**Comment by brittyazel** [comment]
Can you tell me if 1.3.2 fixes this?

**Comment by raysmith59** [comment]
It *may* be a bit better but still not fixed - for instance, Obliterate on my frost DK didn't go active about 10 straight uses but after the 11th it came back.

**Comment by brittyazel** [comment]
Weird... Ok I'll keep digging. I swear I feel like an archaeologist

**Comment by raysmith59** [comment]
I can do some trial and error, too, where in the code are you looking for this one?  I tried on my own a few days ago (this issue has been really bad for my dps since it popped up) and only managed to negatively affect the borders for the buttons I was looking at so pretty sure I was in the wrong place.

**Comment by brittyazel** [comment]
Umm it should be in Objects>BUTTON.lua in a function called UpdateSpellUsablity()

**Comment by brittyazel** [comment]
I maybe(?) fixed it. I added a UpdateUsable() call right after we cancel a cooldown timer or the timer runs out. This should, in theory, return the button vertex color back to the full color.

**Comment by raysmith59** [comment]
Missed the comment to test in master so I was waiting for release.

I spent a lot of time playing yesterday including a raid and I'm not seeing any improvement vs the previous versions, this is still happening, multiple buttons on my warrior weren't lighting up when available (mostly Execute but others at times).  I think this needs to be re-opened.

**Comment by brittyazel** [comment]
Do you have some sort of an alpha applied to your bar? I.e. do you have a transparency set to a lower value, or is the bar alpha set to 1?

**Comment by brittyazel** [comment]
You're sure this started happening with 1.2.6b? I can't find a single thing in that release that should trigger this behavior...

**Comment by raysmith59** [comment]
The current file list doesn't go back that far but that seems to be about right.  I can't say for sure it started happening with that version but that's when I first noticed the issue.  I think there may be some combat-specific aspect to this that I'm going to test further in that I think it happens more (or only) when in combat.

**Comment by brittyazel** [comment]
hrm... ok that's helpful to know that it's only in combat. Most of my trial and error has been while standing still in Zuldazar and running back and forth into and out of the inn. Sorry for this taking a while to sort out, I'm just stumped

**Comment by raysmith59** [comment]
Hadn't thought of that - yes, I only ever notice this in combat (ie. the buttons going grey in the first place are because they were used in combat).  I suppose there's a chance something like a potion going on CD could have the same issue but that's not something I've noticed.

In terms of your alpha question that I can't find, I haven't mucked with anything there, the only settings I have that're likely different from yours are Show Grid Off and Snap To On.

I haven't played much the past couple of days, needed a bit of a break, but I'll be playing more tomorrow including M+ so I'll try to pay more attention there.  I've also set up a second action bar for my main toon that duplicates some the buttons, I'm curious if the second bar button also gets stuck grey when it does on the main action bar.

**Comment by raysmith59** [comment]
I think I've figured out where the issue is if not the specific cause.  The issue only seems to occur if the bar has Cooldown Transparency enabled.  I think there are other issues with that option as well but I'll leave those until the activation issue is fixed, it's possible that could fix other things too.

**Comment by brittyazel** [comment]
Thanks for the update. Sadly I've already rewritten the whole cdAlpha code in the Neuron-Next branch. I'll try to backport it for the time being.

**Comment by brittyazel** [comment]
Please test the lastest MASTER and let me know if this fixes the issue. I think I got it sorted finally

**Comment by raysmith59** [comment]
Looks like it hit release so I tried that version, in VERY limited testing no issues so far, I'll do a more comprehensive test tomorrow.

**Comment by brittyazel** [comment]
Yeah I just went ahead and pulled the trigger. I was able to finally
replicate the issue you were seeing once you said it was when CooldownAlpha
enabled, and from what I can tell I sorted that out

**Comment by brittyazel** [comment]
Yeah I just went ahead and pulled the trigger. I was able to finally replicate the issue you were seeing once you said it was when CooldownAlpha
enabled, and from what I can tell I sorted that out

**Comment by Fizgig1973** [comment]
Checked it across 23 toons so far, seems to be working great. Thanks so much!

**Comment by raysmith59** [comment]
Agreed, so far so good.
