### ISSUE TITLE
Neuron is filling the global namespace with Bar and Button references

### ISSUE THREAD

**Issue by brittyazel** [brittyazel/Neuron#34]
I'm not quite sure why, but Neuron is flooding the global namespace with ActionBar and ActionButton tables. Ideally all refrences to these bars should be in Neuron.BARIndex or Neuron.BARName, and we should only need a couple of top level variables. Flooding the global namespace can slow down the game and all addons due to the lookup table being way more complex

**Comment by teh-fixerer** [comment]
Not sure if this is why, but way back in the day there was a button storage feature.  Perhaps there is leftover code that is causing this?

**Comment by brittyazel** [comment]
It could be. I'm hoping to fix this, but I'm trying to do so in a way that doesn't break everyone's profiles

**Comment by brittyazel** [comment]
This ends up just being the way CreateFrame works. It adds the frame to _G nomatter what pointer you initiall set.
