### ISSUE TITLE
LUA error when putting bars into Edit mode

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#340]
1x [string "NeuronStatusBar4_StatusBar3FBFrame:OnShow"]:1: attempt to index field 'sb' (a nil value)
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@Neuron\Objects\STATUSBTN.lua"]:1809: in function `SetObjectVisibility'
[string "@Neuron\Objects\BAR.lua"]:1719: in function `UpdateObjectVisibility'
[string "@Neuron\Neuron-1.3.0.lua"]:740: in function `ToggleButtonEditMode'
[string "@Neuron\Neuron-MinimapIcon.lua"]:79: in function `Minimap_OnClickHandler'
[string "@Neuron\Neuron-MinimapIcon.lua"]:46: in function `OnClick'
[string "@Atlas\Libs\LibDBIcon-1.0\LibDBIcon-1.0-43.lua"]:144: in function <...ceAtlas\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142>

Locals:
self = NeuronStatusBar4_StatusBar3FBFrame {
 0 = <userdata>
 feedback = NeuronStatusBar4_StatusBar3FBFrameFeedback {
 }
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = NeuronStatusBar4_StatusBar3FBFrameFeedback {
 0 = <userdata>
 text = NeuronStatusBar4_StatusBar3FBFrameFeedbackText {
 }
 bg = NeuronStatusBar4_StatusBar3FBFrameFeedbackBackground {
 }
 border = NeuronStatusBar4_StatusBar3FBFrameFeedbackBorder {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'sb' (a nil value)"

**Comment by brittyazel** [comment]
Please update to 1.3.0b
