### ISSUE TITLE
LUA error when attempting to edit an action button

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#341]
The count kept increasing while the edit UI was open, as soon as I closed it the count froze.

133x Neuron\Neuron-GUI.lua:2549: attempt to index field 'iconframeicon' (a nil value)
[string "@Neuron\Neuron-GUI.lua"]:2549: in function `specUpdateIcon'
[string "@Neuron\Neuron-GUI.lua"]:2616: in function `MacroEditorUpdate'
[string "@Neuron\Neuron-GUI.lua"]:2657: in function `ButtonEditorUpdate'
[string "@Neuron\Neuron-GUI.lua"]:2663: in function `ButtonEditor_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@Neuron\Neuron-GUI.lua"]:4053: in function `ObjEditor_OnClick'
[string "@Neuron\Neuron-GUI.lua"]:4093: in function <Neuron\Neuron-GUI.lua:4093>

Locals:
self = <table> {
 SubFrameHoneycombBackdrop_OnLoad = <function> defined @Neuron\Neuron-GUI.lua:258
 BarListScrollFrameUpdate = <function> defined @Neuron\Neuron-GUI.lua:1135
 updateIconList = <function> defined @Neuron\Neuron-GUI.lua:2850
 modules = <table> {
 }
 BarEditor_DeleteBar = <function> defined @Neuron\Neuron-GUI.lua:1255
 NeuronPanelTemplates_DeselectTab = <function> defined @Neuron\Neuron-GUI.lua:310
 flyoutTypeSetter = <function> defined @Neuron\Neuron-GUI.lua:3601
 visOptionOnClick = <function> defined @Neuron\Neuron-GUI.lua:1559
 SetDefaultModulePrototype = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:440
 NeuronPanelTemplates_TabResize = <function> defined @Neuron\Neuron-GUI.lua:346
 VisEditorScrollFrame_OnLoad = <function> defined @Neuron\Neuron-GUI.lua:1945
 IsEnabled = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 ObjEditor_OnClick = <function> defined @Neuron\Neuron-GUI.lua:4041
 ActionListScrollFrameUpdate = <function> defined @Neuron\Neuron-GUI.lua:2415
 hookHandler = <function> defined @Neuron\Neuron-GUI.lua:3536
 ADDON_LOADED = <function> defined @Neuron\Neuron-GUI.lua:181
 RegisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 MainMenu_OnLoad = <function> defined @Neuron\Neuron-GUI.lua:3523
 hooks = <table> {
 }
 BarOptions_OnLoad = <function> defined @Neuron\Neuron-GUI.lua:1320
 runUpdater = <function> defined @Neuron\Neuron-GUI.lua:3553
 ObjEditor_OnEnter = <function> defined @Neuron\Neuron-GUI.lua:4021
 macroIconOnClick = <function> defined @Neuron\Neuron-GUI.lua:2831
 SetEnabledState = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @Chatter\Libs\AceHook-3.0\AceHook-3.0.lua:274
 macroNoteEdit_OnTextChanged = <function> defined @Neuron\Neuron-GUI.lua:2791
 ColorPicker_OnLoad = <function> defined @Neuron\Neuron-GUI.lua:3499
 SubFrameBlankBackdrop_OnLoad = <function> defined @Neuron\Neuron-GUI.lua:244
 sbTypeOnClick = <function> defined @Neuron\Neuron-GUI.lua:4298
 SecondaryPresetsScrollFrameUpdate = <function> defined @Neuron\Neuron-GUI.lua:2147
 updateCustomState = <function> defined @Neuron\Neuron-GUI.lua:872
 ObjectEditor_OnShow = <function> defined @Neuron\Neuron-GUI.lua:2284
 target_options = <table> {
 }
 BarEditor_OnLoad = <function> defined @Neuron\Neuron-GUI.lua:905
 NewModule = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 EditBox_PopUpInitialize = <function> defined @Neuron\Neuron-GUI.lua:405
 DeleteButton_OnLoad = <function> defined @Neuron\Neuron-GUI.lua:1246
 remapOnTextChanged = <function> defined @Neuron\Neuron-GUI.lua:1688
 BarList_OnLoad = <function> defined @Neuron\Neuron-GUI.lua:1020
 PLAYER_SPECIALIZATION_CHANGED = <function> defined @Neuron\Neuron-GUI.lua:174
 GetName = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 createflyoutmacro = <function> defined @Neuron\Neuron-GUI.lua:3622
 SubFrameBlackBackdrop_OnLoad = <function> defined @Neuron\Neuron-GUI.lua:222
 name = "Neuron_GUI"
 VisEditor_OnLoad = <function> defined @Neuron\Neuron-GUI.lua:1917
 ButtonEditor_OnLoad = <function> defined @Neuron\Neuron-GUI.lua:3042
 Disable = <function> defined @Account

**Comment by brittyazel** [comment]
Please update to 1.3.0b
