### ISSUE TITLE
Weird behaiuor of macro names

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#342]
I recently seen macros not haveing names shown.Also weird thing is when i go into neuron edit buttons if i edit macro i get names back on rest of macros but not on macro i just edited. And macros are basicly to just open addon like /la for loot apraiser.

**Comment by Addonman** [comment]
And with relog names are gone

**Comment by brittyazel** [comment]
hrm. Ok this may be something stupid on my part. I'll take a look at it. I don't show my macro names on the buttons themselves usually so I probably missed it.

You do mean the name of the macro ability shown on the button itself right?

**Comment by brittyazel** [comment]
I'll have this fixed today at some point

**Comment by brittyazel** [comment]
hrm my macro names are working just fine. Can you screenshot an example for me?

**Comment by brittyazel** [comment]
I just created a simple basic macro, gave it a name in the button editor, and the name is showing perfectly. I logged out and back in and it's still showing.

**Comment by Addonman** [comment]
I do have macro names checked.Last couple of days or better saying updates i start noticing names on macros were gone. Names on spell are ok so far ,but macros names i created in /m  just for getting to certain addons faster or simple as /roll so i dont have to type in chat -those names of maros are gone.Macros on abilities are still here ,or mounts of flask and stuff like that.

**Comment by brittyazel** [comment]
Did you manually add names to those simple convenience macros?

**Comment by Addonman** [comment]
Yes in  Blizz macro window you get into with /m. or / macro

**Comment by Addonman** [comment]
I tried even to go into configure button and make macro /roll and name it Roll it doesnt show up for me.Also i noticed what i said before if i edit 1 macro it names shows on other macros,but what i wanted to add that after that  i moved my mouse over macros and names were gone again.

**Comment by brittyazel** [comment]
Ooooog you're using the Blizz macro window. This whole time I had though you were using the Neuron macro window. This is helpful to figuring out your issue

**Comment by Addonman** [comment]
Seems to work ,but is needed to pull all macros from /m window again.

**Comment by brittyazel** [comment]
Yeah there was a bug that erased the name from the button upon dragging a BlizzMacro. I fixed the bug so it doesn't erase the name any longer, but it can't retroactively go back and add names back to those buttons, hance needing to re-drag
