### ISSUE TITLE
Void eruption/void bolt

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#343]
On my priest i noticed that icon doesnt switch from vod eruption into void bolt .Is it Blizz messing with us or Neuron? WA for same abiltiy works fine.

**Comment by brittyazel** [comment]
That might be Neuron's fault. I'll get that fixed quick

**Comment by brittyazel** [comment]
Should have this fixed in the next release. You'll likely have to drag the ability to your bars Gain though for the fix to work
