### ISSUE TITLE
LUA error when changing mage spec from arcane to fire

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#349]
1x Neuron\Objects\BAR.lua:1298: attempt to perform arithmetic on local 'padH' (a nil value)
[string "@Neuron\Objects\BAR.lua"]:1298: in function `SetObjectLoc'
[string "@Neuron\Objects\ACTIONBUTTON_Flyout.lua"]:450: in function `updateFlyoutBars'
[string "@Neuron\Objects\ACTIONBUTTON_Flyout.lua"]:597: in function `Flyout_UpdateData'
[string "@Neuron\Objects\ACTIONBUTTON_Flyout.lua"]:755: in function `UpdateFlyout'
[string "@Neuron\Objects\ACTIONBUTTON.lua"]:642: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by brittyazel** [comment]
fixed. Sorry for the delay just got back in the swing of things. Please test the latest MASTER code and report if there's any issues

**Comment by raysmith59** [comment]
Testing now, thanks.

**Comment by raysmith59** [comment]
No new issues that I've seen so far.
