### ISSUE TITLE
Timers-cooldowns

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#351]
Lately i noticed i am not  getting cooldowns on certain stuff-like on trinket i pulled on my bar or extra action button on cloak arent showing cooldowns any more

**Comment by brittyazel** [comment]
Is this true even with yesterday's update?

**Comment by Addonman** [comment]
well i posted this before i loged in so this as not working yestrday in raid.But after todays log in trinket show CD timer,but cant test raid one since i have no oportunity to test it on Nzoth.

**Comment by brittyazel** [comment]
Yeah sorry. I implemented an inheritance structure to simplify the code, and a few things slipped through. Good news is the code is working well and stable, aside from a few little things 😋. 

I believe the extrabutton is working based on my testing, so I'm going  to close this. Please reopen if anything is awry
