### ISSUE TITLE
Icons faded out

### ISSUE THREAD

**Issue by Fizgig1973** [brittyazel/Neuron#352]
Using the latest update I found that my spells and abilities seem to randomly fade out as if they haven't been learned yet.

This is happening on Extra Action Button 1, and Zone Action Button 1 as well.

**Comment by brittyazel** [comment]
Yes I had this issue yesterday but I thought I fixed it in the latest release. Which version are you using?

**Comment by Fizgig1973** [comment]
Using Neuron-1.3.3 
Date:    Sun Apr 26 00:44:43 2020 -0700

I haven't tested with the Extra Action and Zone Buttons yet, those were happening prior to the latest download, so might be fixed. 

The faded out icons are on my main action bars created by Neuron.

**Comment by brittyazel** [comment]
Are the icons that are effected for spells or items, or both?

**Comment by Fizgig1973** [comment]
Just for the spells. And it seems to happen randomly, it's not always the same spells that fade out.

**Comment by brittyazel** [comment]
I believe this is the same issue as #337. Closing to keep it all in one spot
