### ISSUE TITLE
LUA error when enabling multi spec for a new action bar

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#353]
1x Neuron\Objects\BAR.lua:2226: attempt to call method 'UpdateButtonSpec' (a nil value)
[string "@Neuron\Objects\BAR.lua"]:2226: in function `?'
[string "@Neuron\Neuron-GUI.lua"]:1314: in function `chkOptionOnClick'
[string "@Neuron\Neuron-GUI.lua"]:1330: in function <Neuron\Neuron-GUI.lua:1330>

Locals:
self = NeuronActionBar5 {
 0 = <userdata>
 elapsed = 0
 objTemplate = <table> {
 }
 UnwrapScript = <function> defined @FrameXML\SecureHandlers.lua:788
 dragged = false
 barLabel = "Action Bar"
 messagebg = NeuronActionBar5MessageBG {
 }
 pushed = 0
 keybindable = true
 objMax = 250
 text = NeuronActionBar5Text {
 }
 message = NeuronActionBar5Message {
 }
 driver = NeuronBarDriver5 {
 }
 barType = "ActionBar"
 DB = <table> {
 }
 right = 1174.166748
 data = <table> {
 }
 handler = NeuronBarHandler5 {
 }
 objType = "Action Button"
 barDB = <table> {
 }
 SetFrameRef = <function> defined @FrameXML\SecureHandlers.lua:793
 posSet = true
 click = "RightButton"
 WrapScript = <function> defined @FrameXML\SecureHandlers.lua:782
 alphaUpTimer = <table> {
 }
 buttons = <table> {
 }
 left = 959.166748
 bottom = 168.500000
 vis = <table> {
 }
 class = "ActionBar"
 top = 211.500000
 microAdjust = false
 Execute = <function> defined @FrameXML\SecureHandlers.lua:777
 selected = true
 keybind = NeuronActionBar5KeyBind {
 }
 toggleframe = NeuronActionBar5 {
 }
}
msg = nil
gui = true
checked = true
query = nil
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = NeuronActionBar5_ActionButton1 {
 }
 2 = NeuronActionBar5_ActionButton2 {
 }
 3 = NeuronActionBar5_ActionButton3 {
 }
 4 = NeuronActionBar5_ActionButton4 {
 }
 5 = NeuronActionBar5_ActionButton5 {
 }
}
(for control) = 1
i = 1
object = NeuronActionBar5_ActionButton1 {
 0 = <userdata>
 spellGlow = true
 cdAlpha = 1
 class = "ActionBar"
 tooltips = true
 UnwrapScript = <function> defined @FrameXML\SecureHandlers.lua:788
 FlyoutBorderShadow = NeuronActionBar5_ActionButton1FlyoutBorderShadow {
 }
 downClicks = false
 binder = NeuronActionBar5_ActionButton1BindFrame {
 }
 barLockShift = false
 tooltipsCombat = false
 bindColor = "1;1;1;1"
 spellGlowDef = true
 DB = <table> {
 }
 noAction = "Buttons\UI-Quickslot"
 hasAction = "Buttons\UI-Quickslot2"
 manacolor = <table> {
 }
 data = <table> {
 }
 macroText = true
 rangecolor = <table> {
 }
 multiSpec = false
 cdcolor1 = <table> {
 }
 bar = NeuronActionBar5 {
 }
 countColor = "1;1;1;1"
 elements = <table> {
 }
 cdcolor2 = <table> {
 }
 macroColor = "1;1;1;1"
 Execute = <function> defined @FrameXML\SecureHandlers.lua:777
 rangeInd = true
 barLock = false
 cdText = false
 objType = "ACTIONBUTTON"
 countText = true
 SetFrameRef = <function> defined @FrameXML\SecureHandlers.lua:793
 debuffcolor = <table> {
 }
 barLockAlt = false
 keys = <table> {
 }
 editmode = false
 upClicks = true
 spellGlowAlt = false
 WrapScript = <function> defined @FrameXML\SecureHandlers.lua:782
 tooltipsEnhanced = true
 statedata = <table> {
 }
 id = 1
 buffcolor = <table> {
 }
 isShown = true
 equipcolor = <table> {
 }
 editor = NeuronActionBar5_ActionButton1EditFrame {
 }
 config = <table> {
 }
 FlyoutBorder = NeuronActionBar5_ActionButton1FlyoutBorder {
 }
 bindText = true
 showGrid = false
 FlyoutArrow = NeuronActionBar5_ActionButton1FlyoutArrow {
 }
 rangeTimer = <table> {
 }
 barLockCtrl = false
}
(*temporary) = nil
(*temporary) = NeuronActionBar5_ActionButton1 {
 0 = <userdata>
 spellGlow = true
 cdAlpha = 1
 class = "ActionBar"
 tooltips = true
 UnwrapScript = <function> defined @FrameXML\SecureHandlers.lua:788
 FlyoutBorderShadow = NeuronActionBar5_ActionButton1FlyoutBorderShadow {
 }
 downClicks = false
 binder = NeuronActionBar5_ActionButton1BindFrame {
 }
 barLockShift = false
 tooltipsCombat = false
 bindColor = "1;1;1;1"
 spellGlowDef = true
 DB = <table> {
 }
 noAction = "Buttons\UI-Quickslot"
 hasAction = "Buttons\UI-Quickslot2"
 manacolor = <table> {
 }
 data = <table> {
 }
 macroText = true
 rangecolor = <table> {
 }
 multiSpec = false
 cdcolor1 = <table> {
 }
 bar = NeuronActionBar5 {
 }
 countColor = "1;1;1;1"
 elements = <table> {
 }
 cdcolor2 = <table> {
 }
 macroColor = "1;1;1;1"
 Execute = <function> defined @FrameXML\SecureHandlers.lua:777
 rangeInd = true
 barLock = false
 cdText = fal

**Comment by brittyazel** [comment]
Is this with MASTER or release?
