### ISSUE TITLE
Sunfire does not work

### ISSUE THREAD

**Issue by judgdredd** [brittyazel/Neuron#358]
I drag it on to any neuron button and even bind /cast Sunfire or /cast Sunfire()

It appears on the action bar but is not clickable or able to be pressed by it's corresponding keybind, i've tried placing it in slots that spells definitely work on... the spell does not activate what so ever.

**Comment by jpmeyers** [comment]
after dropping a spell on the action bar, try reloading (/reload). this usually works for me.

**Comment by judgdredd** [comment]
I'll login today and give this a shot, although i'm pretty sure i logged and tried it.

**Comment by brittyazel** [comment]
odd, I use sunfire on my druid all the time. Is it specifically Sunfire, or any spell you drag?

**Comment by ylixir** [comment]
no movement on this from the original post. closing
