### ISSUE TITLE
Charges and stacks not showing

### ISSUE THREAD

**Issue by TruthNZ** [brittyazel/Neuron#366]
## Issue description:
Charges aren't showing on buttons. Nor are abilities with associated stacks.

## How to reproduce:
Put an ability with charges (or generates stacks) onto a button.

## Technical info:
 - **Addon Version:** 1.4.0a

**Comment by TruthNZ** [comment]
I've rolled back to version 1.4.0 and that's working fine for me.

**Comment by brittyazel** [comment]
ugh yep, I know what I did. I'm just not sure what causes it. This bug doesn't show up on my computer or any computer I can test with, so I have no idea what drives it. I'm not sure if it's a CPU performance thing or what, but somehow the loading process gets all twisted around.
