### ISSUE TITLE
Keybinding Number behind the icon

### ISSUE THREAD

**Issue by Solithe** [brittyazel/Neuron#367]
one little problem with the Keybinding Text

![123 - Kopie](https://user-images.githubusercontent.com/46850986/96301546-a4229280-0ff7-11eb-9739-aef0b1d79a07.jpg)

**Comment by Solithe** [comment]
Retail. Shadowland PrePatch.

**Comment by brittyazel** [comment]
Yes it was just fixed. Snag the latest version please

**Comment by Solithe** [comment]
works. ty =)
