### ISSUE TITLE
LUA error in combat

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#368]
May be something new to the latest version, haven't seen this before and I didn't do anything weird.

Message: [ADDON_ACTION_BLOCKED] AddOn 'Neuron' tried to call the protected function 'OverrideActionBarButton4:Show()'.
Time: Fri Oct 16 18:33:41 2020
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Neuron' tried to call the protected function 'OverrideActionBarButton4:Show()'.
[string "@Interface\FrameXML\ActionButton.lua"]:759: in function `OnEvent'
[string "@Interface\FrameXML\ActionButton.lua"]:217: in function <Interface\FrameXML\ActionButton.lua:214>

Locals: <none>

**Comment by brittyazel** [comment]
What is the context? Where were you fighting? Do you have any unique bar configs? Is this retail or classic?

Neuron definitely doesn't ever make any calls to OverrideActionBarButton, and I've never seen this. I'm going to need help isolating it.

**Comment by brittyazel** [comment]
Actually, I think I may know what this is. This is a recurrence of an OLD bug from like 3 years ago. I vaguely remember what I did to fix it.

**Comment by raysmith59** [comment]
This is still happening.  I think I've narrowed it down to happening when one of the action button lights up.  It doesn't happen every time buttons light up but I think a button just lit up every time it happens.  Likely related to the bar Spell Alerts toggle.

I'll try to provide a more expansive error next time it happens.
