### ISSUE TITLE
casting spell while dragging spell

### ISSUE THREAD

**Issue by Oelenor** [brittyazel/Neuron#369]
whenever I pick up a spell to move on a bar it gets casted

**Comment by Oelenor** [comment]
I cannot be around anything when I'm moving spells around. For example, if I am moving around SW: Death around, it will automatically target and cast it on something

**Comment by jpmeyers** [comment]
I know this happens to me when I have "Down Clicks" checked in the bar edit
menu. But, since I prefer spells to cast when I let go of the button I
always make sure that only "Up Click" is checked. Doing this also prevents
a cast when I go to move a button around.

**Comment by brittyazel** [comment]
This is because you have downclicks enabled. This is why upclicks is the default.
