### ISSUE TITLE
Text output occurs when flyouts are present on a bar

### ISSUE THREAD

**Issue by jpmeyers** [brittyazel/Neuron#371]
This has been occurring since the 1.4.0 release of Neuron for the 9.0 pre-patch, both on its own and when other addons are enabled. I consider it less a bug than an annoyance, since it doesn't affect the performance of the addon as a whole.

Any time I have a flyout present on a button, I will get a listed text output in chat that reads "Worn 1, Worn 2, Worn 3, .." (as in the image below) through to as high as 19, but will also skip some numbers.  This output seems to repeat twice when it occurs and it appears to occur on login, whenever I change talents, or if I update a flyout. It doesn't do this if I add or remove spells from the buttons.

The really odd bit is that it doesn't occur unless I've populated a button with a flyout. Blank bars, nothing. Bars with a "normal" button population, nothing. Add a flyout, I get the output below. Remove the flyout and the output stops occurring when I do the activities listed above.

![output](https://user-images.githubusercontent.com/1920508/96354589-df779c80-109d-11eb-8e20-20485bb50d37.jpg)

Love the addon, and I really appreciate your picking up the maintenance of it. I've been using it since it's early days as Macaroon! by Maul and I find it to be the most flexible and useful bar mod I've seen.

**Comment by jpmeyers** [comment]
I think I found it. Line 547 in ACTIONBUTTON_Flyout.lua looks like a debug output:
print(tostring(i),tostring(j))

I commented it out and that seems to have done the trick.

**Comment by brittyazel** [comment]
Yeah my bad, I'll fix that asap and it will be in the next version. Sorry about that!
