### ISSUE TITLE
Mac cmd (command) keybinds

### ISSUE THREAD

**Issue by JJHuskie** [brittyazel/Neuron#377]
Current version of WoW has changed the mac client to allow bindings and macro options with the cmd key and, as such, has removed the UI option to 'use cmd key as ctrl'.  This now prevents making buttons in Neuron using that binding (cmd-1, cmd-2, etc.) as Neuron currently views the command key as a normal key (LMETA) instead of a modifier.  There's an easy workaround for this using macro options (i.e. bind one button to '1' and make its macro something like '/cast [mod:cmd] spell x; spell y'), but this reduces options for organizing bars - essentially the macros bound to cmd end up hidden/stacked.  Personally the cmd key is my favorite and most used modifier, so adding this functionality would be much appreciated.  Thanks.

**Comment by brittyazel** [comment]
I'll do what I can, but I don't have a mac to test on. When I get it I'll likely ask you to test a few iterations until one works

**Comment by JJHuskie** [comment]
Ah, very cool.  I'll be happy to help.  Thanks so much for looking into it.  <3

**Comment by ylixir** [comment]
closing in favor of #466
