### ISSUE TITLE
Lua errors, spell ids/tooltips

### ISSUE THREAD

**Issue by teh-fixerer** [brittyazel/Neuron#38]
Hi,
Getting some lua errors even after recent update on a few characters, especially hunter. Call pet spell placed on the action bar seem to be the cause.  Had some on my fury warrior too, but it was a button that got copied over from the other spec (arms) will check into it more and post separately if I can.

Message: Interface\AddOns\Neuron\Neuron_Buttons.lua:2230: Invalid spell ID in GameTooltip:SetSpellByID
Time: 01/16/18 20:08:05
Count: 16
Stack: Interface\AddOns\Neuron\Neuron_Buttons.lua:2230: Invalid spell ID in GameTooltip:SetSpellByID
[C]: ?
[C]: in function `SetSpellByID'
Interface\AddOns\Neuron\Neuron_Buttons.lua:2230: in function `MACRO_SetSpellTooltip'
Interface\AddOns\Neuron\Neuron_Buttons.lua:2310: in function `MACRO_SetTooltip'
Interface\AddOns\Neuron\Neuron_Buttons.lua:2352: in function <Interface\AddOns\Neuron\Neuron_Buttons.lua:2337>
[C]: ?

Locals:

**Comment by teh-fixerer** [comment]
Sorry for the false alarm, i exited the game and whoa and be hold blizz pushed an update that seemed to fix this issue

**Comment by teh-fixerer** [comment]
it disappeared for a while when blizz pushed a small patch, but it is back now?

**Comment by brittyazel** [comment]
Is it just this single ability causing the bug, or do others trip the error as well?

**Comment by teh-fixerer** [comment]
So far it is just the hunter call pet spells that cause it. I put a button for each pet pet on my bar.
If you don't have an active pet, everything is fine, tooltips and icons as normal.  Once you summon a pet, the lua errors begin and the icons become "clear"

see before (no active pet) and after (with pet) screen grabs below:

![wowscrnshot_011718_104541](https://user-images.githubusercontent.com/8992077/35055194-33751e80-fb74-11e7-9cc6-0a8357275372.jpg)
![wowscrnshot_011718_104605](https://user-images.githubusercontent.com/8992077/35055202-3c281a78-fb74-11e7-9f7a-0b05b04d343f.jpg)

**Comment by teh-fixerer** [comment]
Not sure how i managed to close the ticket,  but the issue is still active.
 I don't normally play marks, just survival and beast master, but I'll check on marks and see if i can gather up whats happening there.

**Comment by brittyazel** [comment]
Yeah this bug appears to be a new occurance as of 7.3.5. I'll have to log onto my girlfriends hunter to replicate the error and find out what's going on. It's always fun when blizzard changes spellID's and doesn't mention it ;-)

**Comment by brittyazel** [comment]
Fixed in the last commit. The fix will be in the next version :-)

**Comment by teh-fixerer** [comment]
Many thanks!
