### ISSUE TITLE
Error starting Pet Battles

### ISSUE THREAD

**Issue by TruthNZ** [brittyazel/Neuron#384]
Upon starting a pet battle I get the following error:

Message: Interface\AddOns\Neuron\Objects\MENUBTN.lua:126: attempt to call global 'MainMenuMicroButton_RepositionAlerts' (a nil value)
Time: Sun Nov 29 00:12:56 2020
Count: 17
Stack: Interface\AddOns\Neuron\Objects\MENUBTN.lua:126: attempt to call global 'MainMenuMicroButton_RepositionAlerts' (a nil value)
[string "=[C]"]: in function `MainMenuMicroButton_RepositionAlerts'
[string "@Interface\AddOns\Neuron\Objects\MENUBTN.lua"]:126: in function `ModifiedMoveMicroButtons'
[string "@Interface\AddOns\Neuron\Objects\MENUBTN.lua"]:72: in function <Interface\AddOns\Neuron\Objects\MENUBTN.lua:72>
[string "=(tail call)"]: ?
[string "*:OnShow"]:2: in function <[string "*:OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Blizzard_PetBattleUI\Blizzard_PetBattleUI.lua"]:151: in function `PetBattleFrame_Display'
[string "@Interface\AddOns\Blizzard_PetBattleUI\Blizzard_PetBattleUI.lua"]:96: in function <...AddOns\Blizzard_PetBattleUI\Blizzard_PetBattleUI.lua:93>

Addon Version: 1.4.2b
Happens with no other addons loaded.

**Comment by brittyazel** [comment]
Got it. Looks like Blizz changed their function names with Shadowlands. I'm on vacation atm but I'll shoot to get this fixed asap as it should be pretty easy
