### ISSUE TITLE
Clamping bars together

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#389]
## Is your feature request related to a problem? Please describe:
Not really a problem but would save some time if we could join bars together like Details attaches 2 windos together
## Describe the solution you'd like to see implemented:
There is a way that you can join 2 bars -either one on top another or left/right side of bar

## Describe alternatives you've considered:
Details have function were you can join 2 windows and  they move if they are locked as one

## Additional context:
*Add any other context, screenshots, sketches, etc about the feature request here. A picture is worth 1000 words.*

**Comment by brittyazel** [comment]
This already exists, it's called SnapTo. Any bars that have SnapTo enabled will stick together. Likewise, moving the bar that was snapped onto should move any bars snapped to it.

**Comment by Addonman** [comment]
Do i have to select snap on on both bars for it to work?

**Comment by Addonman** [comment]
I tried it,but i doesnt work as i would like it to. I set padding to 0 and its still leaves small gap between 2 bars. Like padding was set to 1 instead of 0. Also bottom bars likes to snap to bottom of screen which is not good since i have bazooka addon as top and bottom bars .So bazzoka bars cover part of icon.
