### ISSUE TITLE
Delete confirmation stays active when switching between bars

### ISSUE THREAD

**Issue by 4C51** [brittyazel/Neuron#39]
# Steps to reproduce
1. Select a bar (bar1)
1. Click Delete Current Bar
1. Select a different bar (bar2)
1. Click Yes on the delete confirmation
1. Currently selected bar is deleted

## Expected behavior
Confirmation should be cleared upon switching bar selection to avoid ambiguity -- Leaving the confirmation active is a bit confusing as you lose context.

###### PS: Healer party is the best party!

**Comment by brittyazel** [comment]
I agree 100%
