### ISSUE TITLE
Save button when editing buttons does not seem to do anything

### ISSUE THREAD

**Issue by DejayRezme** [brittyazel/Neuron#394]
## Issue description:
When editing a macro for a button, changing the text seems to get saved no matter if you click "save" or not. So the save button doesn't seem to do anything.
This creates confusion for the user, wondering if he forgot to click save and checking again.
And this doesn't allow you to type something wrong and "cancel" the edit by pressing esc either.

I actually prefer the automatic save. It's just confusing and the button should be removed. Maybe a having to press "revert" would be more practical. Maybe next to the reset button which maybe should be called "clear" or "delete" instead.

Maybe I misunderstand the purpose and this is supposed to save "early" before closing the window. But it also saves automatically 

## How to reproduce:
1. Right click minimap button to edit button
2. Type in some text in macro field
3. Press esc or "X" button to close without pressing save
4. Things are saved anyways. They are always saved.
5. Contemplate why you clicked save for a hundred times before finding this out

EDIT: Ok it does seem to do something and that is save early and see the change in the action bar. But since you can't actually use the button or flyout menu or see the tooltip in edit mode this doesn't seem to serve any purpose either.

**Comment by ylixir** [comment]
save button is gone!
