### ISSUE TITLE
Checkboxes on macro button options tab steal focus from section tabs

### ISSUE THREAD

**Issue by 4C51** [brittyazel/Neuron#40]
# Steps to reproduce
1. Open the editor for a button
1. Click on Options tab
1. Scroll down so the **_Companion_** and **_Favorites_** checkboxes are out of view
1. Try to click on any of the section buttons

## Related Screenshots
![image](https://user-images.githubusercontent.com/2763410/35079454-77a3e076-fbbc-11e7-9681-2e5ec0c826bc.png)
![image](https://user-images.githubusercontent.com/2763410/35079462-88fbb556-fbbc-11e7-8cab-95d50e56dfda.png)

**Comment by brittyazel** [comment]
Yeah this one is annoying. With the way it's coded I can't figure out how to extend the height of the window to avoid the need for a scroll. I think this one is just going to get passively fixed with a full GUI rewrite honestly.
