### ISSUE TITLE
Status bar settings

### ISSUE THREAD

**Issue by Trajin** [brittyazel/Neuron#406]
i'm probably missing something.  I normally use other addons for my status bars, but I created a status bar, but it looks like it's for xp.   How do I change it to track rep or renown?   Would it be possible to add the ability to set what you want the bar to track or monitor?

Thanks

**Comment by brittyazel** [comment]
This is already possible, albeit a bit unintuitive. Status bars are actually "buttons", so you edit them from the button editor. I.e. activate button edit mode, right click the status button, and you can then change some properties and set it to be either rep, xp, cast, or mirror. Further, if you set it to the XP type, you can have it track Renown, Experience, or Honor by right clicking it (not in bar edit mode), just like how you can switch which rep you are tracking by right clicking.
