### ISSUE TITLE
Add default blizzard action bars?

### ISSUE THREAD

**Issue by GreyFoxGer** [brittyazel/Neuron#412]
Is there a way to add an default blizzard action bars, to be able to stop spell book icon glowing? Like it dominos or bt4 does

**Comment by ylixir** [comment]
you can now use blizzard bars alongside neuron bars which i guess should handle this use case

dominos and bartender use the same action slot mechanism that blizzard bars use, while neuron works in a completely different way, this is probably as good as it's going to get without limiting neurons flexibility

**Comment by AlexFolland** [comment]
I'd like to note that Macaroon had the ability to change the button type of any particular individual button on a Macaroon bar from macro button to Blizzard button, so you could simply change button type to Blizzard button and then everything would work the way Blizzard programmed it.  This was never implemented when Macaroon was rewritten as Ion, unfortunately, even though I made heavy use of it on some characters.  My point is that just being able to not disable the original action bars is not technically as good as it can get.

I'm not making a feature request with this comment; just pointing out a possibility so it's not lost.

**Comment by ylixir** [comment]
yes, actually that is still done. it's how vehicles/possession/etc work. the blizzard bars are sort of projected onto the neuron bars.

the problem isn't really technical, it's ux. neuron bars are basically infinitely flexible while blizzard bars are limited to their 8 or 10 bars of 12 buttons each.

so deciding which neuron buttons correspond to which blizzard buttons isn't an obvious 1:1 mapping. at least it's not apparent to me how to accomplish a nice ux for this without limiting neurons flexibility

**Comment by AlexFolland** [comment]
> the problem isn't really technical, it's ux. neuron bars are basically infinitely flexible while blizzard bars are limited to their 8 or 10 bars of 12 buttons each.

I think you misunderstood what I said if you're saying that.  Macaroon could change individual buttons in its unlimited bars to Blizzard buttons.  Macaroon's code still exists if you wanted to check out how that works.

**Comment by ylixir** [comment]
a screenshot is worth 1000 words ;-) if that code still runs anywhere. if i think that macaroon has a nice ux for that then maybe it would be worth keeping in mind
