### ISSUE TITLE
Scroll does not work for bar list in config.

### ISSUE THREAD

**Issue by Vae2009** [brittyazel/Neuron#416]
*When reporting, please verify the issue with only **this** addon enabled and no others unless explicitly reporting an incompatibility between this addon an another. Likewise, please fill in the below information to the best of your ability — this information helps us a great deal.*

## Issue description:
Scroll does not work for bar list in config.

## How to reproduce:
*E.g., Steps to reproduce the behavior...*
1. *Go to '....'*
2. *Click on '....'*
3. *Scroll down to '....'*
4. *See error*

## Technical info:
 - **Addon Version:** *[e.g., 1.2.1]*
 - **Client:** *[e.g., Retail, Classic, PTR, or Beta]*
 - **Client Patch Version:** *[e.g., 9.0.1]*
 
## Additional context:
*Add any other context about the problem here.*

## Screenshots:
*If applicable, add screenshots to help explain your problem.*

## Lua error log:
*Attach the Lua error log here (please use code tags)*

**Comment by brittyazel** [comment]
Yes this is a known issue and likely won't be fixed until we completely replace the configuration panel in it's entirety with the new GUI. The old GUI is broken beyond repair in many ways, this being one.

**Comment by ylixir** [comment]
gui has been replaced
