### ISSUE TITLE
Anyone else having issues with druid forms breaking bars?

### ISSUE THREAD

**Issue by Sifuedition** [brittyazel/Neuron#417]
I set up 10-11 different classes on 2-4 different specs, recently. I had to drop my healing frames addons due to issues, so I set up a LOT of mouseover macros. Took 24+ hours over two days.
Just went to do my first content since re-configuring Neuron. I'm in feral going to the wold boss. Trash spots me immediately despite stealth and I make a run for it. I used dash, followed by Stampeding Roar. As soon as I hit stampeding roar, my bars went blank. I got into the world boss area and changed spec. I healed the fight, then tried to switch back. Feral bars are not working. Reloadui, nothing. Check the macros, and they are still there, but, nothing displayed, nothing works. I die multiple times and finally get out. Hearth back and the bars are suddenly working again. Now, I just don't know if I can trust the bars...

**Comment by brittyazel** [comment]
It sounds like you are using bar states and don't have them set up correctly. If you have bar states enabled for your druid forms, bear, caster, cat, moonkin, travel, tree, etc will all have their own unique bar contents. 

You were in cat form, the stampeding roar puts in bear form which is an entirely different set of content for the bars. 

If that isn't the explanation, then it seems like some odd bar states are going on. I don't experience these issues and I know lots of other druids who don't either. If you can spot a pattern somewhere in your issue I'm happy to look into it.
