### ISSUE TITLE
Soulshape actionbar state on new actionbar.

### ISSUE THREAD

**Issue by Sifuedition** [brittyazel/Neuron#418]
When reporting, please verify the issue with only **this** addon enabled and no others unless explicitly reporting an incompatibility between this addon an another. Likewise, please fill in the below information to the best of your ability — this information helps us a great deal.*

## Issue description:
Due to issues with the behavior of some more complex macros, I tested out some other actionbar addons. I did not uninstall Neuron, nor disable it. I did delete most of the bars to prevent conflicts, however. Simply put, there IS NO REPLACEMENT for Neuron. Thank you so much for this addon. It truly enhances my experience of the game.

Now, I've recreated my primary actionbar and almost everything is working normally. The one thing that is not is the Kyrian covenant ability soulshape. It used to activate a separate actionbar state. The new bar I created is not creating the state for this so it is remaining on the default caster actionbar state.

I have tested with only Neuron, bugsack and buggrabber enabled.

## Technical info:
 - **Addon Version:** 1.4.4 (Curseforge)
 - **Client:** Retail
 - **Client Patch Version:** 0.9.11 (In-game)
 
## Screenshots:
![image](https://user-images.githubusercontent.com/40223388/108128055-d27db080-7071-11eb-898f-b6468bceae4c.png)
![image](https://user-images.githubusercontent.com/40223388/108128170-f5a86000-7071-11eb-8cc5-130f6793047d.png)

## Lua error log:
*Attach the Lua error log here (please use code tags)*
None

**Comment by ylixir** [comment]
i'm a little fuzzy on what is supposed to happen here? do we expect soulshape supposed to show up as another shapeshift bar? i think we currently cap out at 6 or 7 stances. do you think this was related to learning new forms like treant or mount?

if this is still an issue for you @Sifuedition it's probably easy to fix, but otherwise i think i will close this since shadowlands is behind us now!

**Comment by AlexFolland** [comment]
An expansion is never "behind us now".  Its mechanics will come back with Classic, and its content still exists in-game.

**Comment by ylixir** [comment]
i'm closing this since soulshape is now a toy instead of a game mechanic
