### ISSUE TITLE
UI glitch when toggling Multi Spec on or off

### ISSUE THREAD

**Issue by 4C51** [brittyazel/Neuron#42]
# Steps to reproduce
1. Edit a bar with more than one button
1. Turn on/off Multi Spec
1. Button outlines disappear
1. _Increasing_ but _**not**_ _decreasing_ the number of buttons will reset the outlines

## Related Screenshots
Multi Spec toggled
![image](https://user-images.githubusercontent.com/2763410/35079706-05af9f6c-fbbe-11e7-9a4e-8708c60e9c68.png) 

Button count increased
![image](https://user-images.githubusercontent.com/2763410/35079713-104bccac-fbbe-11e7-90f2-24dd659428cd.png)

**Comment by brittyazel** [comment]
is this with or without show grid enabled?

**Comment by 4C51** [comment]
Without, it does not occur when Show Grid is enabled. It seems as though maybe the button outlines should be hidden when Show Grid is disabled and this is a side effect of that state being off?

**Comment by brittyazel** [comment]
So the glitch you are reporting is that the buttons DO go away even though bar edit mode is still enabled ;-) It's a reverse bug report!

**Comment by 4C51** [comment]
That does seem to be the case! So when toggling Multi Spec while in bar configuration mode with Show Grid disabled it hides the grid.

**Comment by brittyazel** [comment]
Yeah that shouldn't happen. The grid should stay visible as long as bar edit mode is active, and toggling Multi Spec should not affect this whatsoever
