### ISSUE TITLE
How to create new bar

### ISSUE THREAD

**Issue by hasnogaems** [brittyazel/Neuron#426]
Where the option for it hidden

**Comment by jpmeyers** [comment]
if you have the Neuron mini-map button enabled, you just left click on it
to enter the Configuration mode, then right click on any existing bar to
bring up the configuration menu. In the lower left corner is a button to
Create New Bar.

if you don't have the mini-map button available, you can just type "/neuron
config" in the chat to enter Configuration mode, the rest is as above.

**Comment by Ketrel** [comment]
If you deleted all your bars, and don't have anything to click in config mode

`/neuron create ActionBar`

**Comment by hasnogaems** [comment]
Thanks guys. Can I create multi row bars?

**Comment by hasnogaems** [comment]
Thanks!

**Comment by Ketrel** [comment]
(worth mentioning that "ActionBar" is case sensitive in that command)

**Comment by ylixir** [comment]
this looks like it's handled (and the ui is different now anyhow)
