### ISSUE TITLE
Display Minimap Button checkbox has reversed functionality when toggling

### ISSUE THREAD

**Issue by 4C51** [brittyazel/Neuron#43]
Checking **Display Minimap Button** within the general options hides the minimap button, unchecking it shows it.

**_Except_** when loading/reloading the UI, where it accurately reflects the checkbox state.

**Comment by brittyazel** [comment]
Yeah I'll fix that, the button seems to get confused

**Comment by brittyazel** [comment]
Fixed on conversion to LibDBIcon
