### ISSUE TITLE
Framedrops @ mouseover an NPC or Player

### ISSUE THREAD

**Issue by Solithe** [brittyazel/Neuron#433]
Hey Soyier,

I have a strange problem when playing WoW with Neuron.
Every time I  mouseover a player or NPC, I have framedrops.

When I mouseover other players, for example in Oribos, my frames break from ~ 100 down to ~ 20.
The more players I run over, the lower the fps

I disabled all of my addons.
If I only activate Neuron, I have the lags.
No other addon caused these drops.
There are no error messages.
I am now 100% sure that it comes from Neuron

greetings
Soli

**Comment by Solithe** [comment]
I'm desperate.
I have this fps drops only with my main lvl 60 priest.
All of my other characters under 60 don't have these problems.
I have created a completely new profile with my lvl 60 priest and I have the same problem. I initially thought of a range error when players are out of my heal range, but with my lvl 50 priest I don't have the problem.
I've tried all 20 lvl 50 characters. no problem.
It's very frustrating


Retail wow Patch 9.1.5
Neuron Version 1.4.11

**Comment by brittyazel** [comment]
So this issue is only on one of your characters? That's really bizarre, and you're the only person to report this. I've been trying to replicate it as well, but I'm unable to. Likewise, there's really nothing in the Neuron code that should do much of anything involving mousing over players and npcs. That's not really something Neuron handles.

Can you tell me more about your setup and config? I'm somewhat blind here

**Comment by Solithe** [comment]
Yeah, only my main have this issue.
i make 2 Videos. First without any addons. In the secound Video is only Neuron aktiv.

https://youtu.be/vU0ay7FILiQ
https://youtu.be/wlCqZm4LIwI

**Comment by brittyazel** [comment]
Strange. Question, I noticed in the second video that you didn't have any target selected, yet the buttons were flashing red to indicate out of range. Do you have some sort of mouseover select enabled? The only thing that I can think is that Neuron is doing a range check query and whatever is switching your selected target on mouseover is overwhelming.

**Comment by Solithe** [comment]
When I have fewer symbols in my bars, I have more fps when I hover over a character with the mouse
Maybe it has something to do with my mouseover macro

/cast[@mouseover,help][]spellname()


or do I have too many symbols in my bars?

**Comment by Solithe** [comment]
Oh didn't see that you already answered =)

**Comment by Solithe** [comment]
I also have the Issue, when i´m in range and when i delete all mouseover buttons

**Comment by Solithe** [comment]
only when i reduce my symbols it gets better

**Comment by Solithe** [comment]
https://youtu.be/J1CFtL9y7eQ  (lvl 50 Druid with mouseover Makros and full addons without Issue)

https://youtu.be/yDVe5GO7hG4 (2nd Priest lvl 50 with same Profil as my lvl 60 Priest and full addons with no issue)

All my chars have the same aktiv addon pack

**Comment by Solithe** [comment]
Last Video:

https://youtu.be/LP2f3hsur2c

lvl 60 Priest with all Addons. Please look at the fps in the top left


=(((

**Comment by Solithe** [comment]
sorry but neuron is the best addon and i don't want to lose it

**Comment by brittyazel** [comment]
This is really bizarre. I'll look into it, but I'm entirely confused why the issue is only on one of your characters.

**Comment by brittyazel** [comment]
When did this start happening?

**Comment by Solithe** [comment]
immediately after logging in


i tried again to leave all addons switched on except neuron.
no fps drops.
When I reactivate neuron I have the issue again

maybe this is due to the German client?


On Saturday I will try to completely delete Neuron and reset everything. From zero and start with the main priest.
but make a backup =)

**Comment by Solithe** [comment]
complete neuron deleted, all settings deleted and reinstalled (1.4.11)
lvl 60 Priest main char, empty profile -> ~ -10 fps @mouseover chars in Orgrimmar
lvl 60 Priest, bars configured but with empty buttons ~ -10 to -20 fps @mousover chars in Orgrimmar
lvl 60 priest, bars configured with complete spells ~ - 30 to -45 fps @ mousover chars in orgimmer


same with a lvl 50 hunter:
no fps change


maybe it has something to do with the maximum lvl or with the covenants?

I'm running out of options

**Comment by Solithe** [comment]
I tried another Action Bar add-on (Ba******4) and didn't have any problems, but don't want to change,  because it doesn't support everything I like about neuron

**Comment by brittyazel** [comment]
I'll do my best to try to help you out here, but this is very very odd. This might be the most peculiar bug I've ever had reported to me. 

Give me a few days (sorry I know this is urgent for you), and I'll see what I can come up with. I'm 2 days away from graduating with my PhD so I'm scrambling to finish my dissertation at the immediate moment. Once that's over with though I'll gladly dive into the code

**Comment by Solithe** [comment]
I'm sorry, if i have left the impression that it is urgent for me. That's not the case. I just want to help with my reports to find the bug =)

You don't need to stress yourself.
RL first

**Comment by AlexFolland** [comment]
"I'm desperate" and "I'm running out of options" make it sound urgent.

Can you please try running [FunctionProfiler](https://www.curseforge.com/wow/addons/fprof), resetting it using its command line options in your chat window, then immediately mousing over a character?  FunctionProfiler will then populate with the functions which have spent the most CPU time.  Please reset FunctionProfiler, then after about 5 seconds of rapidly mousing over a character and then nothing, and back, take a screenshot of each of the 4 graphs FunctionProfiler provides (click its interface to cycle through them).

**Comment by Solithe** [comment]
I hope I got that right

[https://drive.google.com/file/d/1bYRt5j1MDr9sX-oOORWnOysREjoiYu5-/view](url)

**Comment by AlexFolland** [comment]
You have Outfitter enabled, and I'm not sure what other addons.  Also, it looks like you checked immediately after the reset without mousing over the NPC and off it a few times first to see the frame drops.  Please enable only FunctionProfiler and Neuron, then do it again with mousing over the NPC and back and forth a bunch of times for about 5-10 seconds after the reset before taking screenshots.  Thanks!

**Comment by Solithe** [comment]
the only difference i have seen between mouseover and no mouseover is in Inclusive Time

https://drive.google.com/file/d/12oL09QPImqnG7XfvR-NndpsVpfXHD5_4/view?usp=sharing

**Comment by Solithe** [comment]
By the way, many thanks for the help and support.

**Comment by AlexFolland** [comment]
Okay, so it looks like the lag is happening in AceEvent or something that it calls.  This sounds to me like it's happening when a particular event fires.  Can you please try typing `/eventtrace` into the chat box, then mousing over the NPC a bunch of times to see what events are firing, and take a screenshot of the resulting event trace window?

**Comment by Solithe** [comment]
https://drive.google.com/file/d/1mHs56j1Jev8XevZ3gtDmVFc9b40cn2Lu/view?usp=sharing      Issue Charakter

https://drive.google.com/file/d/1BIWouw9cNSmpLIF8IUfu8espdzku4htV/view?usp=sharing       other

**Comment by Solithe** [comment]
OK I got it.
I deleted all spells in the standard ui bar from wow and then loaded Neuron. All errors are gone and the fps are stable.

Thank you so much for the great help AlexFolland.
Without FunctionsProfiler and / eventrace it would not have been possible to solve it so quickly. I have to remember next time.

And also many thanks to Soyier (brittyazel)
Thank you for taking over the add-on and taking so much time. Wasn't the first time I needed your help.

I hope I don't need the help anymore =)

Stay safe, Merry Christmas and a Happy New Year.

**Comment by AlexFolland** [comment]
That's very interesting.  I haven't thought at all about what random junk is on my default UI bars and I've had some unexplainable frame drops in the past myself.  I'll have to strip all my default UI bars some time, since I haven't used them since 2008 when I started using Macaroon.

**Comment by Solithe** [comment]
i haven't had any problems like this until shadowlands. Until a week ago I had a 2 month break. Maybe it had something to do with pach 9.1.5

**Comment by AlexFolland** [comment]
That's good to know anyway, in case I see something like that if I start to play mainline WoW instead of classic again.  I'm glad it's mostly solved.  It still would be good to know what abilit(y/ies) could possibly cause this though.

**Comment by Solithe** [comment]
Renew was 1, Flash Heal 2, Greater Heal 3, Prayer of Healing 5.
I can't remember the rest of it.

I started with macaroon, too. Playing wow since Vanilla Beta. Long long ago. Time is running so fast . 
But that's not the topic =)

**Comment by Ketrel** [comment]
I have similar issues.  It seems to come from rangechecks.

I turned off range on all the bars that it wasn't necessary on and the frame drop reduced, but as I have 4-5 bars that require range checks on the ability it didn't go away entirely.

That seems to be where the biggest drop comes from for me.

**Comment by AlexFolland** [comment]
This ticket is closed because the issue was not with Neuron.  Please read all comments to follow the resolution to its conclusion.
