### ISSUE TITLE
Make it easier to toggle between bar configuration and button configuration

### ISSUE THREAD

**Issue by 4C51** [brittyazel/Neuron#44]
Currently you have to use either a chat command (or macro), data broker, or minimap button to switch between bar configuration and button configuration.

Having either a button on each of the respective windows and/or a separate window that allows switching modes would make it easier to quickly go back and forth, or perhaps a shared mode with different mouse clicks/UI elements to manipulate each.

**Comment by brittyazel** [comment]
Yep, this will be part of the GUI rework

**Comment by brittyazel** [comment]
The new GUI will not have separate bar and button windows, but one window that holds all the relevant settings
