### ISSUE TITLE
For Classic TBC, much broken after update Sept 1-2 2022

### ISSUE THREAD

**Issue by teh-fixerer** [brittyazel/Neuron#443]
Wow Classic Lich King, Pre-patch
On any character (level 2 warrior)
Is it worth fixing for TBC players like me?

Errors:
=====
Error 1
====
Message: Interface\AddOns\Neuron\Neuron-GUI.lua:102: Cannot find a library instance of "LibDualSpec-1.0".
Time: Fri Sep  2 21:07:29 2022
Count: 1
Stack: Interface\AddOns\Neuron\Neuron-GUI.lua:102: Cannot find a library instance of "LibDualSpec-1.0".
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\Neuron\Libs\LibStub\LibStub.lua"]:23: in function `LibStub'
[string "@Interface\AddOns\Neuron\Neuron-GUI.lua"]:102: in function <Interface\AddOns\Neuron\Neuron-GUI.lua:84>
[string "=[C]"]: ?
[string "@Interface\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:623: in function <...ace\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>
======
Error 2
======
Message: Interface\AddOns\Neuron\Neuron.lua:207: attempt to call global 'GetSpecialization' (a nil value)
Time: Fri Sep  2 21:07:32 2022
Count: 1
Stack: Interface\AddOns\Neuron\Neuron.lua:207: attempt to call global 'GetSpecialization' (a nil value)
[string "@Interface\AddOns\Neuron\Neuron.lua"]:207: in function <Interface\AddOns\Neuron\Neuron.lua:172>
[string "=[C]"]: ?
[string "@Interface\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

===
Error 3
===
Message: ...ace\AddOns\Neuron\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "PLAYER_SPECIALIZATION_CHANGED"
Time: Fri Sep  2 21:07:32 2022
Count: 1
Stack: ...ace\AddOns\Neuron\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "PLAYER_SPECIALIZATION_CHANGED"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\Neuron\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Interface\AddOns\Neuron\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:142: in function `RegisterEvent'
[string "@Interface\AddOns\Neuron\Neuron-GUI.lua"]:135: in function <Interface\AddOns\Neuron\Neuron-GUI.lua:121>
[string "=[C]"]: ?
[string "@Interface\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

===
error 4, 2 instances
====
Message: Interface\AddOns\Neuron\Neuron.lua:443: attempt to call global 'GetProfessions' (a nil value)
Time: Fri Sep  2 21:07:32 2022
Count: 1
Stack: Interface\AddOns\Neuron\Neuron.lua:443: attempt to call global 'GetProfessions' (a nil value)
[string "@Interface\AddOns\Neuron\Neuron.lua"]:443: in function `UpdateSpellCache'
[string "@Interface\AddOns\Neuron\Neuron.lua"]:247: in function `?'
[string "@Interface\AddOns\Neuron\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ron\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Neuron\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ron\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Neuron\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Neuron\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...ace\AddOns\Neuron\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

===
error 5
====
Message: Interface\AddOns\Neuron\Neuron-GUI.lua:3064: attempt to index field 'ACTIONBUTTON' (a nil value)
Time: Fri Sep  2 21:07:32 2022
Count: 1
Stack: Interface\AddOns\Neuron\Neuron-GUI.lua:3064: attempt to index field 'ACTIONBUTTON' (a nil value)
[string "@Interface\AddOns\Neuron\Neuron-GUI.lua"]:3064: in function `ButtonEditor_OnLoad'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals: self = <table> {
 SubFrameHoneycombBackdrop_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:240
 BarListScrollFrameUpdate = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1116
 updateIconList = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2833
 modules = <table> {
 }
 BarEditor_DeleteBar = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1236
 NeuronPanelTemplates_DeselectTab = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:292
 flyoutTypeSetter = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3584
 visOptionOnClick = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1540
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 NeuronPanelTemplates_TabResize = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:328
 VisEditorScrollFrame_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1926
 IsEnabled = <function> defined @Interface\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ObjEditor_OnClick = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3986
 ActionListScrollFrameUpdate = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2396
 hookHandler = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3519
 ADDON_LOADED = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:163
 RegisterMessage = <function> defined @Interface\AddOns\Neuron\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Neuron\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 MainMenu_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3506
 hooks = <table> {
 }
 BarOptions_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1301
 runUpdater = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3536
 ObjEditor_OnEnter = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3966
 macroIconOnClick = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2814
 SetEnabledState = <function> defined @Interface\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Interface\AddOns\Neuron\Libs\AceHook-3.0\AceHook-3.0.lua:274
 macroNoteEdit_OnTextChanged = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2774
 ColorPicker_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:3482
 SubFrameBlankBackdrop_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:226
 sbTypeOnClick = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:4243
 SecondaryPresetsScrollFrameUpdate = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2128
 updateCustomState = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:854
 ObjectEditor_OnShow = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:2265
 target_options = <table> {
 }
 BarEditor_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:886
 NewModule = <function> defined @Interface\AddOns\Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 EditBox_PopUpInitialize = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:387
 DeleteButton_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1227
 remapOnTextChanged = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1669
 BarList_OnLoad = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:1001
 PLAYER_SPECIALIZATION_CHANGED = <function> defined @Interface\AddOns\Neuron\Neuron-GUI.lua:156
 GetName = <function> defined @Interface\Add

**Comment by brittyazel** [comment]
I'll download now and see what I can do. Should be straightforward to fix, hopefully.

**Comment by brittyazel** [comment]
This should be fixed. I just released a new version. Please test :-)
