### ISSUE TITLE
WotLK Totem Bar

### ISSUE THREAD

**Issue by AlexFolland** [brittyazel/Neuron#444]
## Is your feature request related to a problem? Please describe:

In WotLK Classic, the only way to configure which totems are used in the totem call spells such as Call of the Ancestors is by enabling the default Blizzard action bars, which requires reloading the UI.

## Describe the solution you'd like to see implemented:

Being able to add a Neuron "Totem Bar" type which reproduces exactly what the default UI's totem bar does would be ideal.

## Describe alternatives you've considered:

I have used the default UI workaround, which is inconvenient.

## Additional context:

Macaroon had this feature back in the day.  I realize Neuron is based on Ion which is a rewrite of Macaroon from scratch, so it doesn't have all of Macaroon's features.

**Comment by ylixir** [comment]
i'm pretty sure i just came across the code that disables this bar. while i have no plans to reimplement this bar in the near term, i will comment out the code that disables it so that wrath shamans at least can access it.

**Comment by AlexFolland** [comment]
That's awesome!  Is that done and ready for testing?

**Comment by ylixir** [comment]
its in #462

**Comment by ylixir** [comment]
> its in #462
which come to think of it, probably has a broken cast bar in wrath. fix just pushed

**Comment by ylixir** [comment]
that code has been merged into neuronnext now

**Comment by ylixir** [comment]
Have you had a chance to check this out @AlexFolland ? `NeuronNext` is now `main` btw

**Comment by AlexFolland** [comment]
No, not yet.  I will check it probably in the next week.

**Comment by AlexFolland** [comment]
For me, switching to that branch depends on https://github.com/brittyazel/Neuron/issues/362 being fixed.  The current branch I'm using is working well for me, and backing up and restoring my configuration is a bit of a hassle.  I'd like to switch when all known issues are resolved.

**Comment by ylixir** [comment]
alright. marking as complete for now in order to tame the backlog. if this is still an issue after we resolve the other item then we can create a new issue at that point

**Comment by AlexFolland** [comment]
If it's not tested, how is it "tame"?
