### ISSUE TITLE
WoTLK Dual Spec

### ISSUE THREAD

**Issue by Vequis-uk** [brittyazel/Neuron#445]
Hey,

I am a junior developer and was wondering if you could potentially help me to implement the feature to "change" the bars depending on if you are in spec 1 or spec 2 aka dual spec in WoTLK.

I have had a quick look through the code (to try and make a macro to swap profiles) and after a quick look I cannot see if it is possible to make such a macro, I assume it would just need to call a function and pass the profile name as a property?

Either way if you could help with either of the two solutions / problems above it would be greatly appreciated.

Look forward to hearing from you

Regards,
David

EDIT: I see that it is using the dual spec and ace libraries, perhaps it is these that require an update for this to work?

**Comment by ylixir** [comment]
I don't play classic, but this feature does work in retail, but you have to turn it on from the profiles section of the settings. Have you tried that?

If that doesn't work, you could just macro it like this: `/cast [spec:1]Spell A;[spec:2]Spell B`

**Comment by Vequis-uk** [comment]
I will double check that tonight but I am sure I turned it on. I think the issue with classic is you are just changing talents effectively, where as retail its actually Destruction or Affliction etc.

Ah I will see if that macro will work, that may be a work around.

Do you know if it is possible to change the profile based on macro? I am happy to do it that way, I did look through the code but could not decipher a profile swapping section

**Comment by brittyazel** [comment]
There are indeed some conditional checks for classic that need to be adjusted for WotLK. I haven't had a chance to do so yet (I also don't play Classic).

**Comment by Vequis-uk** [comment]
Ah ok, nice one. Really appreciate your time on the application all. I have used Neuron for... I do not know how long and honestly there is not another addon that provides what this does. Most intrude into the stock UI too much.

Anyway, keep up the great work :)

**Comment by ylixir** [comment]
@Vequis-uk can you try out this branch and see if dual spec works for you? https://github.com/ylixir/Neuron/tree/bikeshedding

**Comment by Vequis-uk** [comment]
> @Vequis-uk can you try out this branch and see if dual spec works for you? https://github.com/ylixir/Neuron/tree/bikeshedding

Hey I am very sorry I have only just seen this. The link does not work do you have a new one I can try please? Very sorry I get way too many emails....

**Comment by ylixir** [comment]
That code has been merged into NeuronNext now. If you are good with git, you can check out that branch.

If not, you can downlod it. I put a link in the discussions section of this repo.

**Comment by Vequis-uk** [comment]
Nice one, thanks a lot, I will test that out tonight after work and let you know, really do appreciate it 👍

**Comment by Vequis-uk** [comment]
It would appear using this version causes it to not load on classic sadly, I will do some more testing tonight, see if there are LUA errors etc

**Comment by ylixir** [comment]
You have to make sure that the folder name for the addon matches the name of the Neuron.toc file. You may also have to change the `## Interface: 100000` line to `##Interface: 30400`

**Comment by Vequis-uk** [comment]
Ah I see I changed the file name and the interface and it worked - but it seems like the interface menu is different etc. I tried dual spec and it did not swap sadly.

**Comment by Vequis-uk** [comment]
Ah ok, let me try that actually, I will test it now

**Comment by Vequis-uk** [comment]
Ah yes sorry you are correct, I did not have the multi-spec checked. It is swapping the bars between specs with that selected and it did work! Super, at least it is working on this branch :)

**Comment by ylixir** [comment]
`NeuronNext` is now [`main`](https://github.com/brittyazel/Neuron/archive/refs/heads/main.zip) btw, if you want to track the current progress.
