### ISSUE TITLE
Possess and Vehicle Bar Not working in DF Pre-Patch 10.0.0

### ISSUE THREAD

**Issue by Ketrel** [brittyazel/Neuron#449]
## Issue description:
Possess bar override doesn't appear to work in Path of Ascension / or Vehicles (possibly other places)

## How to reproduce:
*E.g., Steps to reproduce the behavior...*
1. ensure your bar is set for vehicle and possession override
2. Select your soulbind in path of ascension / or vehicle in ulduar (place I tested) 

## Technical info:
 - **Addon Version:** 2601463
 - **Client:* Retail 10.0.0.46366
 
## Additional context:
Adding in a couple of debug statements shows that in path of ascension the bar state is 'possess1'

## Screenshots:
Would just be empty space

## Lua error log:
no lua error produced

**Comment by brittyazel** [comment]
The dragonflight branch has been completely replaced the NeuronNext branch at this point. This fix has (theoretically) been integrated into the NeuronNext branch. The plan is to not do any more releases until NeuronNext is ready to ship, which will include breaking changes and no guarantees on profile stability until the release is minted.

**Comment by Ketrel** [comment]
What should be used currently for 10.0.0?  The NeuronNext branch as is doesn't appear functional.

**Comment by brittyazel** [comment]
As stated on the Curseforge and Wowinterface pages, Neuron development is on indefinitely hiatus. Development on NeuronNext is continuing in response to a community developer stepping up to help out, but legacy Neuron pre-10.0 is no longer being supported.

**Comment by Ketrel** [comment]
Ah gotcha.  I've never grabbed it from there, I've been using it straight from github.

**Comment by ylixir** [comment]
@Ketrel tje next branch works for me. Have you tried it in the last few days? It had a lot of updates the other day

**Comment by Ketrel** [comment]
@ylixir yes, I tried it yesterday.  Last commits were Oct 31.

Immediately I saw bars that should be invisible when no modifier keys were pressed were visible all the time, (paged settings still worked) but the actual settings section to control visibility and states is blank in settings, so I don't think that it's usable yet.
