### ISSUE TITLE
Question about Neuron ,future and dragonflight?

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#451]
First of all thank you for all the work you have done to keep this addon alive up to this point. I have seen that you have put Neuron on hiatus  for forsiable future but since then i have seen recent commits done to Neuron next . I just wanted to know what does that mean for future of Neuron ? Is perhaps Ylixir someone that might take over Neuron and continue to keep it alive  since new commits that are merged are his?

**Comment by AlexFolland** [comment]
This is not an issue and I recommend closing it and reposting in Discussions.

![image](https://user-images.githubusercontent.com/601517/200076405-05975657-e473-4b2c-8339-4b82974c66f7.png)

**Comment by brittyazel** [comment]
Yes please open this over as a Discussion, thanks!
