### ISSUE TITLE
Bars showing when they shouldn't

### ISSUE THREAD

**Issue by ylixir** [brittyazel/Neuron#458]
Immediately I saw bars that should be invisible when no modifier keys were pressed were visible all the time, (paged settings still worked) but the actual settings section to control visibility and states is blank in settings, so I don't think that it's usable yet.

_Originally posted by @Ketrel in https://github.com/brittyazel/Neuron/issues/449#issuecomment-1301291407_

Just creating this issue to keep track of the thing about hidden bars showing when they shouldn't (modifier bar/buttons or override stuff?)

**Comment by Ketrel** [comment]
Few clarifications to this if it's going to be standalone.

1. Paged bars (including bars that are invisible on page 1 but not page 2) work correctly.
2. Bars that rely on modifier keys (for example, my toys bar should only show if Ctrl + Shift is pressed) shows all the time.  
3. 2. The Strata doesn't seem to be honored for these bars either (DragonFlight branch, it shows above chat, NeuronNext branch it shows behind chat)
4. The actual menus to modify these settings (States and Visibility) appear as blank tabs (this may not be a bug but just an incomplete UI)

**Comment by ylixir** [comment]
@Ketrel NeuronNext has been given some love with regards to the bar visibility. Can you check and see if it's working better for you?

Haven't looked at the strata yet, but the visibility should hopefully be squared away

**Comment by Ketrel** [comment]
1. Paged visibility still working  
2. Modifier based visibility looks like it's working now  
3. Strata is still an issue, but that's expected at this point.  
4. The menus appear to be there and working (I just did a quick once over, didn't try changing any settings)  

Yep, looks like the only thing sill pending is Strata.  All the other visibility issues look good now!

**Comment by ylixir** [comment]
So I just spent some time messing with the strata, and I can't reproduce the issues you are seeing. Here is what I did:

1. moved an action bar to cover the chat frame. It was at medium strata and below the chat frame
2. changed it to high and it moved above the chat frame.
3. changed it to only show when shift is down and reloaded the ui
4. it's still above the frame, so move it to medium and it moves below the chat frame

Can you provide more details about the circumstances under which it doesn't work, or maybe post a minimal config that reproduces it? (can copy paste from the experimental section in settings)

**Comment by ylixir** [comment]
`NeuronNext` is now `main` btw

**Comment by Ketrel** [comment]
Both of these pics have the strata set to medium.

Dragonflight branch  
![neuron-df](https://user-images.githubusercontent.com/1002607/204156084-3d3c73fc-9ee6-463a-b951-044365db1b5e.png)

NeuronNext/Main branch
![neuron-main](https://user-images.githubusercontent.com/1002607/204156088-7d4260a6-ead9-434a-b5b9-f74147a60742.png)

**Comment by ylixir** [comment]
if you change it to high does it move in front of the chat frame?

i'm not that worried if something super vague like "medium" isn't exactly the same. as long as you can get it to be where you want by changing the setting

**Comment by Ketrel** [comment]
Yes, if I change it to high it goes in front of the chatbox.

Since the various strata are blizzard constants, I think medium is removed/broken as it evaluates to nil, not the words like the rest do.  `/run print(HIGH)` returns `High` for example, while MEDIUM returns nil.

Also, the lua errors I'm getting, I'll open a separate issue as it doesn't appear to be related to any of this.

**Comment by ylixir** [comment]
here the top bar with time warp is medium strata and the bottom bar is low
![image](https://user-images.githubusercontent.com/6045286/204180146-0619c558-aed2-4da9-ad46-947529923382.png)

now with the bottom bar set to high, and the top bar still set to medium
![image](https://user-images.githubusercontent.com/6045286/204180228-2cf8de64-143e-40f1-9c6d-bd53c8e2c6eb.png)

there are no blizzard constants in the code, just the numbers 2-6. there is some weird code in neuron legacy that randomly adds one to the strata. maybe that logic caused this inconsistency? but  is fine with me.

let's think of deleting pointless and confusing code as fixing the bug where it had the wrong strata before and now it has the correct strata 🎊  ;-)

since strata seems to be working fine, i'm going to close this issue
