### ISSUE TITLE
New bars are hard to find in the bar list

### ISSUE THREAD

**Issue by 4C51** [brittyazel/Neuron#46]
When creating new bars they get named and numbered in a generic fashion that can be hard to find if you aren't keeping track of how many of each you have.

Choosing a name before hand or automatically selecting new bars would make them easier to find.

**Comment by brittyazel** [comment]
Yep, will be in the GUI rework :-)

Should I just make a GUI rework ideas bug and you can just add all your ideas there? lol

**Comment by 4C51** [comment]
Hah, that would probably work :)

**Comment by brittyazel** [comment]
Ok I made a bug to fit all these GUI ideas in. And I'll just check them off one at a time

**Comment by brittyazel** [comment]
Can you move all your bugs there and close these ones. It'll be easier to track
