### ISSUE TITLE
Function removes ability to use alongside Blizzard bars

### ISSUE THREAD

**Issue by Ketrel** [brittyazel/Neuron#476]
## Issue description:
*A clear and concise description of what the issue is (i.e. what went wrong and what should have happened).*

## How to reproduce:
1. Enable Blizzard Action bars in Neuron options
2. Try to make Neuron bars

## Technical info:
 - **Addon Version:** commit 6d8a8c3
 - **Client:** Retail
 - **Client Patch Version:** 10.0.2
 
## Additional context:
Looks like it's from this section in Neuron-Startup.lua (lines 58-65)  
```lua  
    -- remove blizzard controlled bars from the list of bars we will create
    local neuronBars =
        Array.filter(
            function (barPair)
                local bar, _ = unpack(barPair)
              return not profileData.blizzBars[bar]
            end,
        Array.fromIterator(pairs(Neuron.registeredBarData)))  
```
I'm not sure if this is to prevent a conflict but I came across this while trying to research another bug which I'll file separately but am trying to find a fix for first. 

Either way this section is what's preventing using the two in tandem.  

I would suggest doing  

```lua  
local neuronBars = Array.fromIterator(pairs(Neuron.registeredBarData))  
``` 

Instead unless there's specific conflicts of other bar types in which case, don't filter out the ones that can co-exist like actionbars.

**Comment by ylixir** [comment]
i knew this was coming 😆

this is intentional, but i have thought about circling back around and allowing both kinds of action bars, or maybe just never disabling the neuron action bars.

is there a use case for using both neuron and blizzard for any of the other bars besides the action bars?

**Comment by Ketrel** [comment]
On some toons, I use more of the default UI, but still like to add extra bars with page/modifier based visibility, things like a 9x9 grid for mounts that only shows on page 2, or things like that.

I actually have a bar for addon tweaks that has a bunch of macros that let me run commands on other addons.  

Why not make two checkboxes.  Show Blizzard's + Disable Neuron's  
That'll give every possible use case a winning setup.  I could probably hack that together as a pull request if I get some time.

**Comment by AlexFolland** [comment]
> is there a use case for using both neuron and blizzard for any of the other bars besides the action bars? is there a use case for using neuron without having the neuron action bars available?

Yes.  Macaroon, Ion, and Neuron have always advertised coexistence with any and all other action bar addons, including the default UI.  I have personally used this as a way to advertise Neuron to others, telling them they don't have to destroy their current UI to just add some macro buttons on a bar.  A friend of mine uses a Neuron bar with just a few buttons to augment the default UI to this day.

**Comment by ylixir** [comment]
that's literally the use case that we are talking about. are there any _other_ use cases for neuron bars to coexist with other bars besides action bars.

for instance: why on earth would someone want both blizzard and neuron exp bars? or both blizzard and neuron cast bars?

**Comment by brittyazel** [comment]
The new blizzard cast bars and mirror bars look quite nice, I could see myself using those. (particularly now since the Neuron cast bar doesn't work with charged abilities yet). The Blizz bag and menu bars are also fine, IMO. I could see a lot of people just using the stock bag and menu bars. This could equally be true for the Blizz Zone Ability/Extra bars. Theirs is equally as configurable as ours, so some may just opt for the Blizz bars there.

**Comment by Addonman** [comment]
I hope you leave those bag,menu, zone ,extra bar in since blizz ui is not that good.

**Comment by Ketrel** [comment]
> I hope you leave those bag,menu, zone ,extra bar in since blizz ui is not that good.

You should be good.  The change allows both Blizz + Neuron actionbars to coexist, it didn't remove anything from Neuron just let both bar types show at once.
