### ISSUE TITLE
Missing Group Finder Eye

### ISSUE THREAD

**Issue by TruthNZ** [brittyazel/Neuron#485]
## Issue description:
The Group Finder Eye is no longer part of the minimap, but now part of the default Blizzard Bag Bar. Unfortunately the Neuron one appears to not be showing the Eye when searching for groups, waiting a queue, etc.

## How to reproduce:
Enable Neuron.
Search for a Group (e.g. LFG, Heroic dungeon, etc.).

## Technical info:
Addon: Main Branch at commit [[ec7deaf]](https://github.com/brittyazel/Neuron/commit/ec7deaf06c1132087aac8c27500025fc36546762)
Client: Retail 10.0.2.46924

**Comment by brittyazel** [comment]
To clarify, the issue is that the Neuron bag bar does not show the LFG (search) eye, and the request is that we add that functionality?

**Comment by TruthNZ** [comment]
Or make it viewable in some fashion with Neuron enabled.

**Comment by ylixir** [comment]
i was wondering where that went. the bag bar? really?

this really makes me want to cut loose the bag bar and the microbuttons honestly
