### ISSUE TITLE
Vehicle/Possession buttons not showing

### ISSUE THREAD

**Issue by TruthNZ** [brittyazel/Neuron#486]
## Issue description:
When using a Vehicle or Possession (hard to tell which is at any given instance, might be on both), the buttons image is missing. Mouseover still works, as does the button itself.

## How to reproduce:
Enable Neuron. Set Bar State to include Vehicle and Possess.
Use a Vehicle.

## Technical info:
Addon: Main Branch at commit [[ec7deaf]](https://github.com/brittyazel/Neuron/commit/ec7deaf06c1132087aac8c27500025fc36546762)
Client: Retail 10.0.2.46924

**Comment by ylixir** [comment]
i love how you included the commit! 🔥
