### ISSUE TITLE
Hidden state for Bag & Menu bars doesn't persist

### ISSUE THREAD

**Issue by 4C51** [brittyazel/Neuron#50]
# Steps to reproduce
1. Have Bag and/or Menu bars
1. Check hidden for either/both
1. Reload client or UI
1. Bars reappear, hidden is unchecked in options

## Additional Notes
Other bar types seem unaffected by this
Occurs on both default bars and newly created bars

**Comment by brittyazel** [comment]
ok cool thanks, I'll fix this. I want to unify the settings between all the different modules, right now they're all somewhat independently configured, thus why it works on some but not others.

**Comment by raysmith59** [comment]
I was going to report this for the cast bar, it's exhibiting the same behaviour.

**Comment by brittyazel** [comment]
Is this still happening?
