### ISSUE TITLE
10.0.5 broke bars edit -prealpha version

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#503]
Count: 1
Message: Interface/AddOns/Neuron/Objects/MenuButton.lua line 58:
   Usage: RawHook([object], method, [handler], [hookSecure]): Attempting to hook a non existing target
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua"]:210:
      Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:118
   [string "@Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua"]:321: RawHook()
   [string "@Interface/AddOns/Neuron/Objects/MenuButton.lua"]:58: InitializeButton()
   [string "@Interface/AddOns/Neuron/Objects/Bar.lua"]:982: LoadObjects()
   [string "@Interface/AddOns/Neuron/Objects/Bar.lua"]:284: Load()
   [string "@Interface/AddOns/Neuron/Neuron.lua"]:151:
      Interface/AddOns/Neuron/Neuron.lua:111
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66:
      ...AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:61
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: EnableAddon()
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626:
      ...AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:611
   [string "=[C]"]: LoadAddOn()
   [string "@Interface/AddOns/BattlePetCageMatch/BattlePetCageMatch.lua"]:1098:
      ...ace/AddOns/BattlePetCageMatch/BattlePetCageMatch.lua:1087
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66:
      ...AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:61
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: EnableAddon()
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626:
      ...AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:611
   [string "=[C]"]: LoadAddOn()
   [string "@Interface/FrameXML/UIParent.lua"]:544: UIParentLoadAddOn()
   [string "@Interface/FrameXML/UIParent.lua"]:753: MajorFactions_LoadUI()
   [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: SetUpMajorFactionList()
   [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: RefreshMajorFactionList()
   [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: RefreshOverlay()
   [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80:
      ...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: CreateFrame()
   [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: CreateOverlay()
   [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: RefreshExpansionOverlay()
   [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35:
      ...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33

Count: 1
Message: Interface/AddOns/Neuron/Objects/Button.lua line 936:
   attempt to index field 'data' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Neuron/Objects/Button.lua"]:936: GetMacroEquipmentSet()
   [string "@Interface/AddOns/Neuron/Objects/Button.lua"]:683: UpdateStatus()
   [string "@Interface/AddOns/Neuron/Objects/Bar.lua"]:1320: UpdateObjectStatus()
   [string "@Interface/AddOns/Neuron/Neuron.lua"]:411: ToggleBarEditMode()
   [string "@Interface/AddOns/Neuron/Neuron.lua"]:439: ToggleButtonEditMode()
   [string "@Interface/AddOns/Neuron/Neuron-MinimapIcon.lua"]:78: Minimap_OnClickHandler()
   [string "@Interface/AddOns/Neuron/Neuron-MinimapIcon.lua"]:27: OnClick()
   [string "@Interface/AddOns/Bazooka/Bazooka.lua"]:1417:
      Interface/AddOns/Bazooka/Bazooka.lua:1414
Locals:
(*temporary) = "RightButton"
(*temporary) = false
(*temporary) = <function> defined =[C]:-1

**Comment by Addonman** [comment]
I know that are other issues for sure since its prealpha,but what i most wondering is why is Neuron incorectly storeing macro buttons? What i mean by that -if you pull macro out of /m frame into old bars it shows ,but if i put them on new bar created with Neuron 2.0 it doesnt show up. Unless i go to edit bars .In edit you can see those buttons there. Spells show up nicely in new bar.Also few times  i got dc from game only my macro buttons were erased. Rest of buttons were intact in memory.

**Comment by Addonman** [comment]
No news,response?

**Comment by brittyazel** [comment]
I'll look at this when I finish up work today. I have barely played 10.0.5 since it released.

**Comment by brittyazel** [comment]
I just updated the code to remove this error. Seems like Blizz substantially changed how Bag and Menu bars work post-10.0.5, and much of the Neuron underlying code will need to be adjusted. I disabled the bag and menu bars for Neuron to avoid this error codepath. That said, now that the default bag and menubars are movable (albeit with limited customization), do we really have much of a need for the Neuron implementation? The Neuron implementation basically just hi-jacked the buttons from the stock bars and packed them up onto a Neuron bar, which wasn't particularly sophisticated.

**Comment by Addonman** [comment]
Not sure if you actually checked Blizzard solution- you can move  both bars , but you can make menu bar only bigger and you can resize (up/down)  bag bar.  Not of best solutions IMO. So if there is chance to do it and its not too much of hassle to do it pls keep      resize options for at least menu bar. 10x in advance.
forgot to add -you can place Blizz bars only inside there grid system-meaning they are snapin to blizz grid.So if other bars are not alliend to that grid  your blizz edited bars are not allined to other bars.

**Comment by brittyazel** [comment]
Gotcha. I'll do what I can to make the new bag and menu changes work for Neuron, but for now you'll have to live with the stock ones. At least it's not broken this way, albeit less ideal. I started down the path of porting their changes over, but it quickly became clear it was going to be a chunk of work to do. They effectively re-wrote the way these two bars work and their associated utility functions. Likewise, I've already found bugs and holdovers in the Blizz code, so it's likely going to continue to change, making it a moving target we need to now chase after.

**Comment by Addonman** [comment]
Thanks for that. I almost feel your pain (not coder my self) since sometimes it feels Blizz coders are idiots. Giving community edit mode and then leave it with out 3 basics edits  (width ,length and function to resize it with keeping aspect ratio of them-scaleing) it just feels idiotic. 
Not sure if it would help you but there is wa that can resize some of elements -objective tracker and alike. It had bag and menu resizeing (didnt use it personally -neuron was better ) as well but he removed it with 10.0.5. 
 https://wago.io/dI8GCw2bf  
I use it to resize objective tracker  and i am sure you know how taint inclined piece of ui it is.
