### ISSUE TITLE
10.1 bug

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#507]
Message: Interface/AddOns/Neuron/Objects/Bar.lua line 72:
   Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: NeuronExitBar1:SetPoint.
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=[C]"]: SetPoint()
   [string "@Interface/AddOns/Neuron/Objects/Bar.lua"]:72: new()
   [string "@Interface/AddOns/Neuron/Neuron-Startup.lua"]:73: CreateBarsAndButtons()
   [string "@Interface/AddOns/Neuron/Neuron.lua"]:104:
      Interface/AddOns/Neuron/Neuron.lua:65
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66:
      ...AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:61
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:494: InitializeAddon()
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:619:
      ...AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:611
Locals:
(*temporary) = <function> defined =[C]:-1

**Comment by Addonman** [comment]
Count: 1
Message: Interface/AddOns/Neuron/GUI/MainWindow.lua line 85:
   attempt to index field 'currentBar' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Neuron/GUI/MainWindow.lua"]:85: PopulateEditorWindow()
   [string "@Interface/AddOns/Neuron/GUI/MainWindow.lua"]:70: CreateEditor()
   [string "@Interface/AddOns/Neuron/Neuron-MinimapIcon.lua"]:56: Minimap_OnClickHandler()
   [string "@Interface/AddOns/Neuron/Neuron-MinimapIcon.lua"]:27: OnClick()
   [string "@Interface/AddOns/Bazooka/Bazooka.lua"]:1417:
      Interface/AddOns/Bazooka/Bazooka.lua:1414
Locals:
(*temporary) = "LeftButton"
(*temporary) = false
(*temporary) = <function> defined =[C]:-1

**Comment by brittyazel** [comment]
I'll take a look when I can, thanks.

**Comment by TruthNZ** [comment]
I resolved it by commenting out line 72 completely. Not sure what the side effects of that might be tho.

**Comment by brittyazel** [comment]
Yeah this one is a bit strange. I got the same error on a different addon of mine as well, so it seems like blizz is doing something different with how frames are working. Your comment seems to do the trick though, and I don't see any adverse effects. I was a bit caught off guard with the way bar dragging works now, with the blue box moving first and then the bar itself snapping once placed. That must be something @ylixir added.
