### ISSUE TITLE
Vehicle button not working (introduced in 7.3.5)

### ISSUE THREAD

**Issue by pottervogel** [brittyazel/Neuron#52]
the vehicle buttons don't work - only the fixed exit button.
maybe only german client? i will test later and report.

**Comment by brittyazel** [comment]
Weird, this isn't an issue for me on the english client. I just tested it and can confirm that all of my vehicle ability buttons and the exit button worked as intended.

**Comment by pottervogel** [comment]
sorry, my bad - neurons vehicle bar works fine - there is an addon incompatibility i have not found yet

**Comment by brittyazel** [comment]
Ok cool. Thanks for the update!
