### ISSUE TITLE
One Action Bar Button Not Working Periodically, Maybe Vehicle Related

### ISSUE THREAD

**Issue by HolteUnderscore** [brittyazel/Neuron#55]
Posting this at Soyier's request as first posted on CurseForge:

I'm experiencing a weird bug too.  I have my main bar as a 20 button bar with 5 columns / 4 rows to match the buttons on a Razer Orbweaver.  Button 20 in that layout (bottom right corner) keeps giving me the message "You cannot do that right now" or words to that effect after a while.  If I reloadui, it works again.  It's happening on multiple chars and hence, multiple classes.  I get it if the button is a macro or just an ability from the spell book.

Addendum - I can confirm this bug occurs every time after using a vehicle.

**Comment by Trajin** [comment]
I'm seeing a similar problem.   I also remap the numbers and the layout to match my MERC Stealth.   I have the action bar 1, button 12 doing that same message.    What I've found is that left mouse won't click the button but right clicking will activate the ability.   Logging the character out and back in usually will reset it.   But it will eventually do it again.   And with multiple characters.   My work around is to create another bar and replace the action bar 1 with this new bar.   Maybe there's something going on with that last button in action bar 1.

**Comment by HolteUnderscore** [comment]
Just to update, this isn't fixed following your latest releases this week.

**Comment by brittyazel** [comment]
Thanks for the heads up, I didn't think it would be. I was already far into the major code rework when you filed this bug report so I was finishing all those loose ends first. I'll look into this in the coming days

**Comment by Trajin** [comment]
I have an interesting update to this one.  I rearranged my action bar to just leave that last button open.   I ran some dailies and now it has the Lightbound Crystal quest item appearing on it.   I didn't put it there.   maybe this will help troubleshoot what is happening.  I'm off to do more dailies and will update if it happens again with quest items using that last action button.

**Comment by Trajin** [comment]
This probably should be it's own ticket, but when you drag an item off the bar, you wont be able to click on anything else.  It tries to swap the icons with what you removed.  I use the lock feature and use the shift key to drag icons.   I've found that reloading the UI will reset this.

**Comment by HolteUnderscore** [comment]
Further update, this issue still persists following the latest couple of updates.

**Comment by brittyazel** [comment]
Yeah I haven't done anything to fix it yet. Sorry guys. Gettin to it

**Comment by Trajin** [comment]
This just happened again while in westfall. did the quest where you take control of the harvester golem.  Right after that quest, I was unable to use the last button on my main bar.   I have mount on there, left clicking got the error that you cant do that right now.   Right clicking it got it to launch.

**Comment by brittyazel** [comment]
Does it still make sense to make the last ability on the bar the exit vehicle button? The extra bar is the exit vehicle button too, no?

**Comment by Trajin** [comment]
This is happening after coming back from being in vehicle mode.  It should be back to normal but that last button of the main action bar no matter how many buttons that are in that bar

Sent from my iPhone

On Mar 9, 2018, at 9:24 PM, Britt Yazel <notifications@github.com<mailto:notifications@github.com>> wrote:


Does it still make sense to make the last ability on the bar the exit vehicle button? The extra bar is the exit vehicle button too, no?

**Comment by Addonman** [comment]
I noticed this behaviour as well and to add to issue i noticed it was happening after changing zones in some way-zoneing in for raids,wq or someething similar.

**Comment by brittyazel** [comment]
Fixed this. Sorry for the delay. I really didn't like the code that was put in place to turn the last button on the bar into the "exit" button. It was hacky as all hell, so I just took it out. If you are in a vehicle, the extra button will still allow you to exit vehicle on command, and if you are mind controlling someone you can just push ESC like you would with the default UI.
