### ISSUE TITLE
profiles - copy, and persistence

### ISSUE THREAD

**Issue by teh-fixerer** [brittyazel/Neuron#58]
Not sure if this has been covered, but in some instances (hard to track down the sources), status, bag, pet bars are not being saved properly between sessions.  Also copying profiles feature seems to have this same issue.

**Comment by brittyazel** [comment]
This should be fixed on my Ace-Event branch I've been working on. This was do to the order the addons were being loaded, and with those 4 modules as separate addons I could not control very nicely how they load in relation to the main Neuron addon. I've brought the 4 modules into the main addon though going forward to align them with the zone ability bar and the extra bar. This gives me way more control, and their settings are saved right alongside all the other neuron settings.

**Comment by brittyazel** [comment]
I just finalized and pushed all my conversion for Ace3-Event to master, do you mind testing and letting me know if this issue is fixed/you encounter any issues? I change A LOT of code, and I'm just a bit scared to push a new release without more eyes testing lol. On my end it's stable :-)

**Comment by teh-fixerer** [comment]
Forgive my noobness, but a little unsure as to how test the module(s) properly.  When I replaced neuron with the download from git code, I couldn't edit bars or buttons.  Replacing the files by overwriting them produced a lot of lua errors.  So I may need a nudge in the right direction to be able to help test. 
    On Saturday, February 24, 2018, 3:28:25 PM CST, Britt Yazel <notifications@github.com> wrote:  
 
 
I just finalized and pushed all my conversion for Ace3-Event to master, do you mind testing and letting me know if this issue is fixed/you encounter any issues? I change A LOT of code, and I'm just a bit scared to push a new release without more eyes testing lol. On my end it's stable :-)

**Comment by brittyazel** [comment]
Not a problem, I moved a bunch of files around so it was probally the old pet/status/bag/menu sub-addons lingering around. All of those files should be deleted as of now. 

It's fine though, the new version was pushed in Curse early this afternoon, so you can test it with the standard curse install now.
