### ISSUE TITLE
feature request: match Blizzard changes to allow pet spells on standard action bar

### ISSUE THREAD

**Issue by teh-fixerer** [brittyazel/Neuron#59]
Not a pressing issue but it would be nice to be able to have pet spells on Neuron action bars.

**Comment by brittyazel** [comment]
agreed

**Comment by brittyazel** [comment]
I looked into this today, but it seems like this can't be done at the moment. When querrying the cursor I.E. GetCursorInfo(), pet actions don't return any usable info besides "petaction", thus we have no identity to build a macro from. :-/

**Comment by brittyazel** [comment]
Good news! I didn't forget about this issue and I fixed it! You can now drag pet abilities onto the bar just like normal abilities. Cheers!
