### ISSUE TITLE
Issue: Action bar - Vehicle state

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#6]
I've just test on my action bar #1 the vehicle state.
The Icons switch to the right state (exemple Lightforged Warframe from the Vindicar), but the macro behind it still get the "homestate" value.
I need to sometime reset the macro on one button of the vehicle state to get the right action activated when used.
No error logged.

**Comment by brittyazel** [comment]
Weird, I haven't noticed this, but I made some changes to this so perhaps I broke it and forget to test it. I'll check it out :-) Thanks for the report!

**Comment by brittyazel** [comment]
I can't seem to replicate this. When I launch my warframe I immediately can use the warframe abilities... hrm...

**Comment by SirLagardere** [comment]
To be more explicit, I launch the warframe, I can use, for exemple, action 1 and 3 but second is a no go (UI error message you should have a weapon equiped).
I then edit the culprit and find a macro identical to the "homestate", including Icon (different from what I see on my bar). Reset it, good to go, but sometime it comes backs...
And if it could help you, when the bar state change, I've got background on 9 icons like my "homestate" bar (like a shadow of buttons placed on it), and the first 3 are the vehcile actions. (compared to my stealth bar state, also on my action bar #1, where not used button are completly transparent.)
I'll try to get a screenshot of this if it meens something.

**Comment by brittyazel** [comment]
That's weird because when I use my Warframe all the buttons are cleared to blank and only the first couple have new abilites in them. Can you double check for me that on the main bar you have then vehicle state enabled

**Comment by SirLagardere** [comment]
Here a screen capture of my action bar 1 state config 
![image](https://user-images.githubusercontent.com/20615278/31517055-fdf5dd00-af9a-11e7-8644-6c336ed6fdb5.png)
Editing the macro of the 1st button (3 states listed)
![image](https://user-images.githubusercontent.com/20615278/31517119-397e0884-af9b-11e7-8061-bc0147bdf096.png)
And the "ghost" buttons
![image](https://user-images.githubusercontent.com/20615278/31517160-5e47f2ba-af9b-11e7-9b13-12757f75e23e.png)
close up on the bar
![image](https://user-images.githubusercontent.com/20615278/31517169-6a95fcf6-af9b-11e7-9aab-f2e4c65f2ac0.png)
Hope I'm not doing it wrong with the capture.

**Comment by brittyazel** [comment]
Ok so the vehicle config state does have them all blank. At least the way mine works (and the way it is coded to work in theory) is that until you get into a vehicle those macros are blank, and they get populated with the available macro's of the vehicle you are in. In that second set of screenshots are you currently mounted on a vehicle like the warframe or a cannon or something?

**Comment by SirLagardere** [comment]
Second set was to show you that 11 button have a blackish back drop when I select "Vehicle" in macro editing.
If I select "stealth", back drop only appears on populated buttons.
I'll try to get captures from a vehicule point of view, but, yes until I get into one, no problem, I jump in, bar state change. I check the macro, only Icon are selected, no macro text, and sometime in combat (or maybe when the combat state change), the macro text zone is fill with the homestate, and even if the bar show me the right icon, editing show me everything of the homestate button, including icon...
Very strange.

**Comment by SirLagardere** [comment]
I just recreate everything from a fresh profile, and still get the problem. It seems to be related with the in and out of combat state. The "override" seems to happen between an "out" to a "in" combat.

**Comment by brittyazel** [comment]
interesting. I don't have in/out of combat enabled on this bar and I don't get the problem. If that is the case, it would seem that the combat state takes preference over the vehicle state, which I need to fix. Can you turn off the combat state and see if that helps for now?

**Comment by brittyazel** [comment]
Ok I came to the bottom of this one finally, it has to do with the way "states" are treated, and that we don't currently have a priority list. This issue is not just with the vehicle bar, but also shows up with stances (druid forms) and such as well. Whatever the latest state to be activated is always takes over, hence entering combat after being in the vehicle state switches you to the combat state. Just like being in my bear form state switches me to a "combat" state once I enter combat.

This is pretty annoying, but I need to figure out a way to work around it. However, for now just keep in mind that situational states such as "combat"/"outdoors"/"indoors" might mess with explicit states such as "alt"/"shift"/"vehicle"/"possess" etc.

The only thing I can say for now is don't use the combat state on the same bar as you have explicit states for now.
