### ISSUE TITLE
Status bar on/off

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#62]
Personally i dont use status bars in neuron and i have them swiched off in addon panel but after latest update status file is still there and thicking it off does nothing as status bars still show in game.Can you add something so we can have option of not use them at all or turn them of with 1 button instead of using option in each of them makeing them hidden.

**Comment by brittyazel** [comment]
Yes the status bar is now a core part of Neuron and no longer a sub-addon module. The fact that it is still showing in the addon list is just because the Neuron-Status folder is still sitting in Interface>addons, but it just an empty shell. Because I cannot physically reach into your computer to delete the file it had to stay unless you choose to get rid of it.

Have you tried just deleting the status bars you don't want? Instead of hiding them why not just delete the bars?

**Comment by Addonman** [comment]
No i didnt try to delete them in case i might use them if addons i am using now for them get broken in future and not to having to mess with setting them up if i use them in future. 
Also deleting folder wouldnt help me since your curseforge file still has neuron-staus folder in them so even if i delete them i guess it would still end up there even if only contains neuron-status.toc .It shows disabled in addon list but still shows there and thats little bit confusing.
Not 100% sure but i think i noticed before curse/twitch app erasing old folder structure and making new .

**Comment by brittyazel** [comment]
Oh if that's the case then I'll can delete them. I just kept them in solely for the purpose of overwriting the .toc file with one that was empty.

**Comment by brittyazel** [comment]
Ok new release out that deletes all the old crap files. You were right about it deleting the addon before updating it, nice.

I'm going to close this bug report because I think the solution to you problem is just to delete the bars you don't want. You can easily remake them if you want them back.

**Comment by Addonman** [comment]
Maybe just add some kind of option to select which status bar to create since if am correct now if you need only 1 type of status  bar but nothing else addon creates bars in certain order so oi the end you need to again delete what you dont need.

**Comment by brittyazel** [comment]
Oh no, you can set any status bar/button to be any type, i.e. cast bar/rep bar/xp bar from the button edit window. From there you can also change width/height texture, etc

**Comment by Addonman** [comment]
Checked it.It there but its imo totally nonintuitive so maybe it would be better to move those setting into editing bars not buttons if possiable ofc. If you didnt tell me that i am 99.9% sure i wouldnt even think to look there.

**Comment by brittyazel** [comment]
Yep I hate the UI as it is today. My goal is to strip out the entirety of the UI and rebuild it from scratch. I just need to find the time to make it happen. This latest update will be the bedrock for it though, as I couldn't do anything to the addon going forward without the changes that I made this last week. I'm still in the neverending process of removing all the old/dead workarounds and hacks, and finding and pruning all the dead code that was just copy-paste from other mods. I need to get us to a "blank" canvas so to speak so I can actually enhance the addon. Right now I'm just trying to fix all the broken/ugly crap while not breaking anything that currently works lol.
