### ISSUE TITLE
blizzard breath/fatigue bar still hidden when mirror bars deleted

### ISSUE THREAD

**Issue by Trajin** [brittyazel/Neuron#65]
I never used the ION status bars in my UI, so I didn't load that piece of the addon.   In my UI most were replaced with other addons.    I've deleted all the status bars and now the default breath/fatigue bar is still hidden.   Can this be unhidden if the status/mirror bars are disabled/deleted?

**Comment by brittyazel** [comment]
Oooh that's a solid point. I didn't think of that implication when I brought the modules into the core addon.  Yes I will add some code to not disable the default breath/fatigue bars unless there is a Neuron equivalent. For now, however, that isn't an option, and I apologize

**Comment by Trajin** [comment]
Thanks for the quick response.  Glad to be able to assist.  Now to get the neuron addin to be in the addon button list in sexymap addon.  I like the addon buttons to hide until moused over.

Sent from my iPhone

On Mar 5, 2018, at 7:41 PM, Britt Yazel <notifications@github.com<mailto:notifications@github.com>> wrote:


Oooh that's a solid point. I didn't think of that implication when I brought the modules into the core addon. Yes I will add some code to not disable the default breath/fatigue bars unless there is a Neuron equivalent. For now, however, that isn't an option, and I apologize

**Comment by brittyazel** [comment]
This is fixed and will be in the latest release
