### ISSUE TITLE
Lua error entering and leaving timewalking dungeon (cata)

### ISSUE THREAD

**Issue by teh-fixerer** [brittyazel/Neuron#67]
Not sure the cause.  On my warrior, and has some links to ace event?
Message: Interface\AddOns\Neuron\Neuron.lua:716: IsPassiveSpell(): Invalid spell slot
Time: 03/16/18 16:35:33
Count: 2
Stack: Interface\AddOns\Neuron\Neuron.lua:716: IsPassiveSpell(): Invalid spell slot
(tail call): ?
[C]: in function `IsPassiveSpell'
Interface\AddOns\Neuron\Neuron.lua:716: in function `UpdateSpellIndex'
Interface\AddOns\Neuron\Neuron.lua:424: in function `?'
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by brittyazel** [comment]
Strange, did this dungeon have some dungeon specific ability that you get?

Did it happen right after leaving the dungeon, like right after the loading screen?

**Comment by teh-fixerer** [comment]
Happened once yesterday on "end time" but i thought it was a glitch, but happened again today on "stonecore".  Error happened once right after zone in, and again after zone out.  I'll try disabling different action bars to see if i can help narrow it down.

**Comment by brittyazel** [comment]
this is weird, and it shouldn't be failing. It's odd that the aceEvent trace is for a "WildPants" addon or something. I wonder if that addon did something to modify the IsPassiveSpell() ability. Can you try disabling that addon to see if it comes back?

**Comment by teh-fixerer** [comment]
ahah thanks for that clue.  I checked my addons NS "wildplants" is part of Bagnon.  will keep at tracing it.

**Comment by teh-fixerer** [comment]
disabled bagnon, just did Vortex pinacle, get a different error, now pointing through neuron to handy notes, both after zone in, and zone out

Message: Interface\AddOns\Neuron\Neuron.lua:716: IsPassiveSpell(): Invalid spell slot
Time: 03/16/18 22:07:33
Count: 2
Stack: Interface\AddOns\Neuron\Neuron.lua:716: IsPassiveSpell(): Invalid spell slot
(tail call): ?
[C]: in function `IsPassiveSpell'
Interface\AddOns\Neuron\Neuron.lua:716: in function `UpdateSpellIndex'
Interface\AddOns\Neuron\Neuron.lua:424: in function `?'
...ore\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ore\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ore\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...AddOns\HandyNotes\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\HandyNotes\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by teh-fixerer** [comment]
both bagnon and handy notes disabled:
Message: Interface\AddOns\Neuron\Neuron.lua:716: IsPassiveSpell(): Invalid spell slot
Time: 03/16/18 22:41:31
Count: 1
Stack: Interface\AddOns\Neuron\Neuron.lua:716: IsPassiveSpell(): Invalid spell slot
(tail call): ?
[C]: in function `IsPassiveSpell'
Interface\AddOns\Neuron\Neuron.lua:716: in function `UpdateSpellIndex'
Interface\AddOns\Neuron\Neuron.lua:424: in function `?'
...ore\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ore\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ore\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ace\AddOns\Neuron\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ace\AddOns\Neuron\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by brittyazel** [comment]
Alright interesting. I'll have to dig into this one

**Comment by teh-fixerer** [comment]
definitely something happening on zone in/out.  Just had neuron disabled before zoning in and enabled it once i was in and no errors.  Was still enabled when i zoned out and the error appeared.    Not a big dig deal really i guess - just an annoyance - since the error only happens on load and exit and doesn't prevent game play,.

**Comment by brittyazel** [comment]
The annoying thing is it is happening only on timewalking. It's like the abilities are momentarily changing right as we are quering their data and thius throwing an error. I'm not sure how to fix this honestly

**Comment by brittyazel** [comment]
Querying*

**Comment by brittyazel** [comment]
I'm pretty sure this is fixed now
