### ISSUE TITLE
Pet ,zone or extra bar acting weirdly.Easy way reseting them and replacing them?

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#68]
Normal behavoiur -no pet no bar,no  zone spell no zone button, basicly shown when there is something to press.
Recently for some unknown reason my bars dissapered or changed behaviuor.they would show all the time with no buttons on them or they wouldbe hidden until i mouseover them.What i call weird here is that with same settings they act differnently on diff char.On one char they act normally but when i try to set them same odd behaviour is still there and nothing changes.
Is there easy way of reseting only those 3 bars and put them in default state?I ask because after i erased them i couldnt find a way to recreate them since menu for recreating bars doesnt  have that option in it and i couldnt find option.Maybe they have some kind weird setting like status bar in buttons menu not sure but i couldnt find it. Ofc there is  way to erase everything and start from start but pain in ass or what i did and luckily i had copy from other char.

**Comment by brittyazel** [comment]
I'll look into it. You should be able to remake the bars, and it's odd that it won't let you

**Comment by Addonman** [comment]
I get menu with few bars but not for zone and extra bar.i think i can create pet bar but its either stay visable or hidden until you mouseover it even if its on char that doesnt really have pet  like it happened on my druid - normally it stay hidden and not reacting on mouseover.

**Comment by brittyazel** [comment]
If you already have a zone and extra bar made, it won't let you make any more and that option will be hidden. Is it possible that you still have bars of those types? That's the only reason those bar types wouldn't be showing

**Comment by Addonman** [comment]
Oh didnt know you can make only one and thats it hidden.I was trying to find a way how to create one when i already had one ,but not working correctly since i wasnt sure if i was going to be able to create one when i erase not working one.

**Comment by brittyazel** [comment]
Fixed I'm pretty sure, please test
