### ISSUE TITLE
Pet Bar problem

### ISSUE THREAD

**Issue by pottervogel** [brittyazel/Neuron#69]
I started a hunter and copied the profile of one melee char because of the layout and a lot of utility buttons  I have all over my chars.. In this profile was no pet bar so i created a new one. This bar has no buttons and i can not create buttons. Tried this several times. Then I made a new action bar and tried to set the state to pet - this time i could create buttons, but the pet state is not working also.

**Comment by brittyazel** [comment]
Yeah I need to figure out why people can't make new pet buttons, I had a similar issue and I could make 10 pet buttons perfectly fine.

I won't have a solution for you until after Monday, I'm headed to Seattle for a work conference over the weekend

**Comment by pottervogel** [comment]
its not a big deal for me,  i use the petbar from elvui for now
just wanted you to know

**Comment by brittyazel** [comment]
Fixed
