### ISSUE TITLE
Keybind save 

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#72]
Is it posiable to save keybinds per char per spec specifically?

**Comment by brittyazel** [comment]
Not at the moment no, I'd like that to be an option, but I have to do a lot of work until that is the way it is. With BfA coming out too there's a ton of changes being made to addons, a lot of which will affect Neuron, so I need to work on that as well.

**Comment by Addonman** [comment]
As i was using  i think raeli spell announcer i noticed it can store profiles for each spec so maybe you can get inspiration or code from there.

**Comment by DejayRezme** [comment]
Can't this be done already with duplicating your profile and using "Enable spec profiles"?

**Comment by ylixir** [comment]
i'm pretty sure this can be done with per spec profiles. closing
