### ISSUE TITLE
icon for equipped item not updating

### ISSUE THREAD

**Issue by randomblackactor** [brittyazel/Neuron#76]
Hi there...absolutely love your addon, probably the best I've seen and I've played since 1.6.  Seeing one small problem...I have a macro for /use 13 set on a button bar, but when I switch the equipped trinket, the icon doesn't change.  I checked the macro itself, and it does automatically update the icon whenever I change the item.

**Comment by brittyazel** [comment]
Yeah I probably need to add a condition to check for equip of trinkets and force a refresh. Can you see if after you switch the trinket and it doesn't update the icon if /reload will force the proper icon to load?

**Comment by randomblackactor** [comment]
Yes, it looks like /reload successfully updates the icon and displays the correct tooltip.

**Comment by brittyazel** [comment]
Cool so it's just a refresh issue. I need to find what trigger fires when switching a trinket and hook the refresh to that

**Comment by brittyazel** [comment]
This is fixed
