### ISSUE TITLE
Issue: Blizzard MultiBarAction appears

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#8]
Sometimes, the "MultiBarAction Right" appears even if the "Display Blizzard Bar" option is uncheck. And until now, only this bar.
No error logged when trigger

**Comment by brittyazel** [comment]
Yeah you have to disable that in the blizzard interface options for now. Disabling the blizzard bar only disables that bar specifically. Some people like to still use the default bars for the right hand of the screen, as it will move the quest tracker to the left when they're out
