### ISSUE TITLE
Default bar showing up when mousing-over an ability in the spellbook

### ISSUE THREAD

**Issue by Koskun** [brittyazel/Neuron#80]
It has only started since the last update.  If I open the spellbook, the moment I mouse over an ability, the default action bar slides up, over top of Neruron.  I go into the options for Neuron and "Display the Blizzard Bar" is not checked.  If I check it then un-check it the default bar goes away.  As soon as I mouse over something in the spellbook again, the default bar just slides right back up.

It does not matter if an ability is on a bar, whether it is default (which I don't use at all, it is only populated by the default actions, I strictly use Neuron).

This is happening on all my characters, regardless of spec, on existing profiles, a reset profile (as I had the bug of the bag, menu, rep/xp, cast bars bug out on me), and on a new profile.

The default options for Action Bars, I have everything unchecked.

**Comment by brittyazel** [comment]
I'll look into this today, asap.

**Comment by brittyazel** [comment]
Ok I'm trying to replicate this, and I just can't. Are you using titan panel by any chance? I think it may be in part to another addon "un-hiding" the blizzard bar, as indicated by the "check then un-check". If it was Neuron that was re-enabling the bar on accident the checkbox would reflect that

**Comment by brittyazel** [comment]
Cool, I answered it myself. I downloaded Titan panel and the issue started happening to me as well, so I added some code in that fixes it. It detects when Titan loads and compensates for it.

**Comment by Koskun** [comment]
I much appreciate how quickly you got into this.  

Sorry for not getting back sooner, work actually had me come in for a few hours.  :P
