### ISSUE TITLE
Pet bar and Extra bar options to hide bind text/change color aren't working

### ISSUE THREAD

**Issue by brittyazel** [brittyazel/Neuron#84]
On the Pet bar and Extra bar, you can't toggle off showing keybinds, nor can you change the color of the cooldown. I'm not sure what other implications this bug has, but it is bar-type specific, which is weird because those functions are bar agnostic. It is probably a small thing in those bar object that is messing this up

**Comment by Esememon** [comment]
I did a thing, and now this is fixed. Looks like pretty much everything else was working.

Also, Extra bar already seemed to be working (or I fixed it with magic), at least in the scope of this issue. It has its own quirks.
