### ISSUE TITLE
Create Menu or Bag Bar doesn't populate buttons

### ISSUE THREAD

**Issue by elphyne** [brittyazel/Neuron#85]
if i remove a button from the menu bar or bag bar there is no way to get the button back. adding a button to the menu or bag bar doesn't populate the button. if i delete the menu bar and then do the option to create bar / menu bar or bag bar it still won't populate any buttons. the bars start off with 0 buttons when created this way and adding the buttons doesn't do anything.. its not even creating empty buttons that i can edit, altho the bar in edit mode does change in size to indication buttons were added. no errors popped up

**Comment by brittyazel** [comment]
I'll look into this tonight. Thanks for the heads up

**Comment by brittyazel** [comment]
fixed, it was a minor logic error.
