### ISSUE TITLE
Error when making new profile or switching to another if i don't reload right away

### ISSUE THREAD

**Issue by elphyne** [brittyazel/Neuron#90]
if i create a new profile or switch to a different profile and i don't  hit the restart button within a few seconds of doing so i get an error report which keeps triggering until i restart it. this happens even when i clear my wtf folder and i only had neuron and bugsack and buggrabber addons installed. this happens even if i just start with the default character-server profile and switch to the default profile with nothing yet on the bars themselves

the error message i get is

306x Neuron\Neuron-Flyouts.lua:1514: attempt to compare nil with number
Neuron\Neuron-Flyouts.lua:1514: in function `updateAnchors'
Neuron\Neuron-Flyouts.lua:78: in function <Neuron\Neuron-Flyouts.lua:78>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 EnableModule = <function> defined @Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 baseName = "Neuron"
 IterateEmbeds = <function> defined @Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 SecureHook = <function> defined @Neuron\Libs\AceHook-3.0\AceHook-3.0.lua:336
 Flyout_GetBar = <function> defined @Neuron\Neuron-Flyouts.lua:1365
 Anchor_RemoveChild = <function> defined @Neuron\Neuron-Flyouts.lua:1422
 RawHookScript = <function> defined @Neuron\Libs\AceHook-3.0\AceHook-3.0.lua:395
 linkScanOnUpdate = <function> defined @Neuron\Neuron-Flyouts.lua:1532
 COMPANION_LEARNED = <function> defined @Neuron\Neuron-Flyouts.lua:236
 defaultModuleState = true
 IsEnabled = <function> defined @Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 DisableModule = <function> defined @Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:381
 SPELLS_CHANGED = <function> defined @Neuron\Neuron-Flyouts.lua:197
 RegisterMessage = <function> defined @BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 UnregisterMessage = <function> defined @BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 Flyout_SetData = <function> defined @Neuron\Neuron-Flyouts.lua:1223
 hooks = <table> {
 }
 Flyout_GetButton = <function> defined @Neuron\Neuron-Flyouts.lua:1271
 TOYS_UPDATED = <function> defined @Neuron\Neuron-Flyouts.lua:299
 SetEnabledState = <function> defined @Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @Neuron\Libs\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 RegisterEvent = <function> defined @BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 updateAnchors = <function> defined @Neuron\Neuron-Flyouts.lua:1506
 filter_mount = <function> defined @Neuron\Neuron-Flyouts.lua:587
 IterateModules = <function> defined @Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 RawHook = <function> defined @Neuron\Libs\AceHook-3.0\AceHook-3.0.lua:313
 CHARACTER_POINTS_CHANGED = <function> defined @Neuron\Neuron-Flyouts.lua:210
 OnInitialize = <function> defined @Neuron\Neuron-Flyouts.lua:64
 UnregisterAllEvents = <function> defined @BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 Flyout_RemoveButtons = <function> defined @Neuron\Neuron-Flyouts.lua:1140
 GetModule = <function> defined @Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:241
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Neuron\Neuron-Flyouts.lua:285
 defaultModuleLibraries = <table> {
 }
 ANCHOR_DelayedUpdate = <function> defined @Neuron\Neuron-Flyouts.lua:1595
 filter_pet = <function> defined @Neuron\Neuron-Flyouts.lua:701
 OnEnable = <function> defined @Neuron\Neuron-Flyouts.lua:100
 timerFrame_OnUpdate = <function> defined @Neuron\Neuron-Flyouts.lua:314
 GetBlizzData = <function> defined @Neuron\Neuron-Flyouts.lua:811
 Flyout_ReleaseBar = <function> defined @Neuron\Neuron-Flyouts.lua:1350
 EQUIPMENT_SETS_CHANGED = <function> defined @Neuron\Neuron-Flyouts.lua:263
 GetName = <function> defined @Neuron\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 PLAYER_INVENTORY_CHANGED = <function> defined @Neuron\Neuron-Flyouts.lua:164
 Flyout_ReleaseButton = <function> defined @Neuron\Neuron-Flyouts.lua:1198
 SecureHookScript = <function> defined @Neuron\Libs\AceHook-3.0\AceHook-3.0.lua:410
 name = "Neuron_Flyouts"
 Flyout_RemoveBar = <function> de

**Comment by brittyazel** [comment]
I can't replicate this, but I added some logic to return gracefully if button doesn't exist during that in-between stage
