### ISSUE TITLE
Arrows on bar editor options bug out if you hold the arrow down

### ISSUE THREAD

**Issue by elphyne** [brittyazel/Neuron#93]
if you hold the button down on the arrow to change any of the options involving numbers on the bar editor options portion the numbers just keep growing until you move the mouse off.. but if you put it back over it will still keep going.. i've managed to get it to sort of stop if i hold the button on the other side down for a bit but it won't let me type anything in the number box anymore and clicking the spot where the number is just increases or decreases the size as if i were clicking the arrow button. if you type the numbers in to begin with you're fine it seems.. or after reload if you've hit the arrow button.. the only option not effected seems to be the number of buttons arrow because holding them down doesnt change the number more then for the initial click. i could have sworn it had been an ongoing issue. but maybe i'm mistaken..

**Comment by brittyazel** [comment]
fixed, will be in the next version
