### ISSUE TITLE
Bar list on left side of the editor doesn't scroll

### ISSUE THREAD

**Issue by elphyne** [brittyazel/Neuron#94]
it shows the arrows, but no scroll bar until i click an arrow or use my mouse wheel, but nothing will scroll no matter which method i try and no matter how many bars past 15 i make... mouse scrolling.. clicking arrows.. dragging the scroll bar once it shows up... it just stays where it is on the list.

I can get the list to move sort of tho. if i were to be seeing say the top of the list "action bar 1" and needed to see whatever name is the 16th bar that doesn't show up on the screen, i can click the arrow at the bottom of that side area and then click the bar name name and it will scroll down basically all the way down.. so if i had like 40 bars.. i would only be able to see the bottom 15 bars now.. but nothing in between unless i manually move the scroll bar to like the bottom middle.. and then click a bar also on the bottom middle it would move down in more of an increment.. so technically there's still a way to view everything on the bars list.. its just.. really annoying trying to if you have an excessive amount of bars.. which i don't but i tested it because i figure you never know.. someone might!

**Comment by brittyazel** [comment]
This is a solid point. The reason this isn't working is because Blizzard removed the FauxScrollFrame functions that this part of the GUI was built on. I don't want to spend time rewriting it right now, becasue i'm just going to end up deleting all that code anyway. None of the GUI code is going to be used in my new AceGUI port

**Comment by ylixir** [comment]
gui redone, closing
