### ISSUE TITLE
0.9.25 : Menu bar behavior

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#99]
Hello,
Since the latest release work on the menu bar, the bar stay visible in pet battle and disapear when the battle ended.
Hope it can be easely fixed :)
Thx

**Comment by brittyazel** [comment]
Ok, so the desired behavior is to disappear during a pet battle? Was this how it was handled before? I don't really do pet battles. And the bar disappears at the end of the pet battle?

**Comment by SirLagardere** [comment]
Actually, until now, when you enter a pet battle, you switch back to the standard Blizzard interface : 
![image](https://user-images.githubusercontent.com/20615278/40939960-878314b6-6846-11e8-9e70-c882f3465498.png)
The neuron menu bar should disapear and the standard menu should be on the right of the battle interface.
When the combat end, the neuron menu bar disapear (until now it was coming back)
And as you see, the menu button is split between the neuron menu bar and the standard interface.

**Comment by brittyazel** [comment]
Yeah this is going to be tricky. The new code works by stealing the default blizzard UI and putting it inside a Neuron Bar, and it seems the combat pet UI is stealing those Neuron buttons back. I'll need to add a condition to stop that from happening, but that still doesn't mean it will give back the buttons after the pet battle.
